### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by InfinCZ** [DevLeoko/AdvancedBan#101]
What version of AdvancedBan (/AdvancedBan) are you using?
2.0.6

What kind of server do you have (Bungeecord/single server)?
Spigot

What server version (/version) are you using?
1.12

Please provide the EXACT steps required to reproduce the problem...

I enable MySQL in config.yml
I fill data to mysql.yml ---> https://postimg.org/image/kqzr8uuev/55a3a5b6/
I look to console and in console is ---> https://postimg.org/image/bs0llb6lr/fecffdaa/

Any error/log post it through pastebin.com and link it here.
https://pastebin.com/6cJtTas2

Add any aditional information below.

Thanks,

Infin

**Comment by DevLeoko** [comment]
Ya seems like your MySQL Data are not valid.
Check them here http://skamps.eu/MySQL/

**Comment by InfinCZ** [comment]
I have web connect with this database and all is ok. But when I make test connect so show text Can't connect to MySQL server on 'wm123.wedos.net'. I solve this problem with my hosting.

Thanks
