### ISSUE TITLE
Request  - Leave a /note on a players history file.

### ISSUE THREAD

**Issue by SiuanSong** [DevLeoko/AdvancedBan#103]
Request
Ability to do /note player to leave a note on the players record without notifying them.  Could be useful for servers that have punishment commands that are not handled by AdvancedBan.  Such as GriefPreventions /softmute and /separate.   Also would be good for keeping track of players that toe the lines of the rules.

**Comment by DevLeoko** [comment]
Ya that's a good idea will be added

**Comment by SiuanSong** [comment]
Any update on this? :P
