### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by yummiesttag** [DevLeoko/AdvancedBan#104]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single server
 
_What server version (/version) are you using?_
http://imgur.com/a/h79Sc

_Please provide the EXACT steps required to reproduce the problem..._
1./warns doesn't work but when I warned the player the warning went though but I can't check warnings.
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/nv6CajdW

_Add any aditional information below._

**Comment by ItzSomebody** [comment]
AdvancedBan isn't compatible with 1.12

**Comment by yummiesttag** [comment]
Ah that would be why then. Any possible updates to when it might be?

**Comment by ItzSomebody** [comment]
I dunno, whenever someone updates the deprecated code XD

**Comment by DevLeoko** [comment]
Please post a list of the plugins you are using.
If you use Staff+, AdvancedBan is not compatible with this plugin

**Comment by yummiesttag** [comment]
I don't use staff+.
13:05:18  [Info] Plugins (54): TMCAntiPortalTrap, PlugMan, AntiAFKPlus, PlayTime, PingPlayer, TMCFly, ViaVersion, ChatColor, ViaBackwards, CoreProtect, AsyncWorldEditInjector, WorldEdit, SuperLogger, AutoMessage, WorldBorder, BuycraftX, Votifier, ProtocolLib, AutoSaveWorld, LibsDisguises, AsyncWorldEdit, PermissionsEx, TsunamiListener, mcMMO, CS-CoreLib, StaffChat, Vault, iControlU, WorldEditSelectionVisualizer, MobArena, HideAndCustomPlugins, WorldGuard, Slimefun, Barrels, PlayerVaults, SpinCrates, SlimeXpansion, Essentials, ExtraGear, CompatNoCheatPlus, Jobs, RandomTP, SlimefunGuidePlus, NoCheatPlus, EssentialsChat, ExoticGarden, TreeAssist, GriefPrevention, SlimefunOres, Slimedustry, PrivateStorage, ColoredEnderChests, SlimeScrap, EssentialsSpawn

**Comment by DevLeoko** [comment]
There are two possible reasons for this issue:
1. There is an incompatibility with another plugin that uses the same commands
> Just check your plugins if there is any plugin with the same commands

2. There is an incompatibility with your spigot version (never tested it on 1.12)
> You will need to wait until I update the resource (in about a month)

**Comment by DevLeoko** [comment]
The updated got released today please tell us if that fixed the problem. If you still use the plugin :P
