### ISSUE TITLE
[Request] Player ban list

### ISSUE THREAD

**Issue by ApertureDevelopment** [DevLeoko/AdvancedBan#105]
Hello,

we are using another plugin, that only looks into the normal ban-list and therefore does not recognize players, banned by your plugin. The best solution would be, if your plugin would have an option to also write banned users into the normal banlist.

Thank you for reading,
~cap

**Comment by ItzSomebody** [comment]
This is very vague.

What is a "normal" banlist???

What is this other plugin?

**Comment by captain1242** [comment]
The banned-ips.json and the banned-players.json

and the plugin is the ServerListPlus plugin. It has a check for banned players but it won't work until the banned player is inside the banned-players.json, or the default bukkit function returns the values from you.

**Comment by DevLeoko** [comment]
Well, I don't think that it would make any sense to save the punishments in this files too.
AdvancedBan provides an API for things like that so you can contact the Dev of the other plugin and ask him to add this feature.

**Comment by captain1242** [comment]
But wouldn't it be better to use the default system instead of creating an own one with API? Not everyone is willing to completly rewrite his plugin just to integrate the API of 1 plugin. Defaults are there so that everyone understands everyone without complicated ways over API's

**Comment by oninoni** [comment]
Also when the plugin is uninstalled people would still be banned.

**Comment by md678685** [comment]
I agree with @captain1242 - this causes issues for us when using other plugins that expect normal bans (`OfflinePlayer#isBanned`) because most plugins won't know that the player is banned, and I don't think many plugin authors will add support for AB just for this.

**Comment by DevLeoko** [comment]
Okey I see as so many people agree with this feature request I'll consider adding it :)

**Comment by captain1242** [comment]
Thank you.

**Comment by DevLeoko** [comment]
Has been added in #170 by @Beelzebu 
You can download the latest build here: http://v.skamps.eu/jenkins/job/AdvancedBanV2/26/
This update will be released in a few weeks on spigot.

Would be great if you could give us some feedback if everything works :)
