### ISSUE TITLE
A problem...

### ISSUE THREAD

**Issue by captain1242** [DevLeoko/AdvancedBan#106]
SQL Injection. 

Read about it. Everything said.

**Comment by ItzSomebody** [comment]
Why is your SQL database open to the world?

**Comment by oninoni** [comment]
That's not how SQL injection works...

**Comment by captain1242** [comment]
That is not what I said. Did you never hear about SQL injection?

**Comment by Possseidon** [comment]
Anybody who has permission to ban players can easily drop the banlist table and possibly crash your plugin. Also the database likely has other data than the banlist, which can break a lot of the server, by just giving someone ban permissions.

**Comment by DevLeoko** [comment]
xD never thought about that
Even though you should only grand reliable persons ban permissions I'm going to prevent SQL-Injection in the upcoming update

**Comment by md678685** [comment]
SQL injection protection isn't a feature. The lack of it is a severe bug.

**Comment by captain1242** [comment]
He is right. It is a Bug, as Developer you should always prevent SQL Injection. Even if just limited users should have ban permissions, you have other commands which might have been added to user commands by server Owners ( like ban lookup )

**Comment by DevLeoko** [comment]
Added in 2.1.0 ;)
