### ISSUE TITLE
Problem with permissions

### ISSUE THREAD

**Issue by cercus** [DevLeoko/AdvancedBan#107]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_ 2.0.6
 
 
_What kind of server do you have (`Bungeecord/single server`)? ->  Bungeecord
 
 
_What server version (/version) are you using? -> CraftBukkit version git-Spigot-6f7aabf-c8ff651 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. -> No errors

_Add any aditional information below. -> I installed this plugin in each server but when I give permission at a player (exemple : ab.kick.use), the player don't made this command

**Comment by ItzSomebody** [comment]
what permissions plugin are you using?

**Comment by supertassu** [comment]
If advancedban is installed at bungee, you have to give the perms at bungee aswell.

**Comment by cercus** [comment]
I just forgot in config.yml (bungeecord) <pseudo>: - <group>
