### ISSUE TITLE
[FEATURE] Ban wave. VAC like ban system.

### ISSUE THREAD

**Issue by SkillzGamingYT** [DevLeoko/AdvancedBan#108]
**_This is a great idea for Anti-cheat makers. And wanted to make server more professional._**

First, Ban wave is like VAC ban system. It will make /banwave add user being add to the ban list after user inputted amount of time user will be banned. 

**Commands:** 
```
/banwave add <name> [ban command eg. 1,2,3] [reason] = add user to banwave
/banwave remove <name> = remove user from banwave
/banwave execute = execute a banwave

```
**What is [ban command] ?**
It's mean what do admin want command on user what to execute after banwave has occurred.

**Examples:**
```
1 : "ban %user% %reason%"
2 : "tempban %user% #hacking %reason%"
```
It will be cool if we can random the time that banwave occur.

**VOTE**: http://www.strawpoll.me/13422738

**Comment by md678685** [comment]
This could just be done with the API. I don't think most people would use this.

**Comment by DevLeoko** [comment]
Well I think this is more like some extra plugin that you would use in addition to a normal ban system but it's not an essential feature. So this is beeing rejected sorry.
