### ISSUE TITLE
Problem about the mysql refreshing

### ISSUE THREAD

**Issue by JeremyZhang2002** [DevLeoko/AdvancedBan#109]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungee
 
_What server version (/version) are you using?_
1.8.8 Spigot

_Please provide the EXACT steps required to reproduce the problem..._
1. Well I am managing a Bungeecord mini game server, I love ur plugin so much plus I also translated to Chinese. Thx for ur work first! But there is only one thing that can better which is about the refreshing of the mysql. I found out the list of players who was punished on the mysql of the server is only reloaded during the restart of server or the reload of the plugin. So I have to restart my servers by my own every time but i got 20+ servers now itz pretty much a hard workd. Can u plz add something like the plugin can reload the profiles from the mysql for in stance every 5 minutes. Plus plz add the option inside the config file that I can choose the reload of profile per how many minutes. thanks! :)
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any aditional information below._
plz help me with this! I luv ur work so much!

**Comment by JeremyZhang2002** [comment]
btw there might be some grammar problems inside coz im not a English native speaker, so yah.

**Comment by JeremyZhang2002** [comment]
can someone help me with this? maybe add it to the plugin as something new?
XD

**Comment by DevLeoko** [comment]
If you want to use this plugin on a Bungeecord network you will need to put it in the plugins folder of the bungeecord server and not in each server individually

**Comment by JeremyZhang2002** [comment]
yeah i got ur point. but the thing is i need this plugin in every single servers because my anti cheat plugin can not execute commands of bungee plugins but sub-server plugins only. So i want to let my anti cheat plugin ban people automatically I have to install this plugin in every single servers.

**Comment by JeremyZhang2002** [comment]
So can u please add that auto refresh as a feature of the update of this plugin plz? XD

**Comment by DevLeoko** [comment]
Take a look at this plugin which forwards commands to the bungeecord
https://www.spigotmc.org/resources/commandforward.27580/

**Comment by JeremyZhang2002** [comment]
omg thx man!
I will try this!
XD

**Comment by JeremyZhang2002** [comment]
but wait i found another problem if i use that forward plugin.
I use pex with mysql wo sync my perms. But pex doesn't work on BC.
plus, this plugin does not support run the command as OP but only normal players, but in the same time I can not set normal players can ban ppl.
So how to solve this?

**Comment by JeremyZhang2002** [comment]
so i think the simplist solution is that add the refresh option to the plugin maybe

**Comment by Beelzebu** [comment]
You can use this plugin to sync your perms though bungee https://www.spigotmc.org/resources/bungeepexbridge.10839/
Or migrate to another perms plugin that supports bungee like [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/) or [PowerfulPerms](https://www.spigotmc.org/resources/powerfulperms.8143/), the both can migrate the data from pex.

**Comment by DevLeoko** [comment]
Indeed there should be the possibility to execute a command as console

> Example Execute as Console:
> /forward console ping
> This will select a random player to forward the connection to the bungee server, but it will be executed as bungee console there.

**Comment by JeremyZhang2002** [comment]
i know about this. But this plugin have a problem which is although they have a command to execute  as 'console' but it will only execute as a normal player randomly but not the real console. So yeah, although I use this command to run as 'console' but it will still run as the perms of normal players. I have already create a issue in the github of the writer and he repeated me he can change it to let the command /forward console to execute as OP permission.

**Comment by ItzSomebody** [comment]
Then use CommandSync

**Comment by DevLeoko** [comment]
In version 2.1.0+ the player's punishments are reloaded on join
