### ISSUE TITLE
/unban doesnt work

### ISSUE THREAD

**Issue by Snowy12** [DevLeoko/AdvancedBan#112]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single
 
_What server version (/version) are you using?_
1.9.4

_Please provide the EXACT steps required to reproduce the problem..._
1. i dont know
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any aditional information below._
Everything else seems to work perfect but when you try to unban something its just blank there is no /unban [name] also console is empty

**Comment by ItzSomebody** [comment]
Try resetting your configs

**Comment by Snowy12** [comment]
Moved to: https://github.com/DevLeoko/AdvancedBan/issues/114
