### ISSUE TITLE
Doesn't work with PermissionEx correctly

### ISSUE THREAD

**Issue by Snowy12** [DevLeoko/AdvancedBan#113]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single
 
_What server version (/version) are you using?_
1.9.4

_Please provide the EXACT steps required to reproduce the problem..._
1. idk
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any aditional information below._
If your server has permissionex /mute /unban and some other commands won't work.

**Comment by md678685** [comment]
We use PEX and AB without any problems. Did you give each group the perms they need to use AB?

**Comment by Snowy12** [comment]
@md678685 Yes, still it wont work also iven if your Opped it doesnt work. Ik this error comes from PEX because ive deleted

**Comment by Snowy12** [comment]
@md678685

**Comment by Snowy12** [comment]
@md678685 Yes, iven if i'm opped it wont let me use it also my owner rank has * permissions, but when i delete PEX from my server unban/mute works perfectly fine so the issue is with PEX do i need to do something in the config? for this to work

**Comment by Snowy12** [comment]
![unban](https://user-images.githubusercontent.com/30303557/28428762-124bab72-6d83-11e7-8a15-65cfd9c33422.PNG)
![ban](https://user-images.githubusercontent.com/30303557/28428763-124ea5f2-6d83-11e7-9f75-eba57f1cedf9.PNG)

**Comment by Beelzebu** [comment]
Try with another permission plugin like LuckPerms and see if the problem persists

**Comment by Snowy12** [comment]
Still happens. It's the PEX im pretty sure that blocks something from working correctly

**Comment by ItzSomebody** [comment]
Did you try resetting your configs?

**Comment by Beelzebu** [comment]
Can you upload your permissions to pastebin or something and send us your plugin list?

**Comment by Snowy12** [comment]
@Beelzebu you mean group permissions? and sure no problem ill send my plugins

**Comment by Snowy12** [comment]
@ItzSomebody ? what do you mean, all ive edited on the config is allow ops

**Comment by Beelzebu** [comment]
@Snowy12 yes, your group permissions

**Comment by Snowy12** [comment]
@Beelzebu 
groups:
  default:
    options:
      default: true
      prefix: '&7[&aDefault&7]'
    permissions:
    - ChestShop.shop.sell
    - ChestShop.shop.buy
    - -bukkit.command.help
    - -bukkit.command.version
    - -bukkit.command.plugins
    - bgo.listwarps
    - bgo.warpdel
    - bgo.warpset
    - bgo.warp
    - essentials.tell
    - essentials.msg
    - essentials.message
    - essentials.warp.list
    - essentials.warp
    - essentials.delhome
    - essentials.home
    - essentials.sethome
    - essentials.tpadeny
    - essentials.tpaccept
    - essentials.tpa
    - essentials.sign.use.enchant
    - essentials.sign.use.sell
    - essentials.sign.use.buy
    - essentials.sign.use.kit
    - essentials.sign.use
    - soup.use
    - souppvp.use
    - pvpsoup.use
    - essentials.tpdeny
    - essentials.kits.pvp
    - essentials.kit.pvp
    - essentials.kits
    - essentials.kit
    - modifyworld.*
  Moderator:
    options:
      prefix: '&7[&5M&ao&ed&fe&br&1a&4t&3o&dr&7]'
    permissions:
    - ChestShop.shop.sell
    - ChestShop.shop.buy
    - -bukkit.command.help
    - -bukkit.command.version
    - -bukkit.command.plugins
    - essentials.gamemode
  Admin:
    options:
      prefix: '&7[&4Admin&7]'
    permissions:
    - ChestShop.shop.sell
    - ChestShop.shop.buy
    - -bukkit.command.version
    - -bukkit.command.help
    - -bukkit.command.plugins
    - '*'
  Head-Admin:
    options:
      prefix: '&7[&aHead&f-&eAdmin&7]'
    permissions:
    - ChestShop.shop.sell
    - ChestShop.shop.buy
    - -bukkit.command.help
    - -bukkit.command.version
    - -bukkit.command.plugins
    - bgo.listgroups
    - bgo.warpdel
    - bgo.warpset
    - bgo.warp
    - essentials.*
  Co-Owner:
    options:
      prefix: '&7[&cCo&f-&dOwner&7]'
    permissions:
    - ChestShop.shop.sell
    - ChestShop.shop.buy
    - -bukkit.command.version
    - -bukkit.command.help
    - -bukkit.command.plugins
    - '*'
  Snow:
    options:
      prefix: '&7[&fSnow&7]'
    permissions:
    - ChestShop.shop.sell
    - ChestShop.shop.buy
    - -bukkit.command.version
    - -bukkit.command.help
    - -bukkit.command.plugins
    - essentials.heal
    - essentials.feed
    - essentials.warp
    - essentials.warp.list
    - essentials.fly
    - essentials.delhome
    - essentials.sethome
    - essentials.home
    - essentials.kit.snow
    - essentials.kit.sno
    - essentials.kit.starter
    - essentials.kit.pvp
    - essentials.kit.
    - essentials.kit
    - essentials.kits.
    - essentials.kits
    - essentials.warp.
    - bgo.listwarps
    - bgo.warpdel
    - bgo.warpset
    - bgo.warp
    - essentials.kits.snow
    - essentials.kits.starter
    - essentials.kits.pvp
  helper:
    options:
      prefix: '&7[&bHelper&7]'
    permissions:
    - ChestShop.shop.sell
    - ChestShop.shop.buy
    - -bukkit.command.help
    - -bukkit.command.version
    - -bukkit.command.plugins
  builder:
    options:
      prefix: '&7[&3Builder&7]'
    permissions:
    - ChestShop.shop.sell
    - ChestShop.shop.buy
    - -bukkit.command.help
    - -bukkit.command.version
    - -bukkit.command.plugins
  VIP:
    options:
      prefix: '&7[&2VIP&7]'
    permissions:
    - ChestShop.shop.sell
    - ChestShop.shop.buy
    - -bukkit.command.help
    - -bukkit.command.version
    - -bukkit.command.plugins
    - bgo.listwarps
    - bgo.warpdel
    - bgo.warp
    - bgo.warpset
    - bgo.listgwarpset
    - bgo.listgwarpsset
    - bgo.listgwarps
    - essentials.warp.list
    - essentials.warp
    - essentials.kits.starter
    - essentials.kit.starter
    - essentials.kit.pvp
    - essentials.kits.pvp
    - essentials.kit.
    - essentials.kit
    - essentials.kits
    - essentials.kits.
  Master:
    options:
      prefix: '&7[&dMaster&7]'
    permissions:
    - ChestShop.shop.sell
    - ChestShop.shop.buy
    - -bukkit.command.help
    - -bukkit.command.version
    - -bukkit.command.plugins
    - bgo.listwarps
    - bgo.warpdel
    - bgo.warpset
    - bgo.warp
    - essentials.warp.list
    - essentials.warp
    - essentials.kits.starter
    - essentials.kits.pvp
    - essentials.kits.master
    - essentials.kit.master
    - essentials.kit.vip
    - essentials.kit.starter
    - essentials.kit.pvp
    - essentials.kits.
    - essentials.kit.
    - essentials.kit
    - essentials.kits
  Rainbow:
    options:
      prefix: '&7[&dR&6a&bi&3n&5b&eo&aw&7]'
    permissions:
    - ChestShop.shop.sell
    - ChestShop.shop.buy
    - -bukkit.command.version
    - -bukkit.command.help
    - -bukkit.command.plugins
    - bgo.listgroups
    - bgo.warpset
    - bgo.warpdel
    - bgo.warp
    - essentials.warp.list
    - essentials.warp
    - essentials.fly
    - essentials.kit.rainbow
    - essentials.kit.starter
    - essentials.kit.pvp
    - essentials.kits.rainbow
    - essentials.kits.starter
    - essentials.kits.pvp
    - essentials.kits.
    - essentials.kit.
    - essentials.kits
    - essentials.kit
  Owner:
    options:
      prefix: '&7[&5O&dw&9n&ee&ar&7]'
    permissions:
    - '*'
  YouTube:
    options:
      prefix: '&7[&6YT&7]'
    permissions:
    - ChestShop.shop.sell
    - ChestShop.shop.buy
    - -bukkit.command.version
    - -bukkit.command.help
    - -bukkit.command.plugins
    - bgo.listwarps
    - bgo.warpdel
    - bgo.warpset
    - bgo.warp
    - essentials.tell
    - essentials.message
    - essentials.msg
    - essentials.tpahere
    - essentials.tpadeny
    - essentials.tpaccept
    - essentials.tpa
    - essentials.home
    - essentials.delhome
    - essentials.sethome
    - essentials.warp.list
    - essentials.warp
    - essentials.kit.youtube
    - essentials.kits.youtube
    - essentials.sign.use.kit
    - essentials.sign.use.kit.
    - essentials.sign.use.kit.youtube
    - essentials.sign.use.kit.starter
    - essentials.sign.use.kit.pvp
    - essentials.sign.use.kits
    - essentials.kits.starter
    - essentials.kits.pvp
    - essentials.kits.
    - essentials.kits
    - essentials.kit.
    - essentials.kit.starter
    - essentials.kit.pvp
    - essentials.kit
    - essentials.heal
    - essentials.feed
    - essentials.fly
  OwnerS:
    options:
      prefix: '&7[&5O&dw&9n&ee&ar&7]'
    permissions:
    - essential.sign.use.kits.pvp
    - essential.sign.use.kit.pvp
    - essential.signs.use.kit.pvp
    - essential.signs.use.kits.pvp
    - essential.signs.use.kits
    - essential.signs.use.kit
    - essential.sign.use.kits
    - essential.sign.use.kit
    - essential.sign.use
    - essential.signs.use.
    - essential.signs.use
    - essential.delhome
    - essential.home
    - essential.sethome
    - -ab.help
    - ab.help
    - ab.all.undo
    - ab.reload
    - ab.systemprefs
    - ab.history
    - ab.banlist
    - ab.check.ip
    - ab.check
    - ab.ban.undo
    - ab.ipban.exempt
    - ab.ipban.notify
    - ab.ban.ip
    - ab.ban.exempt
    - ab.ban.notify
    - ab.ban.perma
    - ab.tempban.exempt
    - ab.tempban.notify
    - ab.ban.temp
    - ab.kick.exempt
    - ab.kick.notify
    - ab.kick.use
    - ab.mute.undo
    - ab.mute.exempt
    - ab.mute.notify
    - ab.mute.perma
    - ab.tempmute.exempt
    - ab.tempmute.notify
    - ab.mute.temp
    - ab.warns.own
    - ab.warn.undo
    - ab.warn.exempt
    - ab.warn.notify
    - ab.warn.perma
    - ab.tempwarn.exempt
    - ab.tempwarn.notify
    - ab.warn.temp
    - essentials.craft
    - essentials.money
    - essentials.balance
    - essentials.message
    - essentials.tell
    - essentials.msg
    - bgo.limit5
    - bgo.limit.5
    - bgo.limit2
    - bgo.listwarps
    - bgo.listwarpt
    - bgo.warpdel
    - bgo.warpset
    - bgo.warp
    - ab.warns.other
    - ab.ban/mute.undo
    - ab.tempban/tempmute/tempwarn.notify
    - ab.tempban/tempmute/tempwarn.exempt
    - ab.ban/mute/warn.temp
    - ab.ban/mute/warn.notify
    - ab.ban/mute/warn.exempt
    - ab.ban/mute/warn.perma
    - -bukkit.command.help
    - -bukkit.command.version
    - -bukkit.command.plugins
    - essentials.jail
    - essentials.tempban
    - essentials.ban
    - essentials.fly
    - essentials.feed
    - essentials.heal
    - essentials.warp.list
    - essentials.warp
    - essentials.sign.create.free
    - essentials.sign.create.heal
    - essentials.sign.use.free
    - essentials.sign.use.heal
    - essentials.sign.use.kit
    - essentials.tpall
    - essentials.tphere
    - essentials.tp
    - essentials.kit.spawner
    - essentials.kit.master
    - essentials.kit.snow
    - essentials.kit.vip
    - essentials.kit.rainbow
    - essentials.kit.starter
    - essentials.kit.pvp
    - essentials.kits.spawner
    - essentials.kits.rainbow
    - essentials.kits.starter
    - essentials.kits.vip
    - essentials.kits.master
    - essentials.kits.snow
    - essentials.kits.pvp
    - essentials.kits.
    - essentials.kits
    - essentials.kit.
    - essentials.kit
    - ChestShop.shop.sell
    - ChestShop.shop.buy

**Comment by Snowy12** [comment]
@ItzSomebody Yes, still having issue something is blocking PEX working with AB

**Comment by Snowy12** [comment]
UPDATE
Not about permissions console cant use /unban /mute /unmute etc also its about PEX but i dont want to delete PEX because groupmanger doesnt work with 1.9 correctly

**Comment by Snowy12** [comment]
Thread moved to: https://github.com/DevLeoko/AdvancedBan/issues/114
its not about pex/groupmanager something else is blocking it.
