### ISSUE TITLE
AdvancedBan Paper Spigot

### ISSUE THREAD

**Issue by dj2553** [DevLeoko/AdvancedBan#115]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
Bungee
 
_What server version (/version) are you using?_

Paper Spigot 1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. Install the plugin
2. Look in console
3. Red Plugin name in Game.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

https://pastebin.com/G8HYghcC

_Add any additional information below._

The Plugin Works Some times which is very strange. It will work and install fine one time than the next the plugin just comes back red or disabled on restart. I have tried using different versions as well but was not able to get the plugin to work 100%. I know this plugin works fine on Spigot I think that its something to do with paper Spigot.

**Comment by DevLeoko** [comment]
what plugins are you using?

**Comment by dj2553** [comment]
Here is a list of Plugins I use on my server, I'm having problems with all types of ban plugins so I don't think its your plugin. I am using the plugin through Bungee and it seems to be working fine.

23.07 16:15:04 [Server] INFO Plugins (50): PlaceholderAPI, NametagEdit, Arconix, HideStream, StaffPlus, LibertyFTopGUI, WorldEdit, TrainingPvP, WorldBorder, MessageAnnouncer, BuycraftX, Votifier, Multiverse-Core, ProtocolLib, NoCheatPlus, GuiRedeemMCMMO, ExplodeLava, PermissionsEx, FeatherBoard, mcMMO, TNTFillFree, CS-CoreLib, Vault, GAListener, BlastJackpot, CrazyCrates, HolographicDisplays, WorldGuard, MobStacker, PlayerVaults, GenBuckets, Essentials, Citizens, CrazyAuctions, Factions, SupplyCrates, CommandNPC, EssentialsSpawn, WorldGuardExtraFlags, TitleManager, ItemHover, CrazyEnchantments, QuickSell, FBasics, EpicSpawners, DeluxeChat, XPboost, ObsidianDestroyer, CombatTagPlus, ShopGUIPlus

**Comment by DevLeoko** [comment]
AdvancedBan is not compatible with staff+

**Comment by DevLeoko** [comment]
Fixed in 2.1.0 ;)
