### ISSUE TITLE
Get all players with the same IP

### ISSUE THREAD

**Issue by pxblx** [DevLeoko/AdvancedBan#117]
You could add a command like /dupeip <player> to get a list of all the player that are joined from the same IP, very useful to detect fastly multiaccounts.

Edit: You could add too a option for hide the notify messages and make the comand silent, like /ban <player> -s.

Thanks you for the amazing resource!

**Comment by ItzSomebody** [comment]
Please use the Issue template so we don't have to ask so many questions.

Are you using BungeeCord with advancedban on individual Spigot servers without IP-fowarding? Are you using a reverse-proxy?

**Comment by md678685** [comment]
@ItzSomebody This is a feature request, not a bug report - how do those questions have anything to do with it?

**Comment by Test83318** [comment]
Also if can be posible I would add the option into the api to have them in a list (Don't mind if type Player[] or a arraylist)

**Comment by DevLeoko** [comment]
This is not in the scope of AdvancedBan as it is not directly related to punishing players. Use a separate plugin for dup. IP detection (there are a lot)
