### ISSUE TITLE
Remove punishment when player is banned/ or it's expired

### ISSUE THREAD

**Issue by jQuery0** [DevLeoko/AdvancedBan#121]
Title says enough. Remove a punishment when a player is either unbanned or the punishment is expired.

**Comment by md678685** [comment]
That defeats the point of having a permanent record of punishments, though.

**Comment by DevLeoko** [comment]
There are two tables (if you use MySQL) or sections in the data file.
The first one holds all active punishments, so the expired ones will be deleted there and the second one is the history so they stay there. I don't get the point about deleting them also in the history?
