### ISSUE TITLE
Banning Problem

### ISSUE THREAD

**Issue by TheRazerEyes** [DevLeoko/AdvancedBan#122]
I have the newest AdvancedBan, Yet when i Ban someone it works fine but when i Unban them they arnt unbanned.. it is very weird.. How to fix this?

**Comment by DevLeoko** [comment]
Please use this Issue-Template: https://github.com/DevLeoko/AdvancedBan/blob/master/ISSUE_TEMPLATE.md

**Comment by TheRazerEyes** [comment]
Version 2.06

Single Server (Spigot)

1.8

/ban (player name)

/unban (player name)

and it doesn't unban them

No errors shown

**Comment by DevLeoko** [comment]
Try to delete the plugin's folder and restart the server

**Comment by DevLeoko** [comment]
Closed due to no response
