### ISSUE TITLE
AdvancedBan Not Working

### ISSUE THREAD

**Issue by Vision-eVG** [DevLeoko/AdvancedBan#123]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 PaperSpigot
 
_What server version (/version) are you using?_
PaperSpigot-1169 (MC 1.12)

This may be the reason why it isn't working. I just came here for proper clarification or if it was a plugin interfering.

_Please provide the EXACT steps required to reproduce the problem..._
1. Install Plugin
2. Nice big red error message in console
3. In /pl name is red

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/t6Yr4gdc

_Add any additional information below._
Plugins: [13:37:02] [Server thread/INFO]: Plugins (65): AdvancedBan, AsyncWorldEdit, AsyncWorldEditInjector, AuctionHouse, BetterEnderChest, BuycraftX, ChatItem, Citizens, ClearChat, ClearLag, ClientPermissions, CombatLogX, CompatNoCheatPlus, CoreProtect, CrazyCrates, CustomRecipes, DeathMessagesPrime, DropEdit, EditableSign, EnchantLimit, EnjinMinecraftPlugin, EpicRename, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, FactionChat, FactionFly, Factions, FactionsTop, HealthBar, HolographicDisplays, HyperDiscord, KoTH, LeaderHeads, LimitCrafting, MassiveCore, mcMMO, MessageAnnouncer, MobHealth, Multiverse-Core, NametagEdit, NoCheatPlus, ObsidianDestroyer, OldCombatMechanics, OpenInv, Orebfuscator4, PermissionsEx, PlaceholderAPI, PlayerHeads, PlugMan, ProtocolLib, ServerListPlus, SilkSpawners, SilkSpawnersShopAddon, SuperVanish, TitleManager, TNTFillFree, Vault, ViaBackwards, ViaVersion, Website, WorldEdit, WorldGuard

**Comment by DevLeoko** [comment]
Why did you close the issue? is it solved?

**Comment by supertassu** [comment]
@DevLeoko Most likely forgot to configure MySQL.

**Comment by DevLeoko** [comment]
That won't cause the plugin to disable itself. If it's not able to establish a connection to the MySQL-Server it will just switch back to File-System

**Comment by supertassu** [comment]
@DevLeoko For me it disables and turns red.

**Comment by Vision-eVG** [comment]
I did a complete stop and start and it fixed it. I forget my restart doesn't stop the server completely.
