### ISSUE TITLE
Ban issue

### ISSUE THREAD

**Issue by CDAGaming** [DevLeoko/AdvancedBan#126]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Latest, Compiled from Source
 
_What kind of server do you have (`Bungeecord/single server`)?_
 PaperSpigot 1.12.1
 
_What server version (/version) are you using?_
Answered Above ^^

_Please provide the EXACT steps required to reproduce the problem..._
1. Start Server
2. Use any ban command
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/AHWhmzVS

_Add any additional information below._

**Comment by ItzSomebody** [comment]
Looks like a disaster with MySQL

**Comment by DevLeoko** [comment]
The Dev Branch is currently not stable if you want to compile the latest stable version use the Master-Branch but thanks for posting that error here so I can fix it as I've not seen it while testing
