### ISSUE TITLE
Banned or punished player's Nickname is in Lowercase

### ISSUE THREAD

**Issue by VideoklipBG** [DevLeoko/AdvancedBan#128]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
"**AdvancedBan 2.0.6**"
 
_What kind of server do you have (`Bungeecord/single server`)?_
 **BungeeCord with couple Spigot Lobbies**
 
_What server version (/version) are you using?_
**Spigot R0.1 Snapshot** / **MC 1.8.8**

_Please provide the EXACT steps required to reproduce the problem..._
1. **Install Advanced Ban**;
2. **No need to configure any messages / files (If you do not want)**;
3. **Join with couple accounts in your Server (In this case - BungeeCord)**;
4. **The Server can be in Online / Offline Mode**;
5. **Set the right permissions for You (The Admin Account) and punish / ban / tempban someone (Other accout)**;
6. **In the chat (the broadcast) will say the Punishment / Ban message, but the Player's Nickname will be in Lowercase (Small letters) no matter if the Player's Account Nickname contains uppercase letters**;

**Example**: "_pLaYeR_01_" > "_player_01_"

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
**_N/A_**

_Add any additional information below._
**_N/A_**

**Comment by ItzSomebody** [comment]
Why is this an error?

As far as I can see from your issue report, you haven't said what's wrong other than a case change in the nickname. Does this affect the ban?

**Comment by VideoklipBG** [comment]
It don't affect the player's ban and mute status, etc. But in the chat it displays wrongly the Nickname (Uppercase and lowercase letters), it's very confusing sometimes when someone is checking a lot of players for curiosity or jsut for info who is banned / muted, etc.

**Comment by DevLeoko** [comment]
This is more like a feature request

**Comment by DevLeoko** [comment]
Has been added in #171 by @Beelzebu and @TreyRuffy
You can download the latest build here: http://v.skamps.eu/jenkins/job/AdvancedBanV2/26/
This update will be released in a few weeks on spigot.

Would be great if you could give us some feedback if everything works :)
