### ISSUE TITLE
UTF-8 support for bungeecord

### ISSUE THREAD

**Issue by Twonox** [DevLeoko/AdvancedBan#13]
There is no support for special characters in Bungeecord ?

**Comment by DevLeoko** [comment]
It should be what is not working?

**Comment by Twonox** [comment]
If I use AdvancedBan with BungeeCord's plugins folder:
http://www.noelshack.com/2016-39-1475262527-2016-09-30-210627.png
http://www.noelshack.com/2016-39-1475262529-2016-09-30-210706.png

But if I use it with Spigot's plugins folder, there is no this problem.

**Comment by DevLeoko** [comment]
You will have to use some kind of \codes like
\xbb for »

**Comment by Twonox** [comment]
I see, you mean UNICODE, i will test thanks

**Comment by Twonox** [comment]
It works, thanks :)
