### ISSUE TITLE
3 Unordered Files(In Incorrect Folder) [Development Branch]

### ISSUE THREAD

**Issue by CDAGaming** [DevLeoko/AdvancedBan#131]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.0 (Development Branch)
 
_What kind of server do you have (`Bungeecord/single server`)?_
 PaperSpigot 1.12.1
 
_What server version (/version) are you using?_
Answered Above

_Please provide the EXACT steps required to reproduce the problem..._
N/A

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
N/A

_Add any additional information below._
"AdvancedBan\data\storage.log"
"AdvancedBan\data\storage.properties"
"AdvancedBan\data\storage.script"

The Files (With those exact names above) Appear in plugins folder and Not in their Proper directory AdvancedBan/Data

**Comment by CDAGaming** [comment]
Looking more closely, it seems these files appearing in plugins are possible duplicate files

**Comment by DevLeoko** [comment]
Is it possible that you copied them by accident there as the Path of the Database is define really clearly?

**Comment by CDAGaming** [comment]
I didn't copy those files at all over. If you wish I can post a screenshot of the duplicates and the actual files

**Comment by DevLeoko** [comment]
Okey found the bug :) It was because Linux handles the Files different than Windows and I only tested it on Windows ;) Will be fixed in the next build

**Comment by CDAGaming** [comment]
Thanks so much :)
