### ISSUE TITLE
Ban's

### ISSUE THREAD

**Issue by TheRazerEyes** [DevLeoko/AdvancedBan#135]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.2
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single Server 1.8 Factions
 
_What server version (/version) are you using?_
Craftbukkit 1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. /ban or /banip (name)
2./unban (name) /unbanip (name)
3. Not unbanned...

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

In the log it says they are unbanned and they try login it says they are still banned.. then i try unban again it says they are not banned...

_Add any additional information below._

Banning/IP banning people = Cannot unban them..

**Comment by ItzSomebody** [comment]
Craftbukkit or Spigot?

**Comment by TheRazerEyes** [comment]
Spigot

**Comment by ItzSomebody** [comment]
Might be an issue with the local SQL storage option.

Are your UUID fetcher settings correct?

**Comment by TheRazerEyes** [comment]
Yes

**Comment by DevLeoko** [comment]
are you using MySQL? maybe just send a screenshot of /advancedban

**Comment by TheRazerEyes** [comment]
I believe so? not sure. I checked data.yml and its not on there its gone
since i unbanned them yet when they try join their still banned

**Comment by ItzSomebody** [comment]
The latest versions of AdvancedBan no longer use data.yml

**Comment by ItzSomebody** [comment]
@DevLeoko I have successfully reproduced the problem. When you put AdvancedBans on Spigot servers, it isn't overriding the default /ban

**Comment by TheRazerEyes** [comment]
How do I fix it?

**Comment by TheRazerEyes** [comment]
I also just tried to temp mute someone  and they can still talk?

**Comment by DevLeoko** [comment]
For a fee of 5USD, you can convert the data.yml to the now used HSQLDB.
The muting issue is most likely caused by your chat plugin

**Comment by TheRazerEyes** [comment]
Oh so i have to pay 5$ to get a free plugin to work?

**Comment by DevLeoko** [comment]
Ofc not you understood that wrong :D
The plugin should work by default, the muting thing is most likely just caused by an incompatible chat plugin. The fee of 5$ is only to convert your old data to the new one but the plugin should still work without that

**Comment by TheRazerEyes** [comment]
Well the new one doesn't work. I ban people unban still doesn't work even
know i updated to current version. SO basically to be able to ban and unban
people using the Advanced"BAN" plugin i need to pay 5$ :p?

**Comment by DevLeoko** [comment]
Did you read my message? 
**"The plugin should work by default"**
**"The fee of 5$ is only to convert your old data to the new one but the plugin should still work without that"**

Try to delete the plugin+plugin folder and reinstall it (maybe backup the plugin folder if you want to keep any of the configs)

**Comment by TheRazerEyes** [comment]
Okay Ive redone it and it looks much different now so I'm guessing it works
cheers, Also just wondering - Is there a way to make it broadcast like

[ServerName] (player name) Has been banned for (Reason) by (StaffMember) ?

**Comment by DevLeoko** [comment]
Ya read the plugin page for more details about the individual features
