### ISSUE TITLE
PunishmentEvent cannot be called Asynchronously

### ISSUE THREAD

**Issue by ManyPandas** [DevLeoko/AdvancedBan#139]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Latest version
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bukkit
 
_What server version (/version) are you using?_
1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
I create a punishment object in the code. Then when I call the create(); method on the object it throws
the error below.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here.
https://pastebin.com/8GR8bDX3_

_Add any additional information below._

**Comment by Beelzebu** [comment]
Seems that you're calling this from an async task and the events can't be called async https://www.spigotmc.org/threads/call-sync-from-async.195967/#post-2042652

**Comment by DevLeoko** [comment]
Can this be closed/Is the Issue solved?

**Comment by ManyPandas** [comment]
Yes
