### ISSUE TITLE
/tempmute not muting, but muted message is still displayed.

### ISSUE THREAD

**Issue by MithrandirCraft** [DevLeoko/AdvancedBan#141]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungee (8 spigot servers)
 
_What server version (/version) are you using?_
mc 1.12.1

_Please provide the EXACT steps required to reproduce the problem..._
1. /tempmute <player> 3h <reason>
2. Check applied player.
3. He/She can still speak, but gets a message indicating he/she is muted.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No errors. It just doesn't work.

_Add any additional information below._
I'm also using ChatControl. Maybe it conflicts somehow.
Any further info required, please ask.

**Comment by DevLeoko** [comment]
We only provide support for the current version, please update.
