### ISSUE TITLE
Error with SQL when check username

### ISSUE THREAD

**Issue by thunderlight411** [DevLeoko/AdvancedBan#143]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.3
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord

_What server version (/version) are you using?_
1.12.1

_Please provide the EXACT steps required to reproduce the problem..._
1. check <username>
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/4V4Gq61d

_Add any additional information below._
when checking history of a user a SQL messages is accrued and there is no output of any history.
When checking the SQL database true advancedban-web-addon or making a select query in PHPMyAdmin there is a nice output available

**Comment by DevLeoko** [comment]
I'll check that issue asap, as it seems to be a problem with the code

**Comment by DevLeoko** [comment]
This is fixed in the newest released version
