### ISSUE TITLE
AdvancedBan no permissions after adding ab.all node

### ISSUE THREAD

**Issue by Adam-Morris** [DevLeoko/AdvancedBan#144]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.1.3-RELEASE
 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord
 
_What server version (/version) are you using?_
PaperSpigot 1.12-R0.1-SNAPSHOT on BungeeCord 1.12

_Please provide the EXACT steps required to reproduce the problem..._
1. Install LuckPerms on BungeeCord server
2. Install AdvancedBan on BungeeCord server
3. Setup Owner rank on LuckPerms
4. Set EnableAllPermissionNodes to true in AdvancedBan config
5. Give Owner rank ab.all
6. Try the command /ban
7. Get an error: "You don't have perms for that"... :(

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any additional information below._
Using LuckPerms.

**Comment by DevLeoko** [comment]
Do the other permissions work? like ab.kick.use

**Comment by Adam-Morris** [comment]
I figured it out, I had not installed LuckPerms-Bungee on my Bungeecord server. After installing that it worked.
