### ISSUE TITLE
UnbanIP

### ISSUE THREAD

**Issue by Louisgrxxn** [DevLeoko/AdvancedBan#145]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 1.8.9
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single server
 
_What server version (/version) are you using?_
2.1.3-RELEASE

_Please provide the EXACT steps required to reproduce the problem..._
1. Ipbanned my alt (for testing)
2./unbanip or /unpunish or /unban isn't unbanning my main or my alt.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
None.

_Add any additional information below._

**Comment by ItzSomebody** [comment]
What data storage type are you using?

**Comment by DevLeoko** [comment]
@Louisgrxxn if you don't respond within a week this issue will be closed
