### ISSUE TITLE
Custom ports (BanPanel)

### ISSUE THREAD

**Issue by SteveTheEngineer** [DevLeoko/AdvancedBan#146]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.3-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
git-Paper-1204 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. Please, add the custom port function to WebPanel (banpanel.eu)

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
-

_Add any additional information below._
-

**Comment by DevLeoko** [comment]
Have you tried to append the port with a ":" at the end of the IP Adress?
Like 127.0.0.1:3306

**Comment by TSEngineer** [comment]
The MySQL-Data are not valid! 
Failed: Unknown MySQL server host 'run51xh5wx.playvdss.com:3003' (74)

**Comment by TSEngineer** [comment]
The MySQL-Data are not valid!
Failed: Unknown MySQL server host 'run51xh5wx.playvdss.com:3003' (74)

2017-10-07 14:54 GMT+03:00 DevLeoko <notifications@github.com>:

**Comment by DevLeoko** [comment]
Okey will be added

**Comment by DevLeoko** [comment]
The official ban panel has been discontinued. The standalone version supports this feature tho.
