### ISSUE TITLE
Kick null player 

### ISSUE THREAD

**Issue by mariolars** [DevLeoko/AdvancedBan#147]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
 2.1.3-RELEASE
_What kind of server do you have (`Bungeecord/single server`)?_
 Single
 
_What server version (/version) are you using?_

git-Paper-1234

_Please provide the EXACT steps required to reproduce the problem..._
1. Plugin spam command to kick
 
_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

https://pastebin.com/xg0QeP7Z
_Add any additional information below._

Check if it's not null

**Comment by DevLeoko** [comment]
There is already a check if the player is online, there is nothing more I can do if you spam the command
