### ISSUE TITLE
Messages.yml Issue - What am I doing wrong?

### ISSUE THREAD

**Issue by geo168** [DevLeoko/AdvancedBan#148]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
Advanced Ban 2.1.3
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
Waterfall Proxy aka Bungeecord Fork 

_What server version (/version) are you using?_

1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. Use this messages.yml https://pastebin.com/k2p7ZF8m
2. Start Waterfall
3. Done

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

https://pastebin.com/H4Y69G5m

_Add any additional information below._

Checked the file through http://www.freecodeformat.com/yaml-validator.php and reports: "Valid YAML"

**Comment by DevLeoko** [comment]
The issue could also be in your Layout File try to check it with the online validator

**Comment by geo168** [comment]
The issue was in messages.yml. I had put double quotation marks in a string. (- "&c&l#%ID% &8> &7&o%REASON%""). Issue fixed. Posting this here for reference.
