### ISSUE TITLE
IP Ban Problem

### ISSUE THREAD

**Issue by lucas2107** [DevLeoko/AdvancedBan#149]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.3
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single Server
 
_What server version (/version) are you using?_
This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. IP ban
2. Player UUID/name not banned. Only IP
3. Can't Unban IP :/

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
/

_Add any additional information below._

When you use /ipban command, player can connect back to server with the same name/UUID.

**Comment by DevLeoko** [comment]
How do you try to unban the IP?

**Comment by lucas2107** [comment]
With /unban & /unbanip

**Comment by DevLeoko** [comment]
Could you give us a feedback if this build fixed your issue?
http://v.skamps.eu/jenkins/job/AdvancedBanV2/19/
If you still use the plugin ;)

**Comment by lucas2107** [comment]
Hi,

I'm going to check at the next restart if it's working ^^

Best regards,

**Comment by lucas2107** [comment]
Working

**Comment by discordappadmin** [comment]
No. It /unban or /unbanip don't work
It says player isn't banned.
Don't spread false commands.

**Comment by Hissam1048v** [comment]
Same issue

**Comment by KingDeltaOne** [comment]
no fix ?
