### ISSUE TITLE
MySQL disconnection

### ISSUE THREAD

**Issue by Twonox** [DevLeoko/AdvancedBan#15]
Some times there is disconnection with MySQL and I can't ban/tempban
http://hastebin.com/umeyetudog.vbs

Idk why...

**Comment by DevLeoko** [comment]
If there is any problem with the MySQL-Server, AdvancedBan tries to reconnect 10 times if this is not successful you will get this message and will have to reload the server.

**Comment by Twonox** [comment]
But others plugins doesn't have any problem with MySQL connection. Only AdvancedBan, a few hours later (it's the alone BungeeCord plugins who use MySQL)
Before I use it in BungeeCord, it was connected to MySQL and I had no any problem with MySQL, only after using BungeeCord with the version 2. (it was version 1 before using bungeecord)

So, the problem come of the version 2 or come of bungeecord.

**Comment by md678685** [comment]
I've seen this happen occasionally with version 2.

**Comment by Twonox** [comment]
There is no longer this problem. I will report it again if it's reproduced.

**Comment by Twonox** [comment]
It happened again :/
http://hastebin.com/tefucoqiro.vbs

The cause can't be my sql server because  when there is sql problem the server shut down, but now the server does not shut down.

You couldn't add a re-connection without rebooting ?

**Comment by DevLeoko** [comment]
How I already said:
If there is any problem with the MySQL-Server, AdvancedBan tries to reconnect 10 times if this is not successful you will get this message and will have to reload the server.
So your MySQL-Server has to have some problems but there will be an even more advanced reconnect system in one of the next updates.
