### ISSUE TITLE
This Isn't letting me Unban A Player

### ISSUE THREAD

**Issue by Techno3600** [DevLeoko/AdvancedBan#152]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
 2.1.3
_What kind of server do you have (`Bungeecord/single server`)?_
 
 Single server
_What server version (/version) are you using?_

CraftBukkit version git-Spigot-7129aeb-c15d869 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
_Please provide the EXACT steps required to reproduce the problem..._
1. Ban a player (/ban)
2. Try to unban the same player 
3. It doesn't work

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
THIS IS /BANLIST
`18.11 23:26:29 [Server] INFO 99blackdiamond | permanent | Techno3600
18.11 23:26:29 [Server] INFO Warn > Generald Rudness / Too Easily triggered
18.11 23:26:29 [Server] INFO Page 1 of 1 | Active bans: 1`
THIS IS /UNBAN (using the same caps and what-not of the username from the banlist)
`18.11 23:27:06 [Server] INFO AdvancedBan » 99blackdiamond is not banned!`
_Add any additional information below._
I need help.

**Comment by Techno3600** [comment]
18.11 23:27:55 [Server] INFO -===== AdvancedBan v2 =====- 
18.11 23:27:55 [Server] INFO Dev • Leoko
18.11 23:27:55 [Server] INFO Status • Stable
18.11 23:27:55 [Server] INFO Version • 2.1.3-RELEASE
18.11 23:27:55 [Server] INFO License • Public
18.11 23:27:55 [Server] INFO Storage • HSQLDB (local)
18.11 23:27:55 [Server] INFO Server • Spigot/Bukkit
18.11 23:27:55 [Server] INFO UUID-Mode • INTERN
18.11 23:27:55 [Server] INFO Prefix • AdvancedBan »
18.11 23:27:55 [Server] INFO -=========================-

**Comment by DevLeoko** [comment]
Could you check if the latest build has fixed this issue?
http://v.skamps.eu/jenkins/job/AdvancedBanV2/19/

**Comment by DevLeoko** [comment]
This is fixed in the newest released version
