### ISSUE TITLE
Variable Name Capitalization

### ISSUE THREAD

**Issue by MsArtix** [DevLeoko/AdvancedBan#153]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.3
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single Server
 
_What server version (/version) are you using?_
1.12.2

_Please provide the EXACT steps required to reproduce the problem..._
1. Ban/mute/kick/warn someone and their name is in all lowercase and not their actual name. this is for the %NAME% variable, while the %OPERATOR% variable spells the persons name with caps in the right place. (I know this isn't a huge issue but it seriously bugs me)

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No errors

**Comment by DevLeoko** [comment]
Same as #128
