### ISSUE TITLE
Feature Request Alt Checking

### ISSUE THREAD

**Issue by MsArtix** [DevLeoko/AdvancedBan#154]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.4
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single Server
 
_What server version (/version) are you using?_
1.12.2

Feature Request: 
So what would happen is when a player joins it checks their IP then runs it throguh advanced ban to see if other players have logged in with the same IP and if they have then it displays a configurable message in chat. Then if there are no other accounts associated with that IP it does nothing (or make it so another set of commands can run and people can leave it empty for nothing to happen). Variables for what is displayed could be the IP the player joined, the name of the player who joined. the other accounts that player has joined with and then show the account status like red=banned gray=not banned but offline and green=online. This is very much a feature that should be implemented because it is ban related. Some servers do not allow alt accounts which means it is easier for them to see and one less plugin for people to have to install on their server. Thanks for reading. Hope to see this added.

**Comment by DevLeoko** [comment]
Sorry but an alt-check would be more something for an extra plugin or maybe an addon but I don't think that such a feature belongs in the core of advancedban
