### ISSUE TITLE
MySQL config settings?

### ISSUE THREAD

**Issue by colinrgodsey** [DevLeoko/AdvancedBan#155]
I could be totally blanking here, but where do you configure the MySQL DB/user/pass? I see no reference in the config file or docs. And when i looked through the code, i saw both: hardcoded db/user/pass, and reference to some YML keys i havent seen. This seems like an amazingly crucial piece of documentation, as mysql is necessary for cross-server support (which is why i liked this one).

thanks!

**Comment by DevLeoko** [comment]
Enable the MySQL-Setting in the config.yml and restart the server, then there will appear a MySQL.yml file in the advancedban folder where you can specify your settings

**Comment by colinrgodsey** [comment]
ah, that was the issue. didnt know it waited to make the mysql config until after it was enabled in the main config. 👍
