### ISSUE TITLE
mysql Communications link failure

### ISSUE THREAD

**Issue by prozhong** [DevLeoko/AdvancedBan#156]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.3-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
Build #1283
https://ci.md-5.net/job/BungeeCord/1283/

_Please provide the EXACT steps required to reproduce the problem..._
1.There is 0 player online, and there has no player joining for 8 + hours
2.One player join the network
3.Then the error shows

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/v0Y7zatU

_Add any additional information below._
Its on my test network, 
I know it won't reproduce on most public network, 
because it is not likely 0 player join for 8+ hours
and this can be solved by config mysql timeout to more than 8 hour

But could you please fix this? Not all plugins using mysql will throw this kind error after idle 8+ hour

**Comment by DevLeoko** [comment]
This should already work fine as the MySQL-Connection is advised to reconnect itself automatically after the default timeout. Also, I have not been able the reproduce this error nor have I ever heard that someone has a similar problem. So I assume this has something to do with your MySQL-Server.
