### ISSUE TITLE
Random Error?

### ISSUE THREAD

**Issue by lucas2107** [DevLeoko/AdvancedBan#157]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
AdvancedBan v2.1.4-SNAPSHOT
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
Single Server
 
_What server version (/version) are you using?_

PaperSpigot 1.8.8

_Please provide the EXACT steps required to reproduce the problem..._

Unknown, maybe at the end of a punishment.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

https://hastebin.com/ezaxerusan.vbs

_Add any additional information below._

N/A

**Comment by DevLeoko** [comment]
Sorry but I have not been able to reproduce this error
