### ISSUE TITLE
Advanched Ban Panel 

### ISSUE THREAD

**Issue by Motovoh** [DevLeoko/AdvancedBan#158]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
Latest version,i installed newest version today.
 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BuungeCord
 
_What server version (/version) are you using?_
git-Spigot-550ebac-7019900 (MC:1.8)

_Please provide the EXACT steps required to reproduce the problem..._
1.Hello i created my web banel for banlist,but when i open it its need like 3 minutes to load,when i search players its just said 508 GateWay not found..

**Comment by DevLeoko** [comment]
Could you please paste the link to your webpanel?

**Comment by Motovoh** [comment]
www.hogwarts2.banpanel.eu

**Comment by Motovoh** [comment]
Loading like 3-4 minutes then it just crash
![t](https://user-images.githubusercontent.com/34837966/34363323-5278b562-ea7b-11e7-8fb8-2ebc4c92b555.PNG)

**Comment by DevLeoko** [comment]
This seems to be caused by your MySQL-Server as it's very slow

**Comment by Motovoh** [comment]
I'm using db4free net and theye have 200 mb space,is there better MySQL
hosting?

27.12.2017. 16.15, "DevLeoko" <notifications@github.com> је написао/ла:

**Comment by DevLeoko** [comment]
If you want a stable and fast MySQL I can only recommend using a paid hoster
