### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by Eloslav** [DevLeoko/AdvancedBan#159]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.3-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
Bungeecord 
 
_What server version (/version) are you using?_
CraftBukkit version git-Spigot-549c1fa-45c8386 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. Install AdvancedBan on all servers and on bungeecord proxy
2. Install LuckPerms on all servers
3. Give admin permission ab.* or ab.all or ab.kick.use
4. Get "You dont have perms for that"

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any additional information below._

**Comment by DevLeoko** [comment]
There are 3 Issues:
1. You are not using the newest version (2.1.4-RELEASE)
2. You should only install AdvanedBan on the BungeeCord and not on the single servers
3. You will need to enter the perms in the config.yml of the BungeeServer

**Comment by Eloslav** [comment]
Thanks a lot! It worked!

**Comment by Eloslav** [comment]
Ok, sorry about my previous message, I am trying to give perms to my staff but it doesnt work.

**Comment by Eloslav** [comment]
I have ab.all in config and also in Luckperms database.

**Comment by DevLeoko** [comment]
did you activate ab.all in the config.yml of AdvancedBan?

**Comment by Eloslav** [comment]
If you mean this one then yes.
EnableAllPermissionNodes: true

**Comment by DevLeoko** [comment]
Please paste the config.yml of bungeecord

**Comment by Eloslav** [comment]
ip_forward: true
network_compression_threshold: 256
stats: dc16d4b7-00c1-4545-8e02-ce19a7658bbd
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - ab.kick.notify
  - ab.ban.notify
  - ab.mute.notify
  - ab.tempban.notify
  - ab.ipban.notify
  - ab.warn.notify
  - ab.banlist.notify
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - ab.all
  staff:
  - ab.all
groups:
  El_Juan:
  - admin
  Krakono:
  - admin
  Ixy:
  - staff
  Troysl:
  - staff
  gery:
  - staff
  rumcajs127:
  - staff
  giles08:
  - staff
  DAIU:
  - admin
  Corpus:
  - staff
  corpus:
  - staff
servers:
  lobby:
    motd: '&1Lobby'
    address: 80.79.16.48:25575
    restricted: false
  survival:
    motd: '&1Survival'
    address: 80.79.16.48:25585
    restricted: false
timeout: 30000
listeners:
- query_port: 25565
  motd: '"&fMINESIS.cz &e- &aSurvival\n&f?&2Economy  &f?&2LagFree &f?&2CZ/SK/EN"'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    80.79.16.48:25575: lobby
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: false
  host: 80.79.16.48:25565
  max_players: 100
  tab_size: 60
  force_default_server: false
prevent_proxy_connections: false
player_limit: 60
online_mode: false
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000

**Comment by Eloslav** [comment]
`ip_forward: true
network_compression_threshold: 256
stats: dc16d4b7-00c1-4545-8e02-ce19a7658bbd
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - ab.kick.notify
  - ab.ban.notify
  - ab.mute.notify
  - ab.tempban.notify
  - ab.ipban.notify
  - ab.warn.notify
  - ab.banlist.notify
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - ab.all
  staff:
  - ab.all
groups:
  El_Juan:
  - admin
  Krakono:
  - admin
  Ixy:
  - staff
  Troysl:
  - staff
  gery:
  - staff
  rumcajs127:
  - staff
  giles08:
  - staff
  DAIU:
  - admin
  Corpus:
  - staff
  corpus:
  - staff
servers:
  lobby:
    motd: '&1Lobby'
    address: 80.79.16.48:25575
    restricted: false
  survival:
    motd: '&1Survival'
    address: 80.79.16.48:25585
    restricted: false
timeout: 30000
listeners:
- query_port: 25565
  motd: '"&fMINESIS.cz &e- &aSurvival\n&f?&2Economy  &f?&2LagFree &f?&2CZ/SK/EN"'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    80.79.16.48:25575: lobby
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: false
  host: 80.79.16.48:25565
  max_players: 100
  tab_size: 60
  force_default_server: false
prevent_proxy_connections: false
player_limit: 60
online_mode: false
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
`

**Comment by Eloslav** [comment]
`ip_forward: true
network_compression_threshold: 256
stats: dc16d4b7-00c1-4545-8e02-ce19a7658bbd
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - ab.kick.notify
  - ab.ban.notify
  - ab.mute.notify
  - ab.tempban.notify
  - ab.ipban.notify
  - ab.warn.notify
  - ab.banlist.notify
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - ab.all
  staff:
  - ab.all
groups:
  El_Juan:
  - admin
  Krakono:
  - admin
  Ixy:
  - staff
  Troysl:
  - staff
  gery:
  - staff
  rumcajs127:
  - staff
  giles08:
  - staff
  DAIU:
  - admin
  Corpus:
  - staff
  corpus:
  - staff
servers:
  lobby:
    motd: '&1Lobby'
    address: 80.79.16.48:25575
    restricted: false
  survival:
    motd: '&1Survival'
    address: 80.79.16.48:25585
    restricted: false
timeout: 30000
listeners:
- query_port: 25565
  motd: '"&fMINESIS.cz &e- &aSurvival\n&f?&2Economy  &f?&2LagFree &f?&2CZ/SK/EN"'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    80.79.16.48:25575: lobby
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: false
  host: 80.79.16.48:25565
  max_players: 100
  tab_size: 60
  force_default_server: false
prevent_proxy_connections: false
player_limit: 60
online_mode: false
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
`

**Comment by DevLeoko** [comment]
Well, that should work fine, if you have restarted the bungeecord server there is no issue I could think of.

**Comment by Eloslav** [comment]
So where is the problem? My staff cannot use bansystem. :(

**Comment by Eloslav** [comment]
BTW happy new year :D

**Comment by DevLeoko** [comment]
Where is AdvancedBan installed? On which servers?

**Comment by Eloslav** [comment]
Only on Bungee as you said

**Comment by DevLeoko** [comment]
Please post a screenshot of the output of:
/advancedban
and
/perms

**Comment by Eloslav** [comment]
![image](https://user-images.githubusercontent.com/34945902/34652775-0bde77b0-f3e3-11e7-8db1-f9c758654c5c.png)

**Comment by Eloslav** [comment]
But now my staff can use it but players cannot see output

**Comment by Eloslav** [comment]
Can you help with that?

**Comment by DevLeoko** [comment]
Sorry no, as the issue seems to be related to LuckPerms. We do not provide any support if there are any third party plugins involved. As it works fine without them
