### ISSUE TITLE
/mute priority

### ISSUE THREAD

**Issue by Twonox** [DevLeoko/AdvancedBan#16]
I use an other plugins for mute, but I can't use /mute & /unmute commands because Ab have the priority, even with commands.yml. Could you add option to disable the mute system of Ab please ?
(I use Ab with bungeecord)

**Comment by Twonox** [comment]
> Ab have the priority, event with commands.yml

**Comment by DevLeoko** [comment]
There will be an option in a future version of advancedban to disable mute&warn commands

**Comment by Twonox** [comment]
Thanks you !! :)

**Comment by Twonox** [comment]
There is no longer need to add this option because there is a way to disable commands of bungee plugins in config.yml.
disabled_commands:
- mute
- unmute
