### ISSUE TITLE
API problem

### ISSUE THREAD

**Issue by ryandw11** [DevLeoko/AdvancedBan#161]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_ 2.1.4 Release
 
 
_What kind of server do you have (`Bungeecord/single server`)?_ Single Server
 
 
_What server version (/version) are you using?_  CraftBukkit version git-Spigot-549c1fa-45c8386 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

When I try using the api to tell if a player is muted or not it always returns false. Here is my code:

```java
	@EventHandler
	public void jsonChat(JsonChatEvent e){
		Player p = e.getPlayer();
		Bukkit.getLogger().info("Test == " + (PunishmentManager.get().getMute(p.getUniqueId().toString())));
		if(PunishmentManager.get().isMuted(p.getUniqueId().toString())){
			
			e.setCancelled(true);
		}
	}
```
The log always return null. So it prints out test == null.

**Comment by DevLeoko** [comment]
My first guess would be that `p.getUniqueId().toString()` returns either a wrong uuid or a differently formatted one.
The simples solution would be to use the AdvancedBan UUIDManager:
`UUIDManager.get().getUUID(String name);`
Also to simplify your code, there is also a `isMuted(String uuid)` method

**Comment by ryandw11** [comment]
Thank you! I managed to get it work now.
