### ISSUE TITLE
Problem with MySQL ?

### ISSUE THREAD

**Issue by EncryptSL** [DevLeoko/AdvancedBan#162]
AdvancedBan 2.1.4
 
 Spigot Latest - Build

When the player joins, so it throws out the error. But not always.

https://pastebin.com/b1k4gNRC

Server is for Warez Players and version of server is 1.12.2.
Plugin is connected on MySQL Database server.

**Comment by DevLeoko** [comment]
There seems to be a problem with your MySQL-Server, please enable the debug in the config.yml and post the debug log as soon as the error occurs again

**Comment by EncryptSL** [comment]
Debug: Query: 
SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?
Debug: An error has ocurred with the database, the error code is: '0'
The state of the sql is: 08S01
Error message: Communications link failure

The last packet successfully received from the server was 114,746 milliseconds ago.  The last packet sent successfully to the server was 8 milliseconds ago.

**Comment by DevLeoko** [comment]
Seems like your MySQL Server stopped responding
