### ISSUE TITLE
Players can be banned again when already banned

### ISSUE THREAD

**Issue by itsTyrion** [DevLeoko/AdvancedBan#163]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.1.4 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
Spigot 1.8.8, and up to date Bungeecord

_Please provide the EXACT steps required to reproduce the problem..._
1. ban a player
2. type the ban command a 2nd time
3. it needs to be typed 2 times to unban him

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any additional information below._
We use a silent anticheat plugin, or, to be more accurate: NoCheatPlus set to not cancel actions. When i.e. a hacker uses Vanilla Fly to Fly to mid, he already has such a high violation level, that he will get banned 3 to 5 times. I tested it with friends, 100% reproducable. I'll attach a screenshot where I typed "banlist" in the console: 
![advancedban bug](https://user-images.githubusercontent.com/17730120/34808592-1e5b5566-f690-11e7-82c1-54f703bac13b.PNG)

Edit: I forgot to mention, that AdvancedBan DOES in fact give the output, that the player is already banned, but does it anyways

**Comment by BlackHawk2306** [comment]
Warum wird dieser Bugreport eigentlich ignoriert? Ist nix kritisches, aber die mehrfach-einträge von Hckern "müllen" leider die Datenbank zu..

**Comment by BlackHawk2306** [comment]
Is there a reason for this report getting ignored`I mean, it isn't a critical bug or so, but it fills the /banlist(and the database) with unnecessary duplicate entries :/

**Comment by DevLeoko** [comment]
I'm sorry that I did not respond I've been a bit busy.
Are you also able to produce multiple punishments when using the punishing command (e.g. /ban) manually via the chat?

**Comment by BlackHawk2306** [comment]
Ah ok. Yes, I can also do that via chat, in case I spam it in. (write the command in chat, press enter, instantly open chat again, press arrow key up, press enter again)

**Comment by DevLeoko** [comment]
Okay ya, AdvancedBan is not meant for spamming commands. I'll mark this as a bug and it will be fixed when I or another Dev will have some time :) thanks for the report.

Just a note for devs:
My first idea would be to solve this with syncronized-blocks and/or locks so that only one punishment process can be run at a time. Maybe not have the same locks for punishment commands and check commands. As they should not interfere. Also AdvancedBan should still be async so it does not cause any lags

**Comment by DevLeoko** [comment]
Should be solved with the newest version: https://www.spigotmc.org/resources/advancedban.8695/update?update=321631
