### ISSUE TITLE
wenn man das bungecord macht und jmd mutet kann der trotzdem /msg machen obwohl das ein mutecommand ist 

### ISSUE THREAD

**Issue by joeymaeuslp** [DevLeoko/AdvancedBan#164]
Mutecommands bei BungeeCord funktionieren nicht 

/msg geht alles geht bitte beheben

**Comment by BlackHawk2306** [comment]
Ich finde das in Ordnung. Ein Mute soll eigentlich ein Chatverbot sein, PM's unter Freunden zu blocken finde ich komplett unnötig. Aber soweit ich weiß, kann man das einstellen ;)

**Comment by joeymaeuslp** [comment]
Danke für deine Rückmeldung man kann mute command einstellen aber das
funktioniert nicht das ist ein bug wenn man ad. ban auf bungeecord nutzt
greifen die mute commands nicht könntest du dir das mal ansehen

Am 15.01.2018 00:26 schrieb "BlackHawk2306" <notifications@github.com>:

Ich finde das in Ordnung. Ein Mute soll eigentlich ein Chatverbot sein,
PM's unter Freunden zu blocken finde ich komplett unnötig. Aber soweit ich
weiß, kann man das einstellen ;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DevLeoko/AdvancedBan/issues/164#issuecomment-357551826>,
or mute the thread

**Comment by DevLeoko** [comment]
Bitte nutze das vorgegebene Support Layout und nach möglichkeiten die Spache Englisch.
Vielen Dank.
