### ISSUE TITLE
Suggestion for /check

### ISSUE THREAD

**Issue by ZxFrankxZ** [DevLeoko/AdvancedBan#165]
I have a suggestion.

Add the option of use /check "ID" for see the sanction.

**Comment by DevLeoko** [comment]
Sounds like a good idea

**Comment by DevLeoko** [comment]
Has been added in #170 by @Beelzebu 
You can download the latest build here: http://v.skamps.eu/jenkins/job/AdvancedBanV2/26/
This update will be released in a few weeks on spigot.

Would be great if you could give us some feedback if everything works :)
