### ISSUE TITLE
Console told me to put the error here and it needs fixing regardless. I have no clue what the issue is :)

### ISSUE THREAD

**Issue by tomtehtom** [DevLeoko/AdvancedBan#166]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
2.1.4-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
Single 
 
_What server version (/version) are you using?_

Spigot 1.12.2 Latest release (maybe a few days old but latest buildtools spigot version.)
_Please provide the EXACT steps required to reproduce the problem..._
1. Start server with advancedban
2. Have a player join?
3. Issue comes up in console.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/kHcCTpWB
Console output, no debug.log was generated??
_Add any additional information below._

**Comment by DevLeoko** [comment]
In the version you have been using, some error messages have not been logged.
As this makes it impossible for us to help this issue will be closed.

You can download the newest build here: http://v.skamps.eu/jenkins/job/AdvancedBanV2/26/
In this build, all errors will be logged to the AdvancedBan logs.

If you get the same issue again with the newer version, make sure to reopen the issue and paste the additional information. I'm sorry for the inconvenience.
