### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to AdvancedBan

### ISSUE THREAD

**Issue by vidum** [DevLeoko/AdvancedBan#168]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
2.1.4-RELASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
Single server
 
_What server version (/version) are you using?_

git-PaperSpigot-"4c7641d" (MC:1.8.8) / API version 1.8.8-R0.1-SNAPSHOT

_Please provide the EXACT steps required to reproduce the problem..._
1. I don't know, every minute this goes on at the console.
(I'm sorry for my bad english)

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

https://hastebin.com/evinaxasat.sql

_Add any additional information below._

**Comment by Beelzebu** [comment]
Seems that is a problem with the database, please enable Debug in the config, try to reproduce this bug and send us the plugins/AdvancedBan/logs/latest.log file.

**Comment by vidum** [comment]
The last packet successfully received from the server was 20,096 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
An unexpected error has ocurred executing an Statement in the database
Please check the debug.log file in the plugin's folder and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
Debug: Query: 
SELECT * FROM `Punishments` WHERE `uuid` = ?
Debug: An error has ocurred with the database, the error code is: '0'
The state of the sql is: 08S01
Error message: Communications link failure

**Comment by DevLeoko** [comment]
Seems like there is an issue with your MySQL server
"The last packet successfully received from the server was 20,096 milliseconds ago"
