### ISSUE TITLE
/ban by an other plugin

### ISSUE THREAD

**Issue by Twonox** [DevLeoko/AdvancedBan#17]
I have an AntiCheat who can execute other plugin's commands but I can't use AB's ban in bungeecord with this plugins.
Any solution ?
I won't ban with essentials, I want ban in all bungeecord servers

**Comment by DevLeoko** [comment]
Sorry this is not possible

**Comment by Twonox** [comment]
If I use AB in all servers exempt bungeecord, with same database (mysql), I can use /ban with this anticheat, but it's "asynchronous". If I ban a player i server A, for server B this player isn't banned, even if I use the same db

**Comment by DevLeoko** [comment]
Ya because if you want to use it on a Server network you will have to install it on the BungeeCord-Server there is no longer the possibility to install it on every Spigot server

**Comment by Twonox** [comment]
I use 

> https://www.spigotmc.org/resources/free-bungeecommandsdispatcher.9854/

to can execute AB commands.

Thanks to dev of my AntiCheat
