### ISSUE TITLE
 Support - BuungeCord

### ISSUE THREAD

**Issue by Motovoh** [DevLeoko/AdvancedBan#172]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
Latest
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BuungeCord
 
_What server version (/version) are you using?_
Latest 1.12.2 Build

_Please provide the EXACT steps required to reproduce the problem..._
1.Why on my buungecord network when i banned somone players cant see the message who i banned?
2.When i restart a buungecord network when i banned somone ip theye can join.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No

**Comment by DevLeoko** [comment]
Where did you install advancedban?

**Comment by Motovoh** [comment]
On buungecord

**Comment by DevLeoko** [comment]
What do you mean by that?
"1.Why on my buungecord network when i banned somone players cant see the message who i banned?"

Are you sure the IP-Bans are handled by advancedban, are they listed in /check or /history or /banlist?

**Comment by Motovoh** [comment]
When i banned somone its not broadcast to every server and its not showing up a message to all players etc 'Leoko got banned for I like This Plugin'

**Comment by DevLeoko** [comment]
Do the players have the required permissions in order to receive the notification?
Also please paste a screenshot of the output of /advancedban

**Comment by Motovoh** [comment]
No i didnt set the permission

**Comment by DevLeoko** [comment]
well then do that in order for other people to receive notifications they need the right notify perms.
Read the plugin page properly https://www.spigotmc.org/resources/advancedban.8695/
