### ISSUE TITLE
Could not pass event AsyncPlayerPreLoginEvent to AdvancedBan v2.1.3-RELEASE

### ISSUE THREAD

**Issue by Kundello** [DevLeoko/AdvancedBan#176]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
  v2.1.3
_What kind of server do you have (`Bungeecord/single server`)?_
Single cracked server.
 
_What server version (/version) are you using?_
Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.58 (MC: 1.7.10)

_Please provide the EXACT steps required to reproduce the problem..._

I use MariaDB mysql server as backend
Charset in db is used - utf8mb4_unicode_ci
Fetcher disabled
When player is not in whitelist and is trying to join, error is writed in console

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

https://pastebin.com/Bf0sYF5d

_Add any additional information below._

**Comment by Kundello** [comment]
Also, if try to punish any player, error is
https://pastebin.com/zFN6A2jr

It seems, sometimes plugin cant correctly connect to database.

**Comment by DevLeoko** [comment]
Sorry but there is no support for outdated versions of AdvnacedBan, the current one is 2.1.4 and 2.1.5 will be released in a few days
