### ISSUE TITLE
Advanchad Ban - Support

### ISSUE THREAD

**Issue by Motovoh** [DevLeoko/AdvancedBan#178]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BuungeCord
 
_What server version (/version) are you using?_
Latest - Spigot 1.12.2 and im using latest BuungeCord.

_Please provide the EXACT steps required to reproduce the problem..._
1.So i have a anti cheat plugin witch auto ban system so i need to install advanchad ban on every single server?
2.Should i also on every server set up MySQL
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any additional information below._

**Comment by Beelzebu** [comment]
You can install [CommandSync](https://www.spigotmc.org/resources/commandsync.115/) to send command to bungeecord from spigot
