### ISSUE TITLE
Just a random bug

### ISSUE THREAD

**Issue by RainOfPain125** [DevLeoko/AdvancedBan#179]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Version • 2.1.4-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 git-Paper-1320 (Paper Spigot)
 
_What server version (/version) are you using?_
Above

_Please provide the EXACT steps required to reproduce the problem..._
1. ?
2. ?
3. Yay, A problem happened! No idea why.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/JcP8gz1a

_Add any additional information below._
I'm using a MySQL setup with this plugin and at first the plugin gave me problems (saying it couldn't connect) but it no longer shows those errors on server boot, so.

**Comment by Beelzebu** [comment]
Install this version http://v.skamps.eu/jenkins/job/AdvancedBanV2/, try to reproduce this bug and send us the plugins/AdvancedBan/logs/latest.log file, the second error is from another plugin and it shouldn't be related to the error of advancedban

**Comment by RainOfPain125** [comment]
Latest ver from that website, the error was encountered again

https://pastebin.com/9W2iPbf4

An unexpected error has ocurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
Query: 
SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?
