### ISSUE TITLE
BuungeCord Error

### ISSUE THREAD

**Issue by Motovoh** [DevLeoko/AdvancedBan#180]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BuungeCord
 
_What server version (/version) are you using?_
Lates Build

_Please provide the EXACT steps required to reproduce the problem..._
1.I dont know :/
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

Query: 
SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?

_Add any additional information below._
No.

**Comment by DevLeoko** [comment]
Install this version http://v.skamps.eu/jenkins/job/AdvancedBanV2/, try to reproduce this bug and send us the plugins/AdvancedBan/logs/latest.log file, the second error is from another plugin and it shouldn't be related to the error of advancedban
