### ISSUE TITLE
API IP-Ban is flawed

### ISSUE THREAD

**Issue by Kavatch** [DevLeoko/AdvancedBan#181]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Newest Version allways
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
Newest Waterfall
and 1.8.8-R0.1 Spigot

_Please provide the EXACT steps required to reproduce the problem..._
When I use the API of the plugin in my plugin and use this code:
`new Punishment(args[0], uuid, "Ban", p.getName(), PunishmentType.BAN, TimeManager.getTime(), -1, null, -1).create(false);
                                new Punishment(args[0], uuid, "IP-Ban", "CONSOLE", PunishmentType.TEMP_IP_BAN, TimeManager.getTime(), TimeManager.getTime() + 1800000, null, -1).create(false);`
It will just ban the player normal with no ip ban.
When I use the /tempipban ingame it will ip ban the player.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No error

_Add any additional information below._
When I execute the code it will still give a the right output ingame.
It looks something like this:
https://s.4lex.de/1qX
Two new entries have also been added to the database.
It even says it's an IP ban, but it's not.

**Comment by Kavatch** [comment]
Oh, and one more thing. It even shows for the banned player that he or she is ip banned. But If this player plays with a second account he is not ip banned although he has the same ip.

**Comment by DevLeoko** [comment]
If you want to create an IP-Ban or Temp-IP-Ban you will need to input the users IP address instead of his uuid
