### ISSUE TITLE
UUID Support with FastLogin

### ISSUE THREAD

**Issue by xXSchrandXx** [DevLeoko/AdvancedBan#183]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.3-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord without AdvancedBan on Backend Server
 
_What server version (/version) are you using?_
1.12.2

_Please provide the EXACT steps required to reproduce the problem..._
1. Use [FastLogin](https://www.spigotmc.org/resources/fastlogin.14153/)
2. Set the UUID-Fetcher on enabled and / or Intern (or Dynamic)
3. Try to join the Server

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No Error: Just getting that my UUID could not be Fatched or it won't use the UUID in Punishments.

_Add any additional information below._
Would a UUID-Fetcher for my Server wich gives Information over the players UUID from FastLogins Database help?

**Comment by DevLeoko** [comment]
Why don't you just disable the uuid fetcher?

**Comment by xXSchrandXx** [comment]
I do have this disabled, but with FastLogin I do get Minecraft Premium UUIDs and Offline UUIDs. So if a player want to use the Mojang feature (renaming) he will getr unbanned becrause it does not use the intern (FastLogin) UUID.

**Comment by Beelzebu** [comment]
You should use intern UUID fetcher due FastLogin forces the player's UUID, the intern fetcher get the UUID that the server has for the player.

**Comment by xXSchrandXx** [comment]
I do use AdvancedBan only on the BungeeCord Server => I tried but it doesn't use the UUID

**Comment by Beelzebu** [comment]
Seems that FastLogin set the player's UUID in the [LoginEvent](https://github.com/games647/FastLogin/blob/master/bungee/src/main/java/com/github/games647/fastlogin/bungee/listener/ConnectListener.java#L66) and AdvancedBan in the PreLoginEvent, that means that AdvancedBan caches the player UUID before FastLogin set the UUID, so we must change this to to ensure compatibility

**Comment by xXSchrandXx** [comment]
I do think that your response about this to the owner of FastLogin is better. So it would be nice if you coult help each other with this. Repo: https://github.com/games647/FastLogin/
