### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by friishon** [DevLeoko/AdvancedBan#184]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBan version 2.1.4-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.12.2

console error
http://paste.degoos.com/meraworedo.md

**Comment by Beelzebu** [comment]
Enable debug in the config, try to reproduce the error and send latest.log file located in plugins/AdvancedBan/logs
