### ISSUE TITLE
Accents doesn't works in config

### ISSUE THREAD

**Issue by UnChatEnSlip** [DevLeoko/AdvancedBan#19]
Hi, good plugin, but beacause i'm french, I'm must add accents in config, but it's not works. How to add it ?
Sorry for my bad English.
Bye

**Comment by DevLeoko** [comment]
You will have to escape this unicode-chars with \-codes.
For example for » you will have to use \xbb

But sorry I've no idea how to get this codes

**Comment by UnChatEnSlip** [comment]
It's work and not work : look my screens in noelshack :

http://image.noelshack.com/fichiers/2016/48/1480447503-2016-11-29-20-24-47.png
http://image.noelshack.com/fichiers/2016/48/1480447517-2016-11-29-20-25-08.png

The first image must display "Vous avez été déconnecté" in the first line, and it's display : "Vous avez \u00e9t\u00e9 d\u00e9connect\u00e9" what I can adjust the problem ?

And the caps in notification ban/kick/mute etc... not works, what I can put in the UUID Fetcher config ?

Thank you in advance !

**Comment by dutchy1001** [comment]
could you post the configs you have this line in so I can try and test it what and how to use

**Comment by UnChatEnSlip** [comment]
I've attached the config... 
[Config AdvanedBan.zip](https://github.com/DevLeoko/AdvancedBan/files/621910/Config.AdvanedBan.zip)

**Comment by DevLeoko** [comment]
If you use \-codes you will have to use " and not '
so not
'[&c&lX-15&f] &cVous avez \u00e9t\u00e9 averti pour %REASON%'
but
"[&c&lX-15&f] &cVous avez \u00e9t\u00e9 averti pour %REASON%"

**Comment by UnChatEnSlip** [comment]
I test it...

**Comment by UnChatEnSlip** [comment]
It's work !! Thank you ! But what I can put in the config for respect Caps Pseudos in notification message ?

**Comment by DevLeoko** [comment]
This is sadly not possible

**Comment by UnChatEnSlip** [comment]
I can't put others parameters in UUID-Fetcher ?

**Comment by UnChatEnSlip** [comment]
And I have 1 question : How to sudo console execute command /playsound .......................... on ban ?

**Comment by DevLeoko** [comment]
No this is not a problem from the uuid-fetcher but in the way the bans are saved. This will be probably fixed in one of the next version. 
And there will also be a feature to execute commands on kick/ban/mute/warn

**Comment by UnChatEnSlip** [comment]
Okey ! When will be the next version ?

**Comment by DevLeoko** [comment]
I'm not able to say this yet. I'm currently not working so much on advancedban

**Comment by UnChatEnSlip** [comment]
Ok
