### ISSUE TITLE
Single is spelled incorrectly in repo desc.

### ISSUE THREAD

**Issue by ir-3** [DevLeoko/AdvancedBan#192]
This is an issue nobody is going to like but...
The description of this repository is currently,
> AdvancedBan is a ban plugin for singel servers and server networks with a great looking ban message

While it should be...

> AdvancedBan is a ban plugin for single servers and server networks with a great looking ban message!

The issue there is that **single** is spelled incorrectly.
Thanks!

**Comment by ir-3** [comment]
I don't think it is a bug. It is more of a community-centered issue. This is a bit late isn't it?

**Comment by BenjaminUrquhart** [comment]
So late I forgot this repo existed

**Comment by ir-3** [comment]
Lol

**Comment by DevLeoko** [comment]
Haha just took me two years to fix that on ^^

**Comment by BenjaminUrquhart** [comment]
I forgot this issue existed
