### ISSUE TITLE
Per world plugins issue

### ISSUE THREAD

**Issue by JulianFRL** [DevLeoko/AdvancedBan#193]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.4
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single server
 
_What server version (/version) are you using?_
1.12.2

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/YMQ4E54A

_Add any additional information below._

**Comment by DevLeoko** [comment]
The paste "https://pastebin.com/YMQ4E54A" is not available anymore
