### ISSUE TITLE
Punishments failing to register

### ISSUE THREAD

**Issue by SpooderCraft** [DevLeoko/AdvancedBan#194]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_: AdvancedBan-2.1.5-SNAPSHOT.jar

_What kind of server do you have (`Bungeecord/single server`)?_: Bungeecord
 
 
_What server version (/version) are you using?_/: all servers are 1.12

_Please provide the EXACT steps required to reproduce the problem..._
1. used a ban gui from melon coal to temp ban user
2.bans user
3. bans user again
4. lets user back in server

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._: https://pastebin.com/jqdLPM9V

_Add any additional information below._ fails to ban users

**Comment by MelonCola** [comment]
It's not a problem with the ban GUI, it's with MySQL. And he's not purposely banning the user twice and having it let the user back in.

**Comment by SpooderCraft** [comment]
ya it does it more then once

**Comment by DevLeoko** [comment]
"Please check the plugins/AdvancedBan/logs/latest.log file and report this error"

**Comment by SpooderCraft** [comment]
https://pastebin.com/jqdLPM9V

**Comment by SpooderCraft** [comment]
That is the log

**Comment by SpooderCraft** [comment]
what do i do??

**Comment by DevLeoko** [comment]
does this error also occur when you use the commands directly without the GUI?

**Comment by SpooderCraft** [comment]
yup!

**Comment by SpooderCraft** [comment]
Yup!

**Comment by SpooderCraft** [comment]
Can u fix it?

**Comment by DevLeoko** [comment]
Please wait for 48h before pushing an issue...
Anyway could you send me a screenshot of /advancedban so I can get an idea of your setup

**Comment by SpooderCraft** [comment]
![image](https://user-images.githubusercontent.com/31389391/38050780-286c05d2-329a-11e8-9afc-3e1e16926053.png)

**Comment by DevLeoko** [comment]
Would it be a possibility for you to just use HyperSQL (local sotrage)?

**Comment by SpooderCraft** [comment]
you mean when it stored in a file in the advancedban folder? then yes. do you want me to change it?

**Comment by SpooderCraft** [comment]
is that what u mean?

**Comment by MelonCola** [comment]
It's a database file I believe, also you only have to comment once and he'll see it.

**Comment by DevLeoko** [comment]
"Please wait for 48h before pushing an issue..."
Support rejected - This is my hobby not my full time job
