### ISSUE TITLE
webpanel mysql error

### ISSUE THREAD

**Issue by justinbea** [DevLeoko/AdvancedBan#195]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 First 2.1.4 release than 2.1.5 snapshot
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
 This server is running CraftBukkit version git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. making database and filling it in on the webpanel register
2. and plugin is not accepting my database
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/LQuy1Tcm

_Add any additional information below._
error on webpanel register
The MySQL-Data are not valid! 
Failed: Host 'at-viex-inx-r16.ha184092.xenox.systems' is not allowed to connect to this MySQL server

**Comment by DevLeoko** [comment]
Seems like your MySQL Server is not reachable from outside localhost.
You can validate your MySQL-Data here: http://skamps.eu/MySQL/

**Comment by justinbea** [comment]
your MySQL tester is saying: Connection test result: Failed
Host 'at-viex-inx-r16.ha184092.xenox.systems' is not allowed to connect to this MySQL server

**Comment by DevLeoko** [comment]
Yap, that means that the issue is not on our side. You will need to make your MySQL-Server reachable from outside localhost. Ask Google how to do that ;)
