### ISSUE TITLE
database, banpanel

### ISSUE THREAD

**Issue by justinbea** [DevLeoko/AdvancedBan#196]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 latest
 
_What kind of server do you have (`Bungeecord/single server`)?_
 bungee
 
_What server version (/version) are you using?_
does not matter

_Please provide the EXACT steps required to reproduce the problem..._
1. none
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
arent

_Add any additional information below._

What is the best way to remove 'test' bans/kicks/warns/mutes & shit, out of the banpanel.eu and /history of the advancedbans plugin?

**Comment by DevLeoko** [comment]
History cannot be cleared.

**Comment by justinbea** [comment]
-.-
