### ISSUE TITLE
error has to report it

### ISSUE THREAD

**Issue by justinbea** [DevLeoko/AdvancedBan#199]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Version • 2.1.5-SNAPSHOT

 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
bungeecord and other servers are 1.12.2 with back&via version

_Please provide the EXACT steps required to reproduce the problem..._
1. report it here
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/80V53VdJ
https://pastebin.com/XcHq6gAL
_Add any additional information below._

**Comment by DevLeoko** [comment]
Already reported in #203 as a bug. Thanks anyway for the report
