### ISSUE TITLE
Problems with Cyrillic alphabet in AB

### ISSUE THREAD

**Issue by AIphaDragon** [DevLeoko/AdvancedBan#202]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.4
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.12.2

_Please provide the EXACT steps required to reproduce the problem..._
Hello! We connected the plugin to mysql and ran into a problem when issuing a penalty: if you use the Cyrillic alphabet at the beginning of the penalty, then mysql will be "???". Thanks in advance for your help.

**Comment by DevLeoko** [comment]
The MySQL-Tables and Connection are not UTF-8 by default for some reason so this would be a feature request to add the support in the code

**Comment by AIphaDragon** [comment]
The problem was solved by adding "useUnicode=true&characterEncoding=utf8"
Code: https://pastebin.com/DMdNKuC8
Thanks for the answer.
