### ISSUE TITLE
Database Error?

### ISSUE THREAD

**Issue by B4TT3RY** [DevLeoko/AdvancedBan#205]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.4-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single Server
 
_What server version (/version) are you using?_
PaperSpigot 1.12.2 (b1414)

_Please provide the EXACT steps required to reproduce the problem..._
1. Backup Databse in A Server
2. Restore Database in B Server
3. Boot
4. Join

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/E0CdCVKg

_Add any additional information below._

**Comment by DevLeoko** [comment]
HSQL is the local storage.
Are you sure that the restored database is 100% correct? It's most likely that there went something wrong with the backup

**Comment by B4TT3RY** [comment]
Hmm maybe?
umm i'll backup and reset db
