### ISSUE TITLE
AdvancedBan masks tab completion for server command arguments

### ISSUE THREAD

**Issue by Brianetta** [DevLeoko/AdvancedBan#206]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.4-RELEASE

_What kind of server do you have (`Bungeecord/single server`)?_
Bungecord (Waterfall)
 
_What server version (/version) are you using?_
Waterfall version git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175

_Please provide the EXACT steps required to reproduce the problem..._
1. Start a command (such as /minecraft:setblock)
2. Press the tab key to try to complete parameters (without starting them off)
3. See the alphabetically first player's name appear instead of a relevant argument

_Add any additional information below._

When handling Bungee's **TabCompleteEvent**, AdvancedBan should determine whether the cursor begins with a `/` (effectively, "isCommand") and if it does, should only populate the suggestions list if the command is one of AdvancedBan's own commands. At present, players are noticing that they can't tab complete Essentials homes, and I'm noticing that I can't tab complete Spigot-side LuckPerms commands unless I first type enough of a command to exclude any player names.

An easy way to demonstrate is the built in Minecraft command `/setblock`. When not running AdvancedBan, it's possible to target a block and start the command `/setblock`, using tab to complete the X, Y and Z parameters followed by the block name. When running AdvancedBan, only player names are suggested, unless the arguments are started off sufficiently that no players can possibly match, which rather takes away from the fact that Minecraft allows you not to have to look up the numbers from the debug screen.

If the player is tab completing a command (the cursor starts with `/`), and that command is not one of AdvancedBans' own commands, the suggestions list should be left empty, which passes the task of tab completion through to the destination server.

**Comment by Brianetta** [comment]
That's a start (and a distinct improvement in my use case). Need to find a way to get all of the commands provided by AdvancedBan.

Next steps:
 - Allow this plugin's commands to be tab-completed
 - Tab-complete the player's name if it's the right argument to do that
 - Don't tab-complete things like time specifications with player names

**Comment by Brianetta** [comment]
This fix isn't compatible with the development branch, but I made use of `plugin.yml` to get the list of commands, which means that the code doesn't have to be altered if the commands change.

**Comment by Beelzebu** [comment]
I think that another solution for this is get the commands from this plugin from the proxy using reflection to get the [multimap of commands registered in the proxy](https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/plugin/PluginManager.java#L54) and then check if the command in the event is from this plugin, it would not break if any command is removed or added

**Comment by DevLeoko** [comment]
Your code cannot be used as it would break on Spigot-Servers because you Import Bungeecord-Classes in the Universal.java which is used for both bungee and spigot. So I labeled this as a bug report and maybe there will be an official fix for this someday. Thanks anyway for the detailed report.

**Comment by BrainStone** [comment]
I think 2.1.5 fixes this issue.

**Comment by DevLeoko** [comment]
Yes it does 👍
