### ISSUE TITLE
[Request] Reasons changing

### ISSUE THREAD

**Issue by Twonox** [DevLeoko/AdvancedBan#21]
If I want change, for example, the ban reason, I must unban and ban again with the new reason.
So, my request is: be able to change the reason without doing this, just redo `/ban PLAYER newReason` like essentials.

**Comment by dutchy1001** [comment]
I like the idea, it can be very handy. 
Atm I open my MySQL DB and change it manual (using [HeidiSQL](http://www.heidisql.com/)) if needed but it would make it a lot easier with a new command indeed

**Comment by DevLeoko** [comment]
This is already planned :) You can see what is planned on the main page under "ToDo"
https://www.spigotmc.org/resources/advancedban.8695/

**Comment by DevLeoko** [comment]
Added in 2.0.0 ;)
