### ISSUE TITLE
Failed to fetch your UUID

### ISSUE THREAD

**Issue by Ant4rez** [DevLeoko/AdvancedBan#210]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.4
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
_What server version (/version) are you using?_
This server is running CraftBukkit version git-Spigot-2086bb0-8cc5a7e (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
_Please provide the EXACT steps required to reproduce the problem..._
1.Log in
_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/T2FyCtnW
_Add any additional information below._
Plugins: AdvancedBan, BungeeChat, BungeePerms, BungeeTools-HubCommand,EhLogin,ServerListPlus,SkinRestorer.

**Comment by Beelzebu** [comment]
Try enabling dynamic uuid fetcher in the config, if you have it already enabled try without "EhLogin"

**Comment by Ant4rez** [comment]
I have it enabled, but the problem is i can't remove the ehlogin, is my authentication plugin for the server.

**Comment by Ant4rez** [comment]
Yes is cracked, but i'm premium. The weird thing is i have a friend that is a cracked user and he can join, but other friend that is also cracked he can't join, is like if has a random thing.

**Comment by DevLeoko** [comment]
That's weird, if your server is cracked it should automatically disable the uuid fetcher if it's set to dynamic
Try manually disabling it in the config

**Comment by Ant4rez** [comment]
Thanks for the support at the moment. i'm going to try dat. First with the dynamic enabled (again), and then if i have the problem, i'm going to try disabling it manually on the config, and comment here the log's for problem.

**Comment by Ant4rez** [comment]
Hello again, well i try with the dynamic. and he can't join, with this config file: https://hastebin.com/ewegipujaz.pl
And this is the log for the bungee server:
https://hastebin.com/rajakiluca.sql

And with it disabled, https://hastebin.com/giponeqobu.pl this happen:

> "08.06 16:36:59 [Server] INFO Load uuid from cache
> 08.06 16:36:59 [Server] INFO Login by McFco"

He can join, but what happen if i have the plugin configured like that?.

**Comment by DevLeoko** [comment]
Instead of using the UUID it uses the Username to identify the User. Which is the right thing to do if you have a cracked server ;D

**Comment by Ant4rez** [comment]
Thank you, and thanks also for update the plugin, greetings:D.

**Comment by DevLeoko** [comment]
Seems like your MySQL-Server died :P
