### ISSUE TITLE
 Is there a way for players to click a link once they are banned?

### ISSUE THREAD

**Issue by Sonic8608** [DevLeoko/AdvancedBan#215]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBan-2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Spigot
 
_What server version (/version) are you using?_
1.12.1-R0.1-SNAPSHOT
---------------------------
question - Is there a way for players to click a link once they are banned?

**Comment by DevLeoko** [comment]
no that's technically not possible
