### ISSUE TITLE
[Request] Unban with BanID

### ISSUE THREAD

**Issue by Elternbrief** [DevLeoko/AdvancedBan#22]
Hey,
ich würde mir den Befehl "/unbanip <ID>" wünschen

Mithilfe von diesem sollte man einen Bann mit der BanID auflösen können.

Ich würde mich freuen, wenn ihr diesen Befehl einführen könntet...

**Comment by DevLeoko** [comment]
Wozu genau würdest du so etwas brauchen?

**Comment by dutchy1001** [comment]
If My translation is correct then it might be something to think about.

When you ban a player's IP but then realise his little sister can't join either (and did nothing wrong) could be a bit unfair for that sister. Instead to unban the player you unban the IP so his little sister can join again while the uuid of the bad guy is still banned.

When you unban a player now you do both the UUID and the IP while you have to ban (player and IP) each separate with 2 different commands, makes sense to have 2 different unban commands to then.

**Comment by DevLeoko** [comment]
No he does not me the IP-Adress but the ID which every punishment has.
Not sure why he typed "/unbanip" :D

**Comment by Elternbrief** [comment]
Sorry, ich meinte /unbanid

Sodass du mit der BanID Spieler entbannen kann

Es würde aber auch eine Ergänzung des /unban Commands gehen, sprich: /unban <Spielername/UUID/IP/BanID"

**Comment by Elternbrief** [comment]
*kannst

**Comment by dutchy1001** [comment]
that's google translate for ya lol

**Comment by Elternbrief** [comment]
Es wäre meiner Meinung schöner bei Entbannungsanträgen mithilfe der ID Spieler entbanden zu können

**Comment by Elternbrief** [comment]
*entbannen

**Comment by dutchy1001** [comment]
You could use the "edit" button to correct your post instead of 1 word posts

**Comment by Elternbrief** [comment]
Sorry, i can't see it on mobile

**Comment by md678685** [comment]
@Elternbrief You can scroll to the bottom and click "Desktop version" and the edit button will show up

**Comment by DevLeoko** [comment]
Added in 2.0.6
