### ISSUE TITLE
Migration from HSQLDB to MySQL

### ISSUE THREAD

**Issue by Morsmorse** [DevLeoko/AdvancedBan#221]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.1.6-SNAPSHOT
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungee
 
_What server version (/version) are you using?_
BungeeCord-Bootstrap:1.12-SNAPSHOT:2356dbc:1318

_Please provide the EXACT steps required to reproduce the problem..._
1. Created MySQL Database
2. Edited the mysql config
3. Set UseMySQL:  to true
4. Restarted

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/qYM9gcCi

_Add any additional information below._
/

**Comment by DevLeoko** [comment]
Please post the AdvancedBan logs: plugins/AdvancedBan/logs/latest.log

**Comment by Morsmorse** [comment]
The pastebin i posted (https://pastebin.com/qYM9gcCi) is the AB-log regarding this error.

The other logs are just "normal" stuff I guess but have a look:
https://pastebin.com/KEbxAzxX

**Comment by DevLeoko** [comment]
Please check if the latest build fixes your issue: http://v.skamps.eu/jenkins/job/AdvancedBanV2/45/
Provided by @BrainStone 👍
