### ISSUE TITLE
No permission

### ISSUE THREAD

**Issue by Noel12346** [DevLeoko/AdvancedBan#228]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 "AdvancedBan-2.1.5-RELEASE" 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.12.2

_Please provide the EXACT steps required to reproduce the problem..._
1.  Add the plugin on bungeecord.
2. Wite "/ban [NAME]" in the chat.
3. And it shows up a permission problem.
4. I add the permission node on PermissionsEx.
5. And it still does not work.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
In the chat it stands "AdvancedBan » You don't have perms for that!"

_Add any additional information below._
But when i ban in the bungeecord console it works.

**Comment by supertassu** [comment]
You have to give the permissions on bungee if the plugin is installed on bungeecord.

**Comment by Noel12346** [comment]
How?

**Comment by Noel12346** [comment]
oh

**Comment by Noel12346** [comment]
I know

**Comment by Beelzebu** [comment]
There is an explanation about the permissions in the wiki https://github.com/DevLeoko/AdvancedBan/wiki/Commands-%26amp%3B-Permissions
