### ISSUE TITLE
Issue with BanPanel register

### ISSUE THREAD

**Issue by RemcoPl** [DevLeoko/AdvancedBan#229]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single
 
_What server version (/version) are you using?_
1.8

_Please provide the EXACT steps required to reproduce the problem..._
1.  idk
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
On the website for the banpanel to create
504 Gateway Time-out
nginx

_Add any additional information below._
i want to create a BanPanel for my server and i cant do this on any pc of me

**Comment by DevLeoko** [comment]
Should be resolved

**Comment by DevLeoko** [comment]
The official ban panel has been discontinued for now
