### ISSUE TITLE
Unable to update Punishment ID

### ISSUE THREAD

**Issue by LovesAsuna** [DevLeoko/AdvancedBan#231]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord
 
_What server version (/version) are you using?_
1.12.2

_Please provide the EXACT steps required to reproduce the problem..._
1.No able to update ID of punishment
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
[latest.log](https://github.com/DevLeoko/AdvancedBan/files/2172692/latest.log)

_Add any additional information below._
nothing

**Comment by RaidAndFade** [comment]
`No able to update ID of punishment! Please restart the server to resolve this issue!`
Have you tried restarting the server?

**Comment by LovesAsuna** [comment]
yes,I did

**Comment by DevLeoko** [comment]
Should be solved with the newest version: https://www.spigotmc.org/resources/advancedban.8695/update?update=321631
