### ISSUE TITLE
AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by Alperenn** [DevLeoko/AdvancedBan#233]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 v2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1.??
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
Pastebin is banned in my country
https://hastebin.com/nejefosaqe.sql

_Add any additional information below._

**Comment by Beelzebu** [comment]
Please send us `plugins/AdvancedBan/logs/latest.log` file, it should contain more information about this error

**Comment by Alperenn** [comment]
https://hastebin.com/uxogamezag.sql

**Comment by Beelzebu** [comment]
Can you install this version and try to reproduce the problem? https://ci.nifheim.net/job/Beelzebu%20AdvancedBan/
It will send all debug messages to the console, these debug messages contain more information about this error

**Comment by Alperenn** [comment]
https://hastebin.com/anisapimin.sql

**Comment by Beelzebu** [comment]
Your MySQL server is closing the connection, if you're using the plugin in a single bungeecord server try disabling MySQL to use H2SQL (local storage)
