### ISSUE TITLE
An unexpected error has ocurred executing an Statement in the database

### ISSUE THREAD

**Issue by Sprax2013** [DevLeoko/AdvancedBan#234]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5-RELEASE
 
_What kind of server do you have (`BungeeCord/single server`)?_
 BungeeCord
 
_What server version (/version) are you using?_
git:BungeeCord-Bootstrap:1.12-SNAPSHOT:2356dbc:1318

_ Please provide the EXACT steps required to reproduce the problem..._
1. Try to connect to BungeeCord
2. Timeout and read the exception

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/KBPuXJ3q

_Add any additional information below._
A player can't join when the exception is thrown. He gets a timeout and can reconnect. Then he can join normally.

**Comment by DevLeoko** [comment]
Try using our newest build from Jenkins: http://v.skamps.eu/jenkins/job/AdvancedBanV2/46/
Please tell us if that resolved your issue

**Comment by Sprax2013** [comment]
The Snapshot seems to fix the issue! (Sorry, I forgot about this issue)
