### ISSUE TITLE
[MySQL] Communications link failure

### ISSUE THREAD

**Issue by downboy** [DevLeoko/AdvancedBan#235]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.6-SNAPSHOT
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungecoord and Single server(for testing)
 
_What server version (/version) are you using?_
This server is running CraftBukkit version git-Spigot-2086bb0-2f3ed3b (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) << test server info

_Please provide the EXACT steps required to reproduce the problem..._
1. let the server run for a while, dont login for like 11,107,629 milliseconds
2. login
3. you will see the mysql error show in the console 

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://hastebin.com/pefetupame.sql

_Add any additional information below._

**Comment by james090500** [comment]
convert sql is running and not timing out the user.

**Comment by DevLeoko** [comment]
Should be solved with the newest version: https://www.spigotmc.org/resources/advancedban.8695/update?update=321631
