### ISSUE TITLE
Mysql Error

### ISSUE THREAD

**Issue by Tanimsiz** [DevLeoko/AdvancedBan#236]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.12.2

_Please provide the EXACT steps required to reproduce the problem..._
1. To connect to the database

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://hastebin.com/edotalocis.sql

_Add any additional information below._
I tried delete the database but doesn't work.

**Comment by A248** [comment]
It seems your hastebin link is broken.

Also, please take a look at #203 . This issue may be a possible duplicate.
