### ISSUE TITLE
How do I connect MYSQL?

### ISSUE THREAD

**Issue by rockyhawk64** [DevLeoko/AdvancedBan#238]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.8.8-R0.1-SNAPSHOT

_Please provide the EXACT steps required to reproduce the problem..._
Not necessary

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
29.07 10:35:35 [Server] INFO Enabling AdvancedBan v2.1.5-RELEASE
29.07 10:35:35 [Server] INFO MySQL-Error
29.07 10:35:35 [Server] INFO Could not connect to MySQL-Server!
29.07 10:35:35 [Server] INFO Disabling plugin!
29.07 10:35:35 [Server] INFO Check your MySQL.yml

_Add any additional information below._
I don't think the above is necessary but does anyone know what I have to put in to the MySQL file to make it work? Right now this is it:

  IP: mysql://152.4.265.156/db_65435
  DB-Name: db_65435
  Username: db_65435
  Password: b6en6rdhre
  Port: 3306

The password isn't the actual one aswell as the IP and the number after the "db_" for obvious reasons... Im using ShockByte to host the server.. The password is the same one I used for the PEX SQL but why is there a "DB-Name" section in this one? I'm not sure what to put there. Also is the IP in the right format cause there is zero documentation on how to do this and every tutorial I could find (they were also in different languages) all put "localhost" and "root" and they don't help... Please help :)

**Comment by DevLeoko** [comment]
If this issue is still relevant, please check the AdvancedBan logs for a more detailed error on the MySQL Failure. Also if the Database is on another host and/or should be accessible from outside localhost you can validate your MySQL-Data here: http://skamps.eu/MySQL/

**Comment by A248** [comment]
Change your IP field to simply `152.4.265.156`
