### ISSUE TITLE
Failed Captcha?

### ISSUE THREAD

**Issue by xChicken** [DevLeoko/AdvancedBan#239]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Latest (2.1.5)
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.8

_Please provide the EXACT steps required to reproduce the problem..._
1.Went to banpanel
2.Registered
3.Says "Failed Captcha"

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No

_Add any additional information below._
All my info is correct, it just says failed captcha
![image](https://user-images.githubusercontent.com/41967903/43475951-35182c36-94ef-11e8-9b9e-f20fbd47ad13.png)

FOR THE RECORD, I DID COMPLETE THE CAPTCHA

**Comment by DevLeoko** [comment]
While this issue got solved a few days ago there occurred another issue which made us close the entire registration page for now. This all should be working again in the upcoming days.

**Comment by DevLeoko** [comment]
The official ban panel has been discontinued for now
