### ISSUE TITLE
AdvancedBan permission

### ISSUE THREAD

**Issue by toxicdoolittle** [DevLeoko/AdvancedBan#24]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.0.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Spigot single server
 
_What server version (/version) are you using?_
1.11

_Please provide the EXACT steps required to reproduce the problem..._
1.Help or possible bug fix
2.I'm trying to add ab.ban/mute/warn.temp but it does not seem to work
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
.I'm trying to add ab.ban/mute/warn.temp but it does not seem to work

_Add any aditional information below._
.I'm trying to add ab.ban/mute/warn.temp but it does not seem to work

**Comment by md678685** [comment]
Please actually follow the template, instead if copying and pasting the same message three times. Post logs and tell us how you're trying to add the permissions.

**Comment by dutchy1001** [comment]
The permission **_ab.ban/mute/warn.temp_** should be read different (and I agree it's confusing how this is mentioned on the main page).
Change the permissions to
- ab.warn.temp
- ab.mute.temp
- ab.ban.temp

This count for all permissions posted that have 2 or 3 **/** in them

**Comment by toxicdoolittle** [comment]
Oh thanks
