### ISSUE TITLE
MySQL unique mistake

### ISSUE THREAD

**Issue by itsTyrion** [DevLeoko/AdvancedBan#243]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
Latest(2.1.5)
 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. Use the plugin with MySQL

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
-

_Add any additional information below._

AdvancedBan seems to be setting the name column as unique identifier, rather than the ones with UUID's

**Comment by DevLeoko** [comment]
It uses the ID as the primary key

**Comment by BlackHawk2306** [comment]
That's odd. Maybe a couple of versions ago? Bc in my db, for some reason, the name was the primary key o.O

**Comment by DevLeoko** [comment]
ID has always been the primary key as the name is not unique if e.g. the user got punished two times.
You can try to refactor the database manually or just delete it and let AdvancedBan generate a new one for you.
