### ISSUE TITLE
[2.1.5/MC 1.12.2] Can't connect to MySQL-Server!

### ISSUE THREAD

**Issue by MichelArendt** [DevLeoko/AdvancedBan#244]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 CraftBukkit - Spigot 1.12.2-R0.1-SNAPSHOT
 
_What server version (/version) are you using?_
 CraftBukkit - Spigot 1.12.2-R0.1-SNAPSHOT

_Please provide the EXACT steps required to reproduce the problem..._
1. Download plugin;
2. Run server;
3. Close server;
4. Edit MYSQL.yml (as in picture below);
5. Run server.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
AdvancedBan config - https://cdn.discordapp.com/attachments/339115490272083970/482766939912142873/unknown.png
LuckPerms config - http://prntscr.com/kmnoxh

_Add any additional information below._
Maybe I'm being dumb and missing something obvious, however changing the IP to localhost didn't help either. Also, creating another DB user different from root - with password - didn't help.
I have LuckPerms-Bukkit-4.2.75 (screenshot 2) and HelpTickets 3.2 which also connect to the DB without issue (as seen by the screenshot above), this leads me to believe it's an issue with this plugin.
"Debug: true" doesn't show any additional info.

Thank in advance!

**Comment by DevLeoko** [comment]
AdvancedBan has a separate log system with the logs stored in the AdvancedBan folder. Please check them for further error messages.

**Comment by MichelArendt** [comment]
I've checked them (also the zipped ones) and those logs are only showing the same info the console does:
http://prntscr.com/kmrpzu
Turning "**Debug: true**" doesn't change the log contents either.

**Comment by ajgeiss0702** [comment]
I am having the same problem.

**Comment by A248** [comment]
Try surrounding your password option with quotes, e.g.
`password: ''` instead of `password: `

**Explanation**
A null String ≠ an empty string. AdvancedBan may be having trouble with a null MySQL password, but an empty password would probably work.
