### ISSUE TITLE
Punishment Don't Remove

### ISSUE THREAD

**Issue by DevCold211** [DevLeoko/AdvancedBan#246]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Spigot
 
_What server version (/version) are you using?_
1.12.2

_Add any additional information below._
Its not on a database it so when i tempban or whatever i dont know this is for every temp command but it dose not remove the punishment at all we have to go to storage.script just to remove it

**Comment by DevLeoko** [comment]
Please check if our latest dev build fixes your issue: http://v.skamps.eu/jenkins/job/AdvancedBanV2/47/

**Comment by DevCold211** [comment]
It dosent even show

**Comment by DevLeoko** [comment]
http://v.skamps.eu:8080/job/AdvancedBanV2/47/
