### ISSUE TITLE
UUID activation 

### ISSUE THREAD

**Issue by TheCalypso** [DevLeoko/AdvancedBan#247]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
 2.1.5
_What kind of server do you have (`Bungeecord/single server`)?_
BungeeCord and Spigot server 1.12.1 
 
_What server version (/version) are you using?_
1.12.1

_Please provide the EXACT steps required to reproduce the problem..._
1. System of UUID is not enable

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No error

_Add any additional information below._
I would like to comment activate the UUID system because the url in the config.yml file is not valid, but that I found yes .php? pseudo = TheCalypso) returns it on the site 3fff8c3980454c0390887a0bbc6d4657.

Thank you very much

TheCalypso

**Comment by TheCalypso** [comment]
I would like to know how to activate uuid mode because when I do / advancedban it shows Uuid mode disable. I would like to make it enable.

**Comment by DevLeoko** [comment]
Duplicated by yourself in #248 ...
