### ISSUE TITLE
UUID mode Disabled

### ISSUE THREAD

**Issue by TheCalypso** [DevLeoko/AdvancedBan#248]
**_What version of AdvancedBan (/AdvancedBan) are you using?**
2.1.5

**What kind of server do you have (Bungeecord/single server)?**
BungeeCord and Spigot server 1.12.1

**What server version (/version) are you using?**
1.12.1

**Please provide the EXACT steps required to reproduce the problem...**
System of UUID is not enable

**Any error/log post it through pastebin.com and link it here.**
No error

**Add any additional information below.**
I would like to know how to enable the UUID mode because when I do /advancedban it shows that the UUID mode is disabled.

This time my english is it correct xD

Thank you very much

TheCalypso

**Comment by DevLeoko** [comment]
AdvancedBan chooses automatically the best UUID-Settings by itself.
So if it's disabled there is most likely a good reason for that (e.g. your server is cracked).

If you want to forcefully enable it any way you can do that in the config under the UUID-Fetcher settings.
