### ISSUE TITLE
BUG bypass mute denied commands

### ISSUE THREAD

**Issue by TheMinerBear** [DevLeoko/AdvancedBan#25]
2.0.5
 
 
BungeeCord
 
 
Spigot 1.8.8 (under BungeeCord)

Basically, "MuteCommands:" can be bypassed if you use caps writing the commands.
1. Open config.yml
2. Add a command to "MuteCommands:"
3. If a player is muted, he can't do the commands, but if he writes it on caps, it will bypass (it's caps sensitive)

_Add any aditional information below._

**Comment by DevLeoko** [comment]
Oh ya I see this a serious issue.
As soon as I'll have any free time I'll fix it, thanks for reporting this bug :)

**Comment by dutchy1001** [comment]
tested this with the latest dev build and seems to be fixed
