### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by MattPuffin** [DevLeoko/AdvancedBan#251]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 v2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single spigot server
 
_What server version (/version) are you using?_
This server is running CraftBukkit version git-Spigot-f6a273b-8ab46ff (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. Player login

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/T2a2mJif

_Add any additional information below._
Doesnt happen everytime a player logs in, its random

**Comment by DevLeoko** [comment]
Same as #249
