### ISSUE TITLE
[API Question] Undo Punishment from API?

### ISSUE THREAD

**Issue by JavaGuy12** [DevLeoko/AdvancedBan#252]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Latest
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord
 
_What server version (/version) are you using?_
_(API Question)_

_Please provide the EXACT steps required to reproduce the problem..._
N/A

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
n/a

_Add any additional information below._

Hi!
I know this may seem dumb, but how do I undo a punishment from the API? I can see how to make one, yet not how to undo. Thanks!

**Comment by DevLeoko** [comment]
There is a delete method in the punishment class 
https://github.com/DevLeoko/AdvancedBan/blob/master/src/main/java/me/leoko/advancedban/utils/Punishment.java#L182

**Comment by JavaGuy12** [comment]
Thanks!
