### ISSUE TITLE
MySQLSyntaxErrorException

### ISSUE THREAD

**Issue by Sandtato** [DevLeoko/AdvancedBan#253]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBan 2.2.0-SNAPSHOT
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single Server 
 
_What server version (/version) are you using?_
Paper version git-Paper-366 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. Enable SQL Database option and restart server.
2. Put in details in MySQL.yml and restart again.
3. Wait for AdvancedBan to start up and display the message stating to see latest.log.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/VWn031cN

_Add any additional information below._

Was working with previous version installed (v2.1.5-RELEASE). This build was installed to test a possible fix for #249. Cannot confirm if this is happening with regular MySQL as my server uses MariaDB.

**Comment by DevLeoko** [comment]
http://v.skamps.eu:8080/job/AdvancedBanV2/50/ sorry seems like the dev that changed the SQL Layout only tested it on HyperSQL.
This changes should fix that :)

**Comment by Sandtato** [comment]
Working now, keep up the great work!
