### ISSUE TITLE
Startup Log Error

### ISSUE THREAD

**Issue by Exophobias** [DevLeoko/AdvancedBan#257]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
v 2.2.0 Snapshot
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single Server
 
_What server version (/version) are you using?_
Latest Spigot 1.12.2

_Please, provide the EXACT steps required to reproduce the problem..._
1. Start the server
2. Check the startup log in the console or in latest.log

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._ (Hastebin is better!)
https://hastebin.com/axazabalir.css

_Add any additional information below._
No idea what it's doing this, I assume its because of it's a snapshot/dev version.

**Comment by A248** [comment]
It seems your hastebin link is broken.

Please also take a look at #203 in case this is a duplicate.
