### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BrettplayMC** [DevLeoko/AdvancedBan#26]
What version of AdvancedBan ( /AdvancedBan ) are you using?
10.3
What kind of server do you have ( Bungeecord/single server )?
Single
What server version (/version) are you using?
1.8.8
Please provide the EXACT steps required to reproduce the problem... 1. 2. 3.
1. Install on server
2. Try to join?
3. Get "Disconnected error"
Any error/log post it through pastebin.com and link it here.
http://pastebin.com/p6Hg39yP
Add any additional information below.

**Comment by dutchy1001** [comment]
You might need to update to V2.0.5, I dont think fixing an issue in an old version is going to happen.

**Comment by BrettplayMC** [comment]
Ok. :/  This just happened today so...

**Comment by BrettplayMC** [comment]
Also I would like to update but it is too complex and hard for me to understand.  I would need someone to do it for me. :/

**Comment by dutchy1001** [comment]
Pm me on spigot and I can help you there to update

**Comment by BrettplayMC** [comment]
Ok! 💃 
Name?

**Comment by dutchy1001** [comment]
ya really need to ask me name in spigot????

**Comment by BrettplayMC** [comment]
nvm xd

**Comment by dutchy1001** [comment]
This has been sorted
