### ISSUE TITLE
Small Error

### ISSUE THREAD

**Issue by ColorsASD** [DevLeoko/AdvancedBan#260]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBan v2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single server.
 
_What server version (/version) are you using?_
PaperSpigot v1.12.2 b1587

_Error:_
 1. Don't work "@" MessagesLayouts but work "#" TimeLayouts.
 2. Update MySQL table utf8_general_ci for special character. (I know how change, but others it may be problematic.)

**Comment by DevLeoko** [comment]
How do you use the command with the timelayout?
