### ISSUE TITLE
Punishments not being logged

### ISSUE THREAD

**Issue by ASHER04** [DevLeoko/AdvancedBan#261]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
Craftbukkit
 
_What server version (/version) are you using?_
This server is running CraftBukkit version git-Spigot-f6a273b-a639ae4 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. Ban or punish someone
2. Doesn't log it into bans.yml or any .yml file EXCEPT it does log it too the folder Data > Storage.log
3. Than when the server restarts the bans aren't even in the Storage.log file

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No, nothing is sent in console.

_Add any additional information below._
You can respond here or help me on discord ThisIsAwesome55#8910 , either works for me, whatever is easiest for you. ALSO I had some help from another player and he said to enable MySQL but it has made no difference.

**Comment by DevLeoko** [comment]
Please check your console again for any kind of error. Especially at the start and shutdown

**Comment by ASHER04** [comment]
> Please check your console again for any kind of error. Especially at the start and shutdown

Alrighty, here is it loading in https://pastebin.com/3zPY07NP. I am going to update to the most recent version right after I post this if this fixes my problems I will tell you here.

**Comment by Beelzebu** [comment]
Hi @ASHER04 can you please enable debug in the config, then try to reproduce the bug and look for errors in console?

**Comment by ASHER04** [comment]
So I did that. Restarted my server, nothing unusual, I than temp banned my alt for 1minute to test and nothing unusual there. They are still not being logged into a ban.yml or anything.

**Comment by ASHER04** [comment]
Should I switch plugins? @Beelzebu

**Comment by DevLeoko** [comment]
Should be solved with the newest version: https://www.spigotmc.org/resources/advancedban.8695/update?update=321631
