### ISSUE TITLE
Maven repo?

### ISSUE THREAD

**Issue by eliteSchwein** [DevLeoko/AdvancedBan#262]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.5
 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.13

Hey There is there an Maven Repo aviable? That would be awesome :-D

**Comment by Beelzebu** [comment]
There is no official maven repo for the plugin, you'll need to compile it by yourself and install it to your local maven repo. I have version 2.1.6-SNAPSHOT in my nexus repo https://repo.nifheim.net/repository/nifheim-public/
