### ISSUE TITLE
config.yml encoding?

### ISSUE THREAD

**Issue by Baw-Appie** [DevLeoko/AdvancedBan#263]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single
 
_What server version (/version) are you using?_
1.12.2

_Please provide the EXACT steps required to reproduce the problem..._
1. load plugin and stop the server.
2. set config as korean
3. broken config file

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any additional information below._

It seems that the CONFIG file is saved in the system encoding when it is saved.
Because of this, if there is Korean in the CONFIG file, the encoding will not be done correctly and the encoding of the file will be broken.

**Comment by Baw-Appie** [comment]
![default](https://user-images.githubusercontent.com/15670271/48823441-32f2ea00-eda4-11e8-9ca9-6f67ac133685.png)

**Comment by Beelzebu** [comment]
Try changing the encoding in your text editor, by default the server tries to load the config files in utf8

**Comment by Baw-Appie** [comment]
When the server is loaded, the file's encoding automatically changes to euc-kr.

**Comment by Beelzebu** [comment]
Try adding `-Dfile.encoding=UTF-8` to the startup flags

**Comment by Baw-Appie** [comment]
> `-Dfile.encoding=UTF-8`시작 플래그에 추가해보십시오.

Doing so creates a problem with console encoding.

**Comment by Baw-Appie** [comment]
> Try adding `-Dfile.encoding=UTF-8` to the startup flags

Doing so creates a problem with console encoding.
