### ISSUE TITLE
Error on api

### ISSUE THREAD

**Issue by Zekcero** [DevLeoko/AdvancedBan#264]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 R: 2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 R: single server
 
_What server version (/version) are you using?_
R: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. I enter
2. banned
3. and the error occurs

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
R: https://pastebin.com/Sx7VFtiL

_Add any additional information below._
R: I made a plugin and integrate the api of this plugin and when the ban occurs that error.

**Comment by Beelzebu** [comment]
Can you please show us your code?

**Comment by realhopedev** [comment]
### Sorry for the Late Reply!

There's currently an issue with offline-servers and mysql, and might be fixed later on.

If your Server is not cracked, reply to this Message.

**Comment by realhopedev** [comment]
There's currently an issue with offline-servers and mysql, and might be fixed later on.

If your Server is not cracked, reply to this Message.

**Comment by DevLeoko** [comment]
Should be solved with the newest version: https://www.spigotmc.org/resources/advancedban.8695/update?update=321631
