### ISSUE TITLE
TimeManager should be static

### ISSUE THREAD

**Issue by james090500** [DevLeoko/AdvancedBan#265]
When creating a new ban the API says use 
`TimeManager.getTime()`
but this can't be used as TimeManager.getTime() cannot be access staticly and creating a new instance for just the timemanger seems a bit pointless.

**Comment by Beelzebu** [comment]
That method is already static https://github.com/DevLeoko/AdvancedBan/blob/08dc4e0abc744ca0f831e4c0ff0f63baa2d71258/src/main/java/me/leoko/advancedban/manager/TimeManager.java#L11

**Comment by james090500** [comment]
Sorry, I should be more specific. This is on the development branch

**Comment by Beelzebu** [comment]
Development branch is not documented yet, to get instance of TimeManager in use you will need to use this: `AdvancedBan.get().getTimeManager()`

**Comment by james090500** [comment]
Perfect, thank you. 

For future reference, how should I specify im on a different branch?

**Comment by Beelzebu** [comment]
Well, the issue template has the `AdvancedBan Version` section where you should tell us the version of the plugin that you're using

**Comment by james090500** [comment]
Alright cheers. I was hoping to just raise issues under different branches
