### ISSUE TITLE
MySQL Database Error

### ISSUE THREAD

**Issue by zachrocks22** [DevLeoko/AdvancedBan#269]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBan v2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Multiple Servers via MYSQL but not Bungee.
 
_What server version (/version) are you using?_
1.13.2-PAPER

_Please provide the EXACT steps required to reproduce the problem..._
1. Load AdvancedBan
2. Configure MySQL.
3. Wait 5 minutes or more.
4. Have a player join/leave.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
[https://pastebin.com/raw/H3P6XrLN](url)

_Add any additional information below._
It's connected via MySQL to a local database.

**Comment by AeSix** [comment]
It would be helpful if you were to copy the error from the log file that it says to in that error.  Also, I'm not certain how you managed to mangle that link, but it takes me to an empty issue page on this tracker.  

If you've figured out the issue, update the ticket and close it please.   If you've not, update the ticekt with all the applicable infor from the log file.
