### ISSUE TITLE
bug ? no perms

### ISSUE THREAD

**Issue by piesio98** [DevLeoko/AdvancedBan#27]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
 2.0.5

_What kind of server do you have (`Bungeecord/single server`)?_
 
 bunge but plugin only on a main server

_What server version (/version) are you using?_

protocol hack 1.7-1.8

_Please provide the EXACT steps required to reproduce the problem..._
1. just type any command in a game
2. aaand no perms
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

no errors

_Add any aditional information below._

Changes in config and in messages files are only visible in console.
http://scr.hu/1j5s/nv337

http://scr.hu/1j5s/xv4rj

**Comment by dutchy1001** [comment]
> What server version (/version) are you using?
protocol hack 1.7-1.8

Still doesnt say what server version you use, is it 1.7 or is it 1.8?

If your only using the plugin only on your main server then I presume you have it there installed and not on your bungee server.
Were are the permissions added; Your permission plugin or in the bungee config?

Messages are beside the point atm as you need to be able to use the permissions first.

**Comment by piesio98** [comment]
version is 1.7, now i see plugin is in bungee server and in main server but permissions are added in main server.

**Comment by dutchy1001** [comment]
due to the plugin in both servers it will not work as it should, either in the bungeecord server or in a spigot/bukkit server.
We recommend the use in the bungee server so it covers each server in your network (with the permissions added to the bungeecord file). 
If only used in 1 server then players can still access the other servers in your network.

**Comment by dutchy1001** [comment]
some input of the OP would be nice...

**Comment by dutchy1001** [comment]
closed due to no further input from OP
