### ISSUE TITLE
update 1.13.2

### ISSUE THREAD

**Issue by successed** [DevLeoko/AdvancedBan#272]
update 1.13.2

**Comment by xknat** [comment]
@successed last commit was Nov 15, 2018, i think its best to look for a alternative.
see https://www.spigotmc.org/resources/bungeesuite-bans.74/
or https://www.spigotmc.org/resources/maxbans-plus.41392/

**Comment by DevLeoko** [comment]
Neither of those plugins has official 1.13 support and both are just as "discontinued" as AdvancedBan is. 
If AdvancedBan does not work for you, feel free to try out some different plugin but there are currently over 500 Servers running with AdvancedBan on 1.13 so I assume it should work just fine (most of them on 1.13.2)

If you'd report any specific issue you have with AdvancedBan on 1.13 you might actually get some help. (try our support discord: https://discord.gg/ycDG6rS)
