### ISSUE TITLE
MYSql Not Kicking

### ISSUE THREAD

**Issue by TaZeDeveloper** [DevLeoko/AdvancedBan#276]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single
 
_What server version (/version) are you using?_
1.12.2-R0.1-SNAPSHOP

_Please provide the EXACT steps required to reproduce the problem..._
1. Make sure you have a SQL Server connected to your plugin
2. ban someone on another server
3. There still on there until they leave

_Add any additional information below._
Just saying can you maybe add it so they get kicked when they're updated on to the database.

**Comment by realhopedev** [comment]
Check latest update

**Comment by A248** [comment]
I cannot reproduce this error.
