### ISSUE TITLE
Error MySQL

### ISSUE THREAD

**Issue by LeoCrish** [DevLeoko/AdvancedBan#280]
Version • 2.1.5-RELEASE

BungeeCord & spigot
 
Spigot 1.12.2

_Please provide the EXACT steps required to reproduce the problem..._
1. Connect the plugin to a MySQL database
2. Ban a player
3. You will get an error

https://pastebin.com/rQPUneGF

**Comment by realhopedev** [comment]
### Sorry for the Late Reply!

There's currently an issue with offline-servers and mysql, and might be fixed later on.

If your Server is not cracked, reply to this Message.

**Comment by A248** [comment]
Duplicate of #231 .
