### ISSUE TITLE
Error MySQL

### ISSUE THREAD

**Issue by LeoCrish** [DevLeoko/AdvancedBan#281]
Version • 2.1.5-RELEASE

BungeeCord & spigot
 
Spigot 1.12.2

1. Connect the plugin to a MySQL database
2. Ban a player
3. You will get an error

https://pastebin.com/rQPUneGF

MySQL.yml - https://pastebin.com/yrJWyDcq

Config.yml - https://pastebin.com/LDJ3hRPg

**Comment by Elikill58** [comment]
I have exactly the same problem

**Comment by A248** [comment]
Duplicate of #280
