### ISSUE TITLE
How to get webpanel download

### ISSUE THREAD

**Issue by nicadee** [DevLeoko/AdvancedBan#282]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
 2.1.5
_What kind of server do you have (`Bungeecord/single server`)?_
 
 Bungeecord
_What server version (/version) are you using?_
Bungeecord 1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1.
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any additional information below._

**Comment by realhopedev** [comment]
Here: https://github.com/mathhulk/advancedbans

**Comment by A248** [comment]
The official webpanel is not available for the time being but you may use mathhulk's project as linked.
