### ISSUE TITLE
Getting multiple notify messages when punishing players

### ISSUE THREAD

**Issue by firstto1** [DevLeoko/AdvancedBan#284]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 3.0.1-SNAPSHOT
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.14.4

_Please provide the EXACT steps required to reproduce the problem..._
1. Run any command that notifys players with ab.X.notify (X being tempban, ban, kick, or etc.) permission.
2. All players with the notify permission will get notified 3 times.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
Console error?: https://pastebin.com/SZWmR5p9
Example of what it looks like in in-game chat: https://i.imgur.com/Ir8JzFn.png

_Add any additional information below._

**Comment by realhopedev** [comment]
Could you send the exact Console output from the Moment you've banned someone until the end of the Log?

**Comment by firstto1** [comment]
It just shows me running the ban command, even with debug set to true.

**Comment by DevLeoko** [comment]
Should be solved with the newest version: https://www.spigotmc.org/resources/advancedban.8695/update?update=321631
