### ISSUE TITLE
Configure command aliases

### ISSUE THREAD

**Issue by agent188** [DevLeoko/AdvancedBan#286]
Sometimes you want to divide the bans into global (BungeeCord) and local (server), and in AdvancedBan there is no way to change commands, for example, I would like to be able to change:
ban -> gban
warn -> gwarn
kick -> gkick

**Comment by realhopedev** [comment]
Use a Alias Plugin for that

**Comment by agent188** [comment]
can you give a link to the plugin?

**Comment by agent188** [comment]
if there is Alias, then the input of the / ban command will again refer to AdvancedBan

**Comment by realhopedev** [comment]
Then add a ban alias to refer to /advancedban:ban

**Comment by agent188** [comment]
and where, again, can be banned? In the BungeeCord config?

**Comment by realhopedev** [comment]
How about you make your own Plugin with your desired Commands and use the AdvancedBan API? That seems to be a good alternative

**Comment by realhopedev** [comment]
I even did it myself, pretty easy to understand

_Gesendet von meinem FIG-LX1 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by agent188** [comment]
I'm not a developer :(

**Comment by agent188** [comment]
I was able to do this with two alias plugins

**Comment by realhopedev** [comment]
Alright! If your Issue has been resolved, please close this Thread :wink:

**Comment by realhopedev** [comment]
I might do a fork for your Suggestion

**Comment by agent188** [comment]
No, I still want to offer the idea to the developers, a couple of things still do not work through aliases: namely, punching nicknames through Tab

**Comment by realhopedev** [comment]
Then you should probably suggest it on the Skamps Dev-Team Discord [here](https://discordapp.com/invite/ycDG6rS)

**Comment by A248** [comment]
You can approach this yourself in 2 ways:

1. **commands.yml** - not sure if this is in BungeeCord, but it's definitely in Spigot
2. Make your own plugin. You will need to register the commands, listen to the commands, and listen for tab completions if you also want tab complete to function properly.

**Comment by A248** [comment]
More information and examples on the **commands.yml** may be found [here](https://bukkit.gamepedia.com/Commands.yml#Alias_Examples)

**Comment by DevLeoko** [comment]
We cannot dynamically change command names afaik, so this feature request is not possible.
See the answers above for alternative ways to achieve that.
