### ISSUE TITLE
Publish AdvancedBan to Alternate Platform

### ISSUE THREAD

**Issue by cnluminous** [DevLeoko/AdvancedBan#287]
Hello, Author of Advanced Ban! I am a player from China. I hope to be able to publish this plug-in to the GIT hosting platform in China and follow GPLv3. I hope to get your authorization. Thank you!

**Comment by cnluminous** [comment]
sorry,my English is not very good.

**Comment by realhopedev** [comment]
Any Reason why you wan't Publish it on there?

**Comment by A248** [comment]
@DevLeoko you should see this.

**Comment by DevLeoko** [comment]
AdvancedBan is published under GPL 3.0 which allows for distribution as long as the other criteria in the license are met.
https://github.com/DevLeoko/AdvancedBan/blob/master/LICENSE.md
