### ISSUE TITLE
Error in the console

### ISSUE THREAD

**Issue by Skeec54** [DevLeoko/AdvancedBan#288]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
  AdvancedBan v2.1.5-RELEASE

_What kind of server do you have (`Bungeecord/single server`)?_
 Single server
 
_What server version (/version) are you using?_
1.14.4

_Please provide the EXACT steps required to reproduce the problem..._
its a Console Error

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/icTvuBmC

_Add any additional information below._
Console Error:
[Mon, 2. Sep 2019 18:11:54 CEST INFO] [AdvancedBan] An unexpected error has ocurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
[Mon, 2. Sep 2019 18:11:54 CEST ERROR] Could not pass event AsyncPlayerPreLoginEvent to AdvancedBan v2.1.5-RELEASE

**Comment by realhopedev** [comment]
Is your Server cracked?

**Comment by Skeec54** [comment]
> Is your Server cracked?

Its Online/Premium

**Comment by realhopedev** [comment]
This issue mostly happens with offline-mode Servers. We will look further into it

**Comment by A248** [comment]
Duplicate of #203 .

I believe the bug is unrelated @realhopedev , please see that issue for more info.
