### ISSUE TITLE
MUTE wont work but BAN and KICK works perfect

### ISSUE THREAD

**Issue by darkjoya** [DevLeoko/AdvancedBan#289]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single server
 
_What server version (/version) are you using?_
1.14.4 paper - Build 186

_Please provide the EXACT steps required to reproduce the problem..._
1. i tried tempmute a guy '/temomute xplayer 1h swear'
2. server says 'xplayer was successfully muted'
3. then xplayer still writing chat and all players see his text.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
there is no errors in console

_Add any additional information below._
ban and kick works perfect but mute and tempmute didnt work. i tried both online server and offline server. it changed nothing. i tried debug mode and still 0 errors.

**Comment by realhopedev** [comment]
It seems like a Plugin is bypassing the Mutes, could you try to disable _all_ plugins temporarily to check if it still occurs?

**Comment by darkjoya** [comment]
I did this and works perfect. And i found the plugin. Its EssentialsX! Which this plugin is servers core plugin. What can i do to fix this?

**Comment by realhopedev** [comment]
If you are using EssentialsXChat in particular, you could remove that

**Comment by darkjoya** [comment]
Im not using EssXChat. yesterday when i trying one by one only main EssX loaded in server. Im using ChatControlPro for chat plugin. But i tried CCP first and didnt broke advancedban.

**Comment by darkjoya** [comment]
Well i find out ChatControlPro doing this. Now i report issue ChatControl's github.
