### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by 6u5t4v** [DevLeoko/AdvancedBan#290]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single server
 
_What server version (/version) are you using?_
Paper version git-Paper-187 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. It just appears every now and again in the console ?

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/uUYZqTAm

_Add any additional information below._

**Comment by realhopedev** [comment]
Is your Server non-premium/cracked?

**Comment by 6u5t4v** [comment]
It is premium

**Comment by realhopedev** [comment]
You are, of course using mysql right?

**Comment by 6u5t4v** [comment]
yes

**Comment by A248** [comment]
Duplicate of #203
