### ISSUE TITLE
Prevent API Version warnings

### ISSUE THREAD

**Issue by ProDash1998** [DevLeoko/AdvancedBan#294]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
 1.14.4
_What server version (/version) are you using?_

_Please provide the EXACT steps required to reproduce the problem..._
none
_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

[21:43:30 WARN]: Plugin AdvancedBan v2.1.5-RELEASE does not specify an api-version.

_Add any additional information below._

i cant download version supported 1.14.4

**Comment by TheFlagCourier** [comment]
The plugin supports 1.14, it just does not declare an API so that it doesn't loose backwards compatibility with <= 1.12. Unless you have minimum-api set in bukkit.yml, this shouldn't prevent the plugin from loading - it's just a warning.

**Comment by JustBru00** [comment]
This can be prevented by adding `api-version: 1.13` to the plugin.yml file. Versions before 1.13 do not check for the `api-version` and will ignore it.

**Comment by A248** [comment]
This isn't a bug. It's just a warning message. Don't worry, it does not break anything.
