### ISSUE TITLE
Permission ladder

### ISSUE THREAD

**Issue by SemperEtAnte** [DevLeoko/AdvancedBan#295]
I would like to ask to add a ladder of rights. Something like:
global admin -> admin -> moder -> (etc.)
From left to right they can punish, from right to left - no. Example: admin cannot punish global admin, and global can punish admin
Of course, the console is an exception banning all living things =)

**Comment by A248** [comment]
Note: Feature was also requested by Discord user LukePlyz
#7958 on 29 November.

**Comment by DevLeoko** [comment]
This feature has been implemented in our newest release: https://www.spigotmc.org/resources/advancedban.8695/update?update=321631
