### ISSUE TITLE
Bug with the API

### ISSUE THREAD

**Issue by Cintox** [DevLeoko/AdvancedBan#296]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single Server
 
_What server version (/version) are you using?_
1.8.8

I implemented the API to my Plugin but now it says "the Constructer(...) is undefined.
Here's my code: 
new Punishment(t.getName(), UUIDManager.get().getUUID(t.getName()), "Hacking", p.getName(), PunishmentType.BAN, TimeManager.getTime(), TimeManager.getTime() + dur, 0, -1).create();

**Comment by A248** [comment]
The constructor is Punishment(String, String, String, String, PunishmentType, long, long, **String**, int).

Your second-to-last argument should be a `String` object; you can just use `null`. Fixed code:
```java
new Punishment(t.getName(), UUIDManager.get().getUUID(t.getName()), "Hacking", p.getName(), PunishmentType.BAN, TimeManager.getTime(), TimeManager.getTime() + dur, null, -1).create();
```
