### ISSUE TITLE
Add Ban-Exempt IP, similarly to Ban-Exempt Players

### ISSUE THREAD

**Issue by Nogapra** [DevLeoko/AdvancedBan#300]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Advancedban 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
Waterfall (Build 309)/  PaperMC (Build 26)
 
_What server version (/version) are you using?_
Paper version git-Paper-26 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

Feature request ?
Added an option to the config.yml file to exclude an IP address from the BAN system

**Comment by DevLeoko** [comment]
The "ExemptedPlayers" config section also accepts IP addresses
