### ISSUE TITLE
WarnActions issuing before they should

### ISSUE THREAD

**Issue by SiuanSong** [DevLeoko/AdvancedBan#305]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single
 
_What server version (/version) are you using?_
Paper version git-Paper-243 

_Please provide the EXACT steps required to reproduce the problem..._
1.  Tempwarn a player 
2. Tempwarn them again within 30 days
3.  Some players receive an auto-ban punishment after only 2 warns instead of 3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No errors in console log

_Add any additional information below._
I have an ongoing issue with multiple players where they are receiving auto-punishments for warns before even reaching the required amount of warnings.  Players should receive a ban after 3 warnings, but it's issuing the ban after 2 warnings, saying that they received 3.

![notepad++_B5yGsvsU9T](https://user-images.githubusercontent.com/28202890/73426638-dde52900-4302-11ea-8866-8e0ed36438a7.png)
![javaw_AFVoHeYDGy](https://user-images.githubusercontent.com/28202890/73426641-dfaeec80-4302-11ea-8d0c-67b1761bc023.png)

**Comment by DevLeoko** [comment]
Should be solved with the newest version: https://www.spigotmc.org/resources/advancedban.8695/update?update=321631
