### ISSUE TITLE
No Advancedban Table found

### ISSUE THREAD

**Issue by RTCFlyer** [DevLeoko/AdvancedBan#31]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Latest Version
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single 
 
_What server version (/version) are you using?_
1.10.2 (updating soon)

_Please provide the EXACT steps required to reproduce the problem..._
1. get a MySql database with the AB website interface.
2. Try to create a acount with the AB website.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No error logs are shown

_Add any aditional information below._
When I try to create the acount with the AdvancedBan website interface it gives me a error saying it can not find the AB tables. I looked in my SQL database and the plugin is not generating the tables.

**Comment by dutchy1001** [comment]
How did you setup your MySQL?
What permissions does the MySQL db have?
Have you double checked the login name/password?

**Comment by RTCFlyer** [comment]
My MySql is setup through bisecthosting.
The permissions should all be fine considering BanManager was able to create tables. And lots of other plugins.
Yes I have double checked the login name/password.

**Comment by dutchy1001** [comment]
I would suggest to renew your password and DB name as the mail that was send out contained your credentials for it (not that I would, but you dont know how many others got that mail).

What I think happens here is that the host doesnt use the default 3306 port which therefor wont let AdvancedBan create the tables. 
In a coming update (no ETA yet) this will change so you can set the port to your own liking.

**Comment by RTCFlyer** [comment]
Any solution to this now, I would really like to set this up. Plus is advancedban is not even accepting my credentials then how am I suppose to use the plugin fully.

**Comment by RTCFlyer** [comment]
I got it! Okay, so turns out the MySql Config file was not loading in the plugin files. I did a few server restarts and I finally got the file. The port works fine! Thanks for the help anyway.

**Comment by dutchy1001** [comment]
Thx for letting me know. I hope it will go smooth from here on.

**Comment by dutchy1001** [comment]
**PS. dont forget to change the credentials**

**Comment by RTCFlyer** [comment]
I have already done this :) Thanks again, also anyway to import old bans from the data?

**Comment by dutchy1001** [comment]
Unfortunately not, this was also an issue from the last update, I hope in the next update this will be added., so dont delete your old DB yet.

**Comment by RTCFlyer** [comment]
So, it has been working so far, now I am getting this error when I try to /warn someone.
09.01 22:21:43 [Server] INFO RTCFlyer issued server command: /warn test test
09.01 22:21:43 [Server] INFO AdvancedBan <> Skipped executing SQL because there is no connection to the MySQL-Server please restart the server!
09.01 22:21:43 [Server] INFO AdvancedBan <> Skipped executing SQL because there is no connection to the MySQL-Server please restart the server!
09.01 22:21:43 [Server] INFO AdvancedBan <> Skipped executing SQL because there is no connection to the MySQL-Server please restart the server!
09.01 22:21:43 [Server] WARN [AdvancedBan] Plugin AdvancedBan v2.0.5 generated an exception while executing task 145
09.01 22:21:43 [Server] INFO java.lang.NullPointerException
09.01 22:21:43 [Server] INFO at me.leoko.advancedban.utils.Punishment.create(Punishment.java:103) ~[?:?]
09.01 22:21:43 [Server] INFO at me.leoko.advancedban.manager.CommandManager$1.run(CommandManager.java:123) ~[?:?]
09.01 22:21:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.jar:git-Spigot-de459a2-51263e9]
09.01 22:21:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.10.jar:git-Spigot-de459a2-51263e9]
09.01 22:21:43 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
09.01 22:21:43 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
09.01 22:21:43 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by dutchy1001** [comment]
when using a name that doesnt have a real UUID it will error, this will be fixed in a next update

**Comment by dutchy1001** [comment]
Edited the message as the bold was hard to read and missing the last sentence. Use spaces between sections and pastebin for logs is way better to read.

Stillsomething with your connection to the MySQL is not set properly.
