### ISSUE TITLE
AdvancedBan SQL Error

### ISSUE THREAD

**Issue by TheJoeCoder** [DevLeoko/AdvancedBan#311]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord (Waterfall)
 
_What server version (/version) are you using?_
This server is running Waterfall version git:Waterfall-Bootstrap:1.15-SNAPSHOT:4ecb3f3:309 by md_5

_Please provide the EXACT steps required to reproduce the problem..._
1. Log in ONCE
2. Second time you log in it works

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/vaF5K67E

_Add any additional information below._
I'm using mysql.

**Comment by DevLeoko** [comment]
I am sorry, I'm not able to help with this issue as critical information is missing from the log file.
The latest version (2.1.7) includes this information. So please update and feel free to reopen this issue if the bug persists.
