### ISSUE TITLE
permissions not working 

### ISSUE THREAD

**Issue by owlman5126** [DevLeoko/AdvancedBan#312]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
spigot on 1.14.4

_Please provide the EXACT steps required to reproduce the problem..._
1.type /ban test
2. server sends back the default you do not have the perms message

_Add any additional information below._
I am running mineOS if that helps

**Comment by DevLeoko** [comment]
Q: I want to use this with Bungeecord, where do I install the plugin
A: Only on the Bungeecord and not on the single spigot servers

Q: I'm using AdvancedBan on BungeeCord, but permissions aren't working, even if players are opped!

A: You may be confused between BungeeCord versus Spigot permissions.

Spigot Perms
* Configured on each Spigot server, can be managed with a permissions plugin.
* Used by Spigot plugins.
* Includes OP, which grants access to all permissions.

Bungee Perms
* Configured on the BungeeCord proxy.
* Used by BungeeCord plugins.
* There is no such thing as "OP".

OP is Spigot-server only. Permissions are separated between BungeeCord permissions (which BungeeCord plugins use) and Spigot permissions (which Spigot plugins use, and which OP is related to)

If you install AdvancedBan on BungeeCord, you will need to grant your moderators BungeeCord permissions. AdvancedBan, if installed on BungeeCord, cannot detect Spigot permissions.
If you don't use BungeeCord, don't worry about this.

**Comment by owlman5126** [comment]
ok thanks but that does not help. I have given the player the perms to issue the /ban command but when they issue the command it says that they don't have permission to do that.

**Comment by DevLeoko** [comment]
What permissions system so you use? Where is AdvancedBan installed? And which permission do you give the player?

**Comment by owlman5126** [comment]
installed on bungeecord, I am using luckperms bungeecord version, I gave them ab.all

**Comment by DevLeoko** [comment]
Is ab.all enabled in the config?

**Comment by owlman5126** [comment]
yes

**Comment by DevLeoko** [comment]
I am a bit confused by your answer. There are no settings for other commands.
I am talking about the setting: `EnableAllPermissionNodes: false` in the `config.yml`, it should be set to `true`

**Comment by owlman5126** [comment]
sorry I thought that you where talking about the bungee config :)

**Comment by owlman5126** [comment]
still not working tho :(

**Comment by owlman5126** [comment]
seams to of fixed it self 👍

**Comment by owlman5126** [comment]
Thanks a lot for the help
