### ISSUE TITLE
/tempipban not working

### ISSUE THREAD

**Issue by Matocolotoe** [DevLeoko/AdvancedBan#313]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.1.7 (latest)
 
_What kind of server do you have (`Bungeecord/single server`)?_
Single server
 
_What server version (/version) are you using?_
Spigot 1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
Just run the `/tempipban` command. Nothing happens, no message appears.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
Nothing.

**Comment by Aurelien30000** [comment]
Confirmed on Paper 1.15.2 (single) and BungeeCord (proxy), nothing occurs, with or without correct arguments :)

**Comment by DevLeoko** [comment]
Thanks for the report. This bug actually got fixed in the latest dev build: https://github.com/DevLeoko/AdvancedBan/actions/runs/67268996

**Comment by Matocolotoe** [comment]
Alright, thank you very much ! :)
