### ISSUE TITLE
Server was destroyed because AdvancedBan was crushed! [Problem solved]

### ISSUE THREAD

**Issue by Oloxus2008** [DevLeoko/AdvancedBan#314]
I downloaded this plugin a few days ago. My server needed a slightly better plugin to edit the look of the ban. At the very beginning it was obvious that the plugin did not work - nobody could be banned, silenced or warned! The next day the server did not turn on - I was still receiving information that the server / plugins / AdvancedBan.jar file was not responding. I can't remove the plugin either. I only lost 3 hours of time in which I designed information styles and 2 years of work on the server, over 2000 players and a lot of cash on server RAM, domain, etc. PLEASE REPAIR IT AS FAST, BECAUSE THE SERVER IS 3 HOURS ALREADY OFF !!!

**Comment by DevLeoko** [comment]
I'm sorry to hear that you had such issues while setting up AdvancedBan.

But we can't really provide you with any support unless you include useful information into your bug report. Using the *mandatory* issue template would be a good start

**Comment by Oloxus2008** [comment]
After uninstalling the plugin and turning on the server without it and running the plugin, the server went quite well. The plugin has been configured.
The problem has apparently been resolved! : D
Thank you for your help, because your comment made me try to remove the plugin via FTP and edit it again!
I use jusz plugin for 1 day and the plugin never got damaged: D
Thank you for your help.

**Comment by DevLeoko** [comment]
I am convinced this had nothing to do with AdvancedBan. And the issue got resolved because you restarted your server not because you removed AdvancedBan. But nevermind, glad your issue is resolved.
