### ISSUE TITLE
Geyser Floodgate Support

### ISSUE THREAD

**Issue by benrobson** [DevLeoko/AdvancedBan#317]
Hey,
I am looking to use AdvancedBan on my Server, but I also want to use Geyser's FloodGate in conjunction. I've gotten everything to work but when logging in it throws a `[AdvancedBan] Failed to fetch your UUID`.
Would there be a workaround to this to make this operational to support both clients?

**Comment by DevLeoko** [comment]
Not sure how FloodGate works. You could try to change AdvancedBan's UUID Fetcher settings.
For example force internal fetching:
```YAML
UUID-Fetcher:
  Dynamic: false
  Enabled: true
  Intern: true
```
or simply disable the UUID fetcher so AdvancedBan uses names

**Comment by benrobson** [comment]
Geyser is a bridge/proxy allowing you to connect to Minecraft: Java Edition servers with Minecraft: Bedrock edition. Floodgate is an addon to Geyser which is a hybrid mode plugin to allow for connections from Geyser to join online mode servers.
More information can be found here: https://github.com/GeyserMC/Geyser/wiki/Floodgate

I will try what you have suggested, but if I simply disable the UUID fetcher wouldn't that make it able for players to change username and log back in?

**Comment by DevLeoko** [comment]
Yes, but there is not really any other way to do this.
You can:
a) Just use usernames
b) Use the UUID provided by the Server implementation
c) Fetch a UUID from any REST API based on the username

AdvancedBan supports all three of these options

**Comment by ZandercraftGames** [comment]
So is this issue resolved with the latest commits in a way that it doesn't validate floodgate user's uuids through online verification, or do we still need to disable online UUID verification with them?

**Comment by DevLeoko** [comment]
I didn't do the fix, but I'd guess you would need to set the uuid fetcher to use internal fetching.
```YAML
UUID-Fetcher:
  Dynamic: false
  Enabled: true
  Intern: true
```

**Comment by ZandercraftGames** [comment]
Okay. Just a suggestion though, maybe set it up in a way that catches when a user joins via it, as it is a plugin. You can catch the event of people joining through floodgate/geyser and then ignore online UUID checking for them and only use internal UUIDs for them automatically. So that there is still the security of online UUID checking for Java Edition users, but not Bedrock where it isn't compatible.

**Comment by ZandercraftGames** [comment]
@DevLeoko I did that, I also compiled the latest commit in the dev branch. It still states "Failed to get your UUID".

**Comment by benrobson** [comment]
I also compiled from the latest in master with the latest version of both Geyser and Floodgate and still give the can't validate UUID, even with internal fetching.

**Comment by DevLeoko** [comment]
Alright, then it seems like support for Floodgate has to be added manually.
Marking this issue as a feature request.

**Comment by benrobson** [comment]
Any progress on this?
