### ISSUE TITLE
Hikari library, mysql connection improvement

### ISSUE THREAD

**Issue by tobgen** [DevLeoko/AdvancedBan#320]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.8
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungee + 5 spigot
 
_What server version (/version) are you using?_
1.15.2

_Please provide the EXACT steps required to reproduce the problem..._
1. Install AdvancedBan
2. Configure it for MySQL
3. Have the servers idle
4. Player logs in

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://paste.md-5.net/vugobumalo.sql

_Add any additional information below._
This is kinda expected if your server has been idle for the timeout value.
Hikari can solve this by keeping the connection to the database alive.
Just a thought.

**Comment by DevLeoko** [comment]
We have set "autoReconnect" to true, so in theory, it should reconnect once the connection is gone. But yes it would be a good idea to implement/use some more sophisticated MySQL (Pool) connection management. Thanks for pointing that issue out

**Comment by tobgen** [comment]
Reconnect works and does what it is suppose to do , so the issue is just "cosmetic" in the logs.

**Comment by DevLeoko** [comment]
The latest version of AdvancedBan now uses Hikari connection pooling. Thanks for the feature request 👍 
https://www.spigotmc.org/resources/advancedban.8695/update?update=335170
