### ISSUE TITLE
Get ban, ban reason by ip / uuid

### ISSUE THREAD

**Issue by qba567** [DevLeoko/AdvancedBan#321]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Stable 2.1.8
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Paper
 
_What server version (/version) are you using?_
1.15.2

Hi how to get ban and ban reason by player ip or uuid. I ve tried to do it with: me.leoko.advancedban.manager.PunishmentManager.get().getBan(uuid), but always return null

**Comment by DevLeoko** [comment]
make sure to use AdvancedBans UUIDManager to resolve a players UUID
