### ISSUE TITLE
Could not pass event AsyncPlayerPreLoginEvent to AdvancedBan v2.1.8

### ISSUE THREAD

**Issue by SteelMageE** [DevLeoko/AdvancedBan#325]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.8
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single server
 
_What server version (/version) are you using?_

1.14.4
_Please provide the EXACT steps required to reproduce the problem..._
1.I'm starting the server
2.and gives me such an error
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/ifwCB7Tw

_Add any additional information below._
I hope I wrote everything correctly!
If you need more information, write xD

**Comment by DevLeoko** [comment]
There should also be another error in AdvacnedBan's own log files. Could you post that too?
It's located in the advancedban plugin folder

**Comment by SteelMageE** [comment]
[2020-04-20-1.log](https://github.com/DevLeoko/AdvancedBan/files/4508924/2020-04-20-1.log)

**Comment by DevLeoko** [comment]
Yes, thank you.
Seems like this related to #320, we will look into it, thanks for the report

**Comment by DevLeoko** [comment]
This issue should be fixed in the latest version of AdvancedBan.
https://www.spigotmc.org/resources/advancedban.8695/update?update=335170
Sorry for the trouble and feel free to reopen this issue if the bug persists.
