### ISSUE TITLE
Database delete

### ISSUE THREAD

**Issue by crafter23456** [DevLeoko/AdvancedBan#331]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 The newest I think 2.18
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
Spigot 1.8.9

_Please provide the EXACT steps required to reproduce the problem..._
1. I delete the 2 PunishmentHistory and the 2 Punishments files
2. Than I recover them and add them to the server
3. But it won't work

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/zXvVXVWg

_Add any additional information below._

**Comment by DevLeoko** [comment]
This seems like an issue with your MySQL server, not AdvancedBan.
