### ISSUE TITLE
This is the translations for messages.yml

### ISSUE THREAD

**Issue by DominiKiD** [DevLeoko/AdvancedBan#334]
General:
  Prefix: "&1&lPOLICIA: &8&l»"
  NoPerms: "&4No tienes permisos para eso!"
  LayoutNotFound: "&4No hay diseño llamado %NAME%"
  # This will be the replacement for the %DURATION% variable
  TimeLayoutD: "%D%dia(s) %H%h %M%min and %S%seg"
  TimeLayoutH: "%H%hora(s) %M%min and %S%seg"
  TimeLayoutM: "%M%min y %S%seg"
  TimeLayoutS: "%S% segudos"
  FailedFetch: "&4¡No se pudo obtener el UUID de%NAME%! Consulte la consola para obtener más detalles."
Ban:
  Usage: "&4Uso &8» &8&o/ban [Nonmbre] [Razón/@Layout]"
  Done: "&4&o%NAME% &8 fue baneado|a!"
  AlreadyDone: "&4&o%NAME% &8ya fue sido baneado|a!"
  Exempt: "&8No puedes bannear a &4&o%NAME%"
  Layout:
  - '%PREFIX% &8Permanentemente baneado|a'
  - "&4Razón &8» &8%REASON%"
  - '&8POLICIA: Revise el portal web '
  Notification:
  - "&4&o%NAME% &8Baneado|a por &e&o%OPERATOR%"
  - "&8Razón: &o%REASON%"
  UndoNotification: "&e&o%OPERATOR% &8desbaneado|a &4&o%NAME%"
Ipban:
  Usage: "&4USO: &8» &8&o/banip [Name/IP] [Razón/@Layout]"
  Layout:
  - '%PREFIX% &8Permanentemente baneado|a'
  - "&4Razón &8» &8%REASON%"
  - '&8POLICIA: Revise el portal web '
  Notification:
  - "&4&o%NAME% &8Baneado|a por &e&o%OPERATOR%"
  - "&8Razón: &o%REASON%"
  IpNotCashed: "&4No hay IP guardado para %NAME%!"
Tempban:
  Usage: "&4USO: &8» &8&o/tempban [Nombre] [Xmo/Xd/Xh/Xm/Xs/#TimeLayout] [Razón/@Layout]"
  MaxDuration: "&4No puedes banear más de %MAX%seg"
  Layout:
  - '%PREFIX% &8Temporalmente baneado|a'
  - "&4Razón &8» &8%REASON%"
  - "&4Duración &8» &8%DURATION%"
  - '&8POLICIA: Revise el portal web '
  Notification:
  - "&4&o%NAME% &8Baneado|a por &e&o%OPERATOR%"
  - "&8Razón: &o%REASON%"
  - "&8&oEste Jugador Baneado|a for &e&o%DURATION%"
Tempipban:
  Usage: "&4USO: &8» &8&o/tempipban [Name/IP] [Xmo/Xd/Xh/Xm/Xs/#TimeLayout] [Razón/@Layout]"
  MaxDuration: "&4No puedes banear más de %MAX%seg"
  Layout:
  - '%PREFIX% &8Temporalmente baneado|a'
  - "&4Razón &8» &8%REASON%"
  - "&4Duración &8» &8%DURATION%"
  - '&8POLICIA: Revise el portal web '
  Notification:
  - "&4&o%NAME% &8Baneado|a por &e&o%OPERATOR%"
  - "&8Razón: &o%REASON%"
  - "&8&oEste Jugador Baneado|a for &e&o%DURATION%"
Mute:
  Usage: "&4USO: &8» &8&o/mute [Nombre] [Razón/@Layout]"
  Done: "&4&o%NAME% &8fue exitosamente silenciado|a!"
  AlreadyDone: "&4&o%NAME% &8ya esta silenciado|a!"
  Exempt: "&8No puedes silenciar &4&o%NAME%"
  Layout:
  - '%PREFIX% &8EstásPermanentemente silenciado|a'
  - "&4Razón &8» &8%REASON%"
  Notification:
  - "&4&o%NAME% &8silenciado|a por &e&o%OPERATOR%"
  - "&8Razón: &o%REASON%"
  UndoNotification: "&e&o%OPERATOR% &8desilenciado &4&o%NAME%"
Tempmute:
  Usage: "&4USO: &8» &8&o/tempmute [Nombre] [Xmo/Xd/Xh/Xm/Xs/#TimeLayout] [Razón/@Layout]"
  MaxDuration: "&4No puedes silenciar mas de %MAX%seg"
  Layout:
  - '%PREFIX% &8Tu estas silenciado por %DURATION%'
  - "&4Razón &8» &8%REASON%"
  Notification:
  - "&4&o%NAME% &8muted por &e&o%OPERATOR%"
  - "&8Razón: &o%REASON%"
  - "&8&oEste Jugador silenciado|a por &e&o%DURATION%"
Warn:
  Usage: "&4USO: &8» &8&o/warn [Nombre] [Razón/@Layout]"
  Done: "&4&o%NAME% &8fue exitosamente warned!"
  Exempt: "&8No puedes advertir a &4&o%NAME%"
  Layout:
  - '%PREFIX% &4Has recivido una warning'
  - "&4Razón &8» &8%REASON%"
  - '&8Ahora lo tienes &4&o%COUNT% &8advertencia(s) en total !'
  Notification:
  - "&4&o%NAME% &8advertido|a por &e&o%OPERATOR%"
  - "&8Razón: &o%REASON%"
Tempwarn:
  Usage: "&4USO: &8» &8&o/tempwarn [Nombre] [Xmo/Xd/Xh/Xm/Xs/#TimeLayout] [Razón/@Layout]"
  MaxDuration: "&4No puedes advertir por mas de %MAX%seg"
  Layout:
  - '%PREFIX% &4Has recivido un temporalmente-warning'
  - "&4Razón &8» &8%REASON%"
  - "&4It pasará en &8» &8%DURATION%"
  - '&8Ahora lo tienes &4&o%COUNT% &8advertencia(s) en total !'
  Notification:
  - "&4&o%NAME% &8temporalmente-advertido|a por &e&o%OPERATOR%"
  - "&8Razón: &o%REASON%"
  - "&8Esta advertencia pasará en &o%DURATION%"
Kick:
  Usage: "&4USO: &8» &8&o/kick [Nombre] [Razón/@Layout]"
  Done: "&4&o%NAME% &8fue exitosamente kicked!"
  NotOnline: "&4&o%NAME% &8no esta en linea!"
  Exempt: "&8No puedes expulsar a &4&o%NAME%"
  Layout:
  - '%PREFIX% &8Has sido expulsado|a'

  - "&4Razón &8» &8%REASON%"
  Notification:
  - "&4&o%NAME% &8Expulsado|a por &e&o%OPERATOR%"
  - "&8Razón: &o%REASON%"
UnBan:
  Usage: "&4USO: &8» &8&o/unban [Name/IP]"
  NotPunished: "&4&o%NAME% no esta baneado|a!"
  Done: "&a&o%NAME% &8fue exitosamente desbaneado|a!"
  Notification: "&e&o%OPERATOR% &8desbaneado|a &4&o%NAME%"
UnMute:
  Usage: "&4USO: &8» &8&o/unmute [Nombre]"
  NotPunished: "&4&o%NAME% No está silenciado|a!!"
  Done: "&a&o%NAME% &8fue exitosamente desilenciado!"
  Notification: "&e&o%OPERATOR% &8desilenciado &4&o%NAME%"
UnWarn:
  Usage: "&4USO: &8» &8&o/unwarn [ID]o/unwarn clear [Nombre]"
  NotFound: "&4No se pudo encontrar la advertencia #%ID%"
  Done: "&8Warn &a&o#%ID% &8fue exitosamente borrado!"
  Notification: "&e&o%OPERATOR% &8desadvertio a &4&o%NAME%"
  Clear:
    Empty: "&4&o%NAME% &8has no warnings!"
    Done: "&8Cleared &a&o%COUNT% &8warnings"
UnPunish:
  Usage: "&4USO: &8» &8&o/unpunish [ID]"
  NotFound: "&4Could not find Castigo #%ID%"
  Done: "&8Castigo &a&o#%ID% &8fue exitosamente borrado!"
Banlist:
  Usage: "&4USO: &8» &8&o/banlist <Pagina>"
  OutOfIndex: "&4No hay pagina %PAGE%!"
  NoEntries: "&4&oNo hay resultados"
  Header:
  - "%PREFIX% &8Banlist:"
  - "&4&oPlayer/IP &8| &e&oDuración &8| &8&oBaneado|a por"
  - "&4&oType &8> &8&oRazón"
  - "&8"
  Entry:
  - "&8[&e%DATE%&8]"
  - "&4%NAME% &8| &e%DURATION% &8| &8%OPERATOR%"
  - "&4%TYPE% &8> &8&o%REASON%"
  - "&8"
  Footer: "&8Page &e&o%CURRENT_PAGE% &8of &e&o%TOTAL_PAGES% &8| &8Listed bans: &e&o%COUNT%"
  PageFooter: "&8Use &e&o/banlist %NEXT_PAGE% &8to see the next page"
History:
  Usage: "&4USO: &8» &8&o/history [Name/IP] <Pagina>"
  OutOfIndex: "&4No hay pagina %PAGE%!"
  NoEntries: "&4&oCould not find the history of %NAME% :("
  Header:
  - "%PREFIX% &8History for %NAME%:"
  - "&4&oName &8| &e&oDuración &8| &8&oOperator"
  - "&4&oType &8> &8&oRazón"
  - "&8"
  Entry:
  - "&8[&e%DATE%&8]"
  - "&4%NAME% &8| &e%DURATION% &8| &8%OPERATOR%"
  - "&4%TYPE% &8> &8&o%REASON%"
  - "&8"
  Footer: "&8Page &e&o%CURRENT_PAGE% &8of &e&o%TOTAL_PAGES% &8| &8Total entries: &e&o%COUNT%"
  PageFooter: "&8Use &e&o/history %NAME% %NEXT_PAGE% &8to see the next page"
Warns:
  Usage: "&4USO: &8» &8&o/warns [Nombre] <Pagina> &4or &8&o/warns <Pagina>"
  OutOfIndex: "&4No hay pagina %PAGE%!"
  NoEntries: "&4&o%NAME% todavia no tiene advertencias"
  Header:
  - "%PREFIX% &8Advertencias para %NAME%:"
  - "&4&oName &8| &e&oDuración &8| &8&oAdvertencia de"
  - "&4&o#ID &8> &8&oRazón"
  - "&8"
  Entry:
  - "&8[&e%DATE%&8]"
  - "&4%NAME% &8| &e%DURATION% &8| &8%OPERATOR%"
  - "&4&l#%ID% &8> &8&o%REASON%"
  - "&8"
  Footer: "&8Pagina &e&o%CURRENT_PAGE% &8de &e&o%TOTAL_PAGES% &8| &8Advertencias activas: &e&o%COUNT%"
  PageFooter: "&8Use &e&o/warns %NAME% %NEXT_PAGE% &8to see the next page"
WarnsOwn:
  OutOfIndex: "&4No hay pagina %PAGE%!"
  NoEntries: "&4&oYou have no warnings yet"
  Header:
    - "%PREFIX% &8Your warnings:"
    - "&e&oDuración &8| &8&oAdvertencia de"
    - "&4&o#ID &8> &8&oRazón"
    - "&8"
  Entry:
    - "&8[&e%DATE%&8]"
    - "&e%DURATION% &8| &8%OPERATOR%"
    - "&4&l#%ID% &8> &8&o%REASON%"
    - "&8"
  Footer: "&8Pagina &e&o%CURRENT_PAGE% &8de &e&o%TOTAL_PAGES% &8| &8Advertencias activas: &e&o%COUNT%"
  PageFooter: "&8Use &e&o/warns %NEXT_PAGE% &8to see the next page"
ChangeReason:
  Usage: "&4USO: &8» &8&o/change-reason [ID o ban/mute USER] [Nueva Razón]"
  Done: "&8Castigo &a&o#%ID% &8ha sido actualizado con éxito!"
  NotFound: "&4Lo sentimos, no hemos podido encontrar este castigo."
Check:
  Usage: "&4USO: &8» &8&o/check [Nombre]"
  Header: "&8Checkiando &e&o%NAME% &8(%CACHED%&8)"
  UUID: "&4UUID &8» &8%UUID% &8(%CACHED%&8)"
  IP: "&4IP &8» &8%IP% &8(%CACHED%&8)"
  Geo: "&4Pais &8» &8%LOCATION%"
  Mute: "&4Silenciado|a &8» &8%DURATION%"
  MuteReason: "  &4Razón &8» &8%REASON%"
  Ban: "&4Baneado|a &8» &8%DURATION%"
  BanReason: "  &4Razón &8» &8%REASON%"
  Warn: "&4Advertencias &8» &8%COUNT%"
  NotFound: "&4Lo sentimos, no hemos podido encontrar %NAME%"
  Cached: "&a&ocached"
  NotCached: "&4&ono esta en el caché"

**Comment by DevLeoko** [comment]
Use pastebin or upload the file directly.
Or just post it on our Discord, you might reach more users there.
