### ISSUE TITLE
Allow MySQL and HyperSQL

### ISSUE THREAD

**Issue by JHarris12345** [DevLeoko/AdvancedBan#335]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.8
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungee and spigot
 
_What server version (/version) are you using?_
paper and bungee 1.15

_Please provide the EXACT steps required to reproduce the problem..._
No problem but I have been using HyperSQL internal storage for a year and need to go onto MySQL without losing data. How can I do this? If it is not possible to keep data, is it possible to have a system where it prints to MySQL but can read data from HyperSQL files at the same time?

**Comment by DevLeoko** [comment]
We don't provide any converters sorry
