### ISSUE TITLE
Mysql is not saving the UUID

### ISSUE THREAD

**Issue by joandotcodina** [DevLeoko/AdvancedBan#337]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.8
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord with Sportpaper (https://github.com/Electroid/SportPaper)
(Bukkit --> Spigot --> Paper --> SportPaper)
 
_What server version (/version) are you using?_
git-SportPaper-"4d63808" (MC1.8.8)

_Please provide the EXACT steps required to reproduce the problem..._
1. Just play
2. Using Mysql 

The saw the error while i was checking in the DB
_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
Photo of mysql [https://imgur.com/a/KcB7Y0P](https://imgur.com/a/KcB7Y0P)

_Add any additional information below._

**Comment by DevLeoko** [comment]
If you have a bungee server only install AdvancedBan there and not on the individual spigot server

**Comment by joandotcodina** [comment]
Thank u!
