### ISSUE TITLE
[Feature Request] Command check <player> add the history of ip 

### ISSUE THREAD

**Issue by Neewen** [DevLeoko/AdvancedBan#339]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_

2.1.8 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
I'm not using advancedban right now. (but my test server is the 1.9.4 spigot)

_What is the proposed feature?_

The feature request is to be able to see a player's ip history.

**Comment by DevLeoko** [comment]
To see the player's ip history simply do /history IP

**Comment by Neewen** [comment]
Hi,
Does that make every ip change? Every connection?

**Comment by DevLeoko** [comment]
Sorry, I don't understand the question.
The /history IP command shows you the history for that particular IP address.
It is not intended to have any long term tracking of ip-bans based on a player name.

**Comment by Neewen** [comment]
In other words, being able to have all the ip used by a player

**Comment by DevLeoko** [comment]
`It is not intended to have any long term tracking of ip-bans based on a player name.`
So no, AdvancedBan does not really do any IP to Player matching.

**Comment by Neewen** [comment]
Hi, thanks anyway.
