### ISSUE TITLE
[Help] activate UUID even in crack  

### ISSUE THREAD

**Issue by Neewen** [DevLeoko/AdvancedBan#340]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_

2.1.8 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
I'm not using advancedban right now. (but my test server is the 1.9.4 spigot)

_What is the proposed feature?_

To be able to activate in the plugin configuration the uuid for in some cases (server which makes for those who buy minecraft a connection by the servers of mojang and which thus have a UUID of mojang and that the crack must logi n[/register and /login] as for example with the plugin JPremium or EhLogin on spigotmc) it will make it possible not to ban only the nickname and thus that if the person changes of nickname it remains banned.

**Comment by DevLeoko** [comment]
But when someone gets banned they can just choose a different name/account as it's a cracked server. They don't even have to change their accounts name.

**Comment by Neewen** [comment]
Hi,
**For "They don't even have to change their accounts name."**
If he can because the server handles crack and premium differently with JPremium or Aegis...
Exemple for JPremium (in description):
![image](https://user-images.githubusercontent.com/62424178/80907975-e68f3600-8d1b-11ea-9b2d-27e2b9a6ad58.png)
![image](https://user-images.githubusercontent.com/62424178/80907941-69fc5780-8d1b-11ea-836b-d9f1c2a14325.png)

**and I'd like to add**
if we configure JPremium or other, to have a maximum of 2 accounts per register ip (in premium and crack) it could be bypassed by changing the nickname because all other plugins work with UUIDs and not yours so JPremium or other for him it's the same account once the nickname change so he could get all his stuff (for example which is duplicate) and give it to a lot of people at a time when the administrators/moderators are not there.

**Comment by DevLeoko** [comment]
Does JPremium inject the UUIDs so that they identify the accounts as you want them to?
Then you can just enable Intern UUID Fetching in the config and AdvancedBan will start using the UUIDs provided by the server

**Comment by Neewen** [comment]
Oh uuid fetching, I didn't see sorry.

**Comment by DevLeoko** [comment]
No problem, can this be closed then?

**Comment by Neewen** [comment]
Yes, no problem, thank you.
