### ISSUE TITLE
WarnActions still issuing before they should

### ISSUE THREAD

**Issue by wanskae** [DevLeoko/AdvancedBan#343]
I can see someone had already made a bug report on this and this should've been fixed a while ago in version 2.1.5. Yet we're still experiencing this.

_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.8
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
git-Paper-162 (MC: 1.15.2)

_Please provide the EXACT steps required to reproduce the problem..._
1. Warn a player a few times (in our case, at least three times)
2. Occasionally players get tempbanned on the third warning instead of on the fourth

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No errors in console

_Add any additional information below._
Like with the previous bug report, players are getting punished too soon.
![image](https://user-images.githubusercontent.com/63206547/81056664-9529a700-8ed3-11ea-9063-a9749c1bb1c5.png)
![image](https://user-images.githubusercontent.com/63206547/81056786-d7eb7f00-8ed3-11ea-94b6-6d64b145ae3d.png)
Player should be kicked from 3 warnings and banned from 4. Yet some players get banned on the third warning.

**Comment by DevLeoko** [comment]
Thanks for the bug report, I'll check this out.

**Comment by DevLeoko** [comment]
This bug should be fixed in the latest version of AdvancedBan.
https://www.spigotmc.org/resources/advancedban.8695/update?update=335170
Sorry for the trouble and feel free to reopen this issue if the bug persists.

**Comment by SiuanSong** [comment]
Running 2.1.9 and can confirm this is still happening. 
I do not remember ever removing a punishment this players punishment history file.

![firefox_MJOtmAL2Dr](https://user-images.githubusercontent.com/28202890/83583677-fc5a6b80-a512-11ea-8bb3-abbcff83e17c.png)

**Comment by DevLeoko** [comment]
Any chance you might have observed any pattern/circumstance that causes this to happen?
