### ISSUE TITLE
[Feature Request] Checking IP address

### ISSUE THREAD

**Issue by wanskae** [DevLeoko/AdvancedBan#344]
**What version of AdvancedBan (`/AdvancedBan`) are you using?**
 2.1.8
 
**What kind of server do you have (`Bungeecord/single server`)?**
 Bungeecord
 
**What is the proposed feature?**
Command /check [ip] that would show all the users logged in from a specified IP address.

At the moment the only way to look for ban evaders or such is to check players individually with /check [player]. That is of course not ideal. Thus a feature like this would be quite useful.

**What would be a problem in this plugin?**
This is kind of a bug report at the same time, because I have noticed that usually (or even always) when checking on an offline player, the IP address says 'none cashed'. Is that a problem on plugin side or in our server database? Would that affect the /check [ip] command and is there a solution for this?
![image](https://user-images.githubusercontent.com/63206547/81235044-b76e1280-9002-11ea-93a9-6dd757318f6a.png)

**Comment by DevLeoko** [comment]
> Command /check [ip] that would show all the users logged in from a specified IP address.

That is not what AdvancedBan is about. For such features there are a lot of Alt-Account Plugin
