### ISSUE TITLE
All players are exempt, cannot kick/ban

### ISSUE THREAD

**Issue by xKesvaL** [DevLeoko/AdvancedBan#345]
I'm using the version 2.1.8 (BungeeCord) of AdvancedBan.
It is installed in each of my spigot (paper) server too.
 
I'm on Paper 1.15.2 (Build 245)

1. Create a bungeecord + paper server, install AdvancedBans
2. Install luckperms on bungee + paper (LuckPerms is working, i checked)
3. Add kick permissions to admin and try to ban someone

And here, i get « Cannot kick <player> » like if he was exempted, but he is not.

**Comment by DevLeoko** [comment]
Q: I want to use this with Bungeecord, where do I install the plugin
A: Only on the Bungeecord and not on the single spigot servers

Q: I don't have permissions (but I should)!
A-Bungeecord: You have to use the Bungeecord permission system, so either use the config.yml of Bungeecord to give you the perms or use a Plugin which supports Bungeecord Permissions
Make sure you have the right permission nodes: https://pastebin.com/iFeBRD5A

**Comment by xKesvaL** [comment]
I was using this on my spigot servers too, sorry.
