### ISSUE TITLE
MySQL problem

### ISSUE THREAD

**Issue by LarceRR** [DevLeoko/AdvancedBan#346]
1.AdvancedBan version - 2.1.8
2. Single server
3. Minecraft server version - 1.7.10 (Thermos)

1. I connected the plugin to the database
2. I tried to ban a player using the console
3. i just type /ban [Nickname] [reason] in the console
2. The console writed me error like this:

https://pastebin.com/q0wFW8Nc

**Comment by DevLeoko** [comment]
Duplicate of #320
