### ISSUE TITLE
[Feature Request] Ban names (instead of UUID)

### ISSUE THREAD

**Issue by joecollyer** [DevLeoko/AdvancedBan#347]
I thought that it would be a good idea (especially for larger servers) if you had the option to ban a NAME instead of a UUID.
This would allow servers to ban bad usernames without the user having to appeal and be approved when they change it - saving lots of time.

Command would look something like /banname (username)

Would be cool if possible, thanks!

**Comment by DevLeoko** [comment]
I think this is more something for an own plugin that would maybe even have default lists with forbidden names. This does not really require the complicated AdvancedBan infrastructure.
