### ISSUE TITLE
Dependency Relocation

### ISSUE THREAD

**Issue by A248** [DevLeoko/AdvancedBan#351]
**What version of AdvancedBan (`/AdvancedBan`) are you using?**
 2.1.9-RELEASE
 
**What kind of server do you have (`Bungeecord/single server`)?**
 Single
 
**What server version (/version) are you using?**
For the example,
`Paper version git-Paper-284 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**Please provide the EXACT steps required to reproduce the problem.**
1. Install AdvancedBan
2. Install another plugin which uses dependencies from AdvancedBan
3. Use a server implementation which includes dependencies from AdvancedBan
4. View/monitor for conflicts

**Any error/log post it through [pastebin.com](http://pastebin.com) and link it here.**
Here is an example, using AntiVPN (which relies on hsqldb) with AdvancedBan, https://pastebin.com/1tAfmaK4, the main takeaway of which is
```
[AntiVPN] Loaded class org.hsqldb.jdbc.JDBCDriver from AdvancedBan v2.1.9 which is not a depend, softdepend or loadbefore of this plugin.
```

**Add any additional information below.**
If 2 plugins uses different versions of shaded but not relocated dependencies, linkage errors may occur. The above example is the best-case scenario. I would presume plugins may encounter NoSuchMethodError / NoClassDefFoundError during operation if there is a versioning mismatch. The CraftBukkit wiki mentions "unintended behavior or exceptions" (https://bukkit.gamepedia.com/Using_External_Libraries_with_Plugins#Shade_the_external_libraries_into_the_plugin.E2.80.99s_jar). slf4j, in particular, *should* fail fast rather than permit the problem to silently persist (see http://www.slf4j.org/codes.html#multiple_bindings).

I originally setup 2 examples – the one described above with AntiVPN, and another intended to produce a slf4j binding conflict. I used multiple versions of Paper with slf4j included, as well as a plugin with slf4j shaded. Oddly enough, even though I verified that multiple slf4j bindings were on the classpath, I was unable to create such a conflict. However, I did find an error report related to another plugin using slf4j, where the plugin included slf4j in its jar: https://forums.minehut.com/topic/7113-an-internal-error-occurred-while-trying-to-perform-this-command/ (Use CTRL+F and search for "slf4j").

**The Solution**
I believe it would be reasonably simple to relocate AdvancedBan's shaded dependencies. The only reason I haven't created a PR yet is because I am unsure how certain dependencies and interdependencies would be affected by relocation.

For instance, I know that JDBC drivers such as hsqldb have an entry in the MANIFEST.MF so that they're recognised as valid drivers. However, I don't know if the maven-shade-plugin will change this or not. I'll do some testing and see what happens.

**Comment by DevLeoko** [comment]
Thanks a lot for this extensive bug report, some solid debugging you did there 👍
Have you already tried relocating it?

**Comment by A248** [comment]
By pure coincidence I found a user whose server console reported AdvancedBan using slf4j from another plugin:
```
[Server] Server thread/WARN [AdvancedBan] Loaded class org.slf4j.LoggerFactory from DiscordWhitelister v1.0.9 which is not a depend, softdepend or loadbefore of this plugin.
```
Line 476, https://pastebin.com/Jx72qemg

**Comment by OopsieWoopsie** [comment]
I was giving support to an user of one of my plugins and I found this, I can't provide the full server log because it contains sensitive information. This happened at the startup, before the plugin MOTD.

> [17:23:46] [Server thread/WARN]: [AdvancedBan] Loaded class org.h2.Driver from AdvancedAchievements v6.0.0 which is not a depend, softdepend or loadbefore of this plugin.

I don't think is something serious but it should be really bad if the plugin from which the lib. is loaded has a different version than the one required by AB.

**Comment by A248** [comment]
The PR corresponding to this issue, which relocates the dependencies using the maven-shade-plugin, has been merged, so future versions of AdvancedBan shouldn't have this problem.
