### ISSUE TITLE
/change-reason not working + error

### ISSUE THREAD

**Issue by Tikkle** [DevLeoko/AdvancedBan#353]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.9
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single
 
_What server version (/version) are you using?_
Paper version git-Paper-299 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
5 versions behind

_Please, provide the EXACT steps required to reproduce the problem..._
1. tempban, tempmute, or tempwarn someone for any reason
2. try to change the reason with /change-reason ID NEWREASON
3. Doesn't change the reason and the console spits out an error.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
[pastebin.com](https://pastebin.com/meU0wzzB)

_Add any additional information below._
If you need more info, just ask :)

**Comment by DevLeoko** [comment]
Thanks for the bug report, we will look into this 👍

**Comment by DevLeoko** [comment]
This issue got fixed in the latest version of AdvancedBan, thanks for the report
