### ISSUE TITLE
#Layouts are case sensitive

### ISSUE THREAD

**Issue by SiuanSong** [DevLeoko/AdvancedBan#355]
Running 2.1.9 and #layouts are case sensitive.  I don't know if this is intended or not and while it's a super minor issue, I thought I'd report it nonetheless.
Cheers m8

**Comment by DevLeoko** [comment]
Thanks for the report, will be fixed

**Comment by DevLeoko** [comment]
It is actually not that trivial to read layouts from the config in a case-insensitive manner. As this is a minor issue, I think we will just leave it as it is.
Thanks though for pointing that out.

**Comment by SiuanSong** [comment]
Fair enough! Thanks for your time
