### ISSUE TITLE
Player cannot use commands that start with any of the prohibbited commands

### ISSUE THREAD

**Issue by radiant-ai** [DevLeoko/AdvancedBan#357]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.9
 
_What kind of server do you have (`Bungeecord/single server`)?_
Single
 
_What server version (/version) are you using?_
Paper-318

_Please provide the EXACT steps required to reproduce the problem..._
1. Mute player.
2. Player tries to use command starting with any of the prohibitted coommands. E.g there is an -"r" entry in a list of prohibitted commands.
3. Player cannot use commands starting with "r". E.g /region or /rtp

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any additional information below._
Problem is here: [https://github.com/DevLeoko/AdvancedBan/blob/652f414a545fe9b469f870cf53846deaeb871622/src/main/java/me/leoko/advancedban/Universal.java#L208](url)

**Comment by DevLeoko** [comment]
Thanks for the report

**Comment by DevLeoko** [comment]
This issue got fixed in the latest version of AdvancedBan, thanks for the report
