### ISSUE TITLE
Ban Announcer Bug

### ISSUE THREAD

**Issue by itsWarHammer** [DevLeoko/AdvancedBan#359]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 3.6.4
 
_What kind of server do you have (`Bungeecord/single server`)?_
 currently Single
 
_What server version (/version) are you using?_
1.12.2 

_Please provide the EXACT steps required to reproduce the problem..._
1. the player was previously muted 
2. /history
3. Ban Announcer message is sent to discord writing it as an Un-Mute embed

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
no errors

_Add any additional information below._

**Comment by DevLeoko** [comment]
BanAnnouncer is not our resource. Please use their support.
