### ISSUE TITLE
/unwarn [ID] Error

### ISSUE THREAD

**Issue by BCBAdrian** [DevLeoko/AdvancedBan#364]
2.1.5-RELEASE
 
Single
 
CraftBukkit version git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) ( SPIGOT 1.12.2 )

_Please provide the EXACT steps required to reproduce the problem..._
1. /warn someone
2. /unwarn [ID] ?
3. See Error.

[LOG](https://pastebin.com/iubUYv3W)

I don’t know how the /unwarn [ID] command works, and what ID it needs to indicate, but when I specify any, the console error. Help please.

**Comment by DevLeoko** [comment]
You are using an outdated version. Please update to the newest one

**Comment by BCBAdrian** [comment]
Need to use warning ID from banlist?

**Comment by DevLeoko** [comment]
yes or from /warns PLAYER
