### ISSUE TITLE
ChatControlPro conflicting with AdvancedBan mute.

### ISSUE THREAD

**Issue by MithrandirCraft** [DevLeoko/AdvancedBan#365]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.9-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Waterfall server + 4 Paper servers
 
_What server version (/version) are you using?_
git-Paper-350 (MC: 1.15.2)

_Please provide the EXACT steps required to reproduce the problem..._
1.Install advancedban
2./mute <player> <reason>
3.with muted player, try sending /tell <message>'s
4.tell's are not muted. Everything else seems to be.

_Add any additional information below._
I've already spoken to ChatControlPro about this. There seems to be an event priority issue.
https://github.com/kangarko/ChatControl-Pro/issues/1681

**Comment by DevLeoko** [comment]
Why do you think this has something to do with priorities? For which event would that be?
There should be no other plugin trying to cancel/uncancel a command.
Is /tell a bungeecord command? Have you installed AdvancedBan only on the bungeecord?
Does muting other bungeecord/non-buneecord commands work?

**Comment by DevLeoko** [comment]
Also please check if this dev version fixes your issue: https://github.com/DevLeoko/AdvancedBan/actions/runs/129873002
(Download under "Artifacts")

**Comment by MithrandirCraft** [comment]
> Why do you think this has something to do with priorities? For which event would that be?
Every time I bring this up on ChatControlPro's github, they always ask me to modify their chat formatting priorities, although they where pretty vague on what event would be exactly causing a conflict here, they have brought up a few time that it was a priority issue.

> There should be no other plugin trying to cancel/uncancel a command.
The command in itself isn't being cancelled/uncancelled. It's the actual effects that are NOT being cancelled, specifically through /tell. Essentially you can use /tell even while muted.

> Is /tell a bungeecord command?
Nope, it's a ChatControlPro command, as I mentioned, this is a conflict between CCP(/tell) and AB(/mute effects).

> Does muting other bungeecord/non-buneecord commands work?
I haven't found, nor have been reported any issues with any other communication method based on a command from ChatControlPro, or any other source.

> Also please check if this dev version fixes your issue
ok.

**Comment by DevLeoko** [comment]
> The command in itself isn't being cancelled/uncancelled. It's the actual effects that are NOT being cancelled, specifically through /tell. Essentially you can use /tell even while muted.

I'm not sure whether I understand you correctly.
AdvancedBan is not considering the effects of any command.
When someone executes a command AB checks whether this command is forbidden for muted players and prevents it from even reaching the command's plugin.
And AdvancedBan should be the only plugin interfering at that point.

The latest build should now work for you, please check whether the issue persists

**Comment by DevLeoko** [comment]
> I haven't found, nor have been reported any issues with any other communication method based on a command from ChatControlPro, or any other source.

Would you mind adding one bungeecord and one spigot command to the muted-commands list and see if they get blocked when you are muted?

**Comment by MithrandirCraft** [comment]
>  AdvancedBan is not considering the effects of any command.
That would be why you can use ChatControlPro's /tell in order to avoid /mute effects.

> I'm not sure whether I understand you correctly.
> Would you mind adding one bungeecord and one spigot command to the muted-commands list and see if they get blocked when you are muted?
You CAN execute the /mute command. The issue is that if you are muted with AdvancedBans, you can still speak through /tell. 

It seems maybe they just don't want to support your plugin, for what I can read.

> Would you mind adding one bungeecord and one spigot command to the muted-commands list and see if they get blocked when you are muted?
I can and I will if you want, but this isn't my issue at all.

**Comment by DevLeoko** [comment]
I think you are a little confused about what a chat message is and what a command is.
/tell is a command
Normally it goes like this: Player types "/tell ABC" --> Server receives command --> CCP processes command
But when a player is muted: Player types "/tell ABC" --> Server receives command --> AB intercepts command --> CCP does not get the command

And it seems like the interception part does not work properly.
Now I'd like to know whether that is an Issue with CCP or your Server.

So would you mind adding one bungeecord and one spigot command to the muted-commands list (config.yml of AB) and see if they get blocked when you are muted?


> I will if you want, but this isn't related to my issue at all.

We changed how AB recognizes muted command since the last release

**Comment by MithrandirCraft** [comment]
> I think you are a little confused about what a chat message is and what a command is.
I think you are confused and that I expressed myself perfectly :'D
I understand you can't handle behaviours that you do not control (ChatControlPro's PM's), so maybe there's simply no solution for this.

>  Now I'd like to know whether that is an Issue with CCP or your Server.
If you ask me, I'd say it's just CCP that doesn't want to offer compatibility with your plugin. Instead they just want to sell their own. I came here because they mentioned I should ask you about it.

**Comment by DevLeoko** [comment]
> I understand you can't handle behaviours that you do not control (ChatControlPro's PM's), so maybe there's simply no solution for this.

If it is a normal command than AB is able to intercept it. Or is it not a command?

I've installed CCP and AB on a local server and it seems to work fine
![image](https://user-images.githubusercontent.com/13747815/84710124-e3ff3d80-af63-11ea-8960-b81ae92f39cd.png)

**Comment by MithrandirCraft** [comment]
> Or is it not a command?
Well, now that I think about it. Technically players use the command to comunicate, so I guess it is, and I'm the one who's confused :P

I'm going to try to solve the sql problem and update first.
I just noticed this config:
```MuteCommands:
- 'me'
- 'say'
- 'tell'
- 'msg'
- 't'
- 'whisper'```
This should do the trick as you said, sorry for making this conversation excessive for such a simple solution.

**Comment by MithrandirCraft** [comment]
Fixed, thanks!
