### ISSUE TITLE
Permissions doesn't work 

### ISSUE THREAD

**Issue by IMakeMCVideos** [DevLeoko/AdvancedBan#366]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_ 2.1.9
 
 
_What kind of server do you have (`Bungeecord/single server`)?_ Bungeecord server.
 
 
_What server version (/version) are you using?_ 1.8.8 Minecraft.

_Please provide the EXACT steps required to reproduce the problem..._
1. I can't use the permissions
2. For example if I give a Mod the permission "ab.ban.perma" he cant do /ban
3. I use Luckperms for every permission.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any additional information below._
I use Luckperms for the permissions and groups and prefixes etc.

**Comment by DevLeoko** [comment]
Is Luckperms also installed on the bungeecord? Check the users' permissions with "lpb check"

**Comment by IMakeMCVideos** [comment]
Do you need to install LuckPerms it on every server? Because only thing I
get in the hub if I type that is "Running LuckPerms v5.1.55."

Op ma 15 jun. 2020 20:15 schreef Leo Garbe <notifications@github.com>:

**Comment by DevLeoko** [comment]
Yes, I think Luckperms should be installed on all servers and the bungeecord. Whereas AdvancedBan only goes on the Bungee.

You should then be able to do `/lpb check <user> <permission>`
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-General#lp-check-user-permission

**Comment by IMakeMCVideos** [comment]
Wait, do I need to install Luckperms-Bungee to Bungeecord and Luckperms-bukkit to all other servers or every server the Luckperms-Bungee plugin? Because now my prefixes don't work or something

**Comment by DevLeoko** [comment]
I'm sorry, I've never really worked with Luckperms. You will need to use their support if you have any issues
