### ISSUE TITLE
ERROR MYSQL

### ISSUE THREAD

**Issue by SoyWama** [DevLeoko/AdvancedBan#368]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBan-2.1.9-RELEASE.jar
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single server
 
_What server version (/version) are you using?_
paper-341.jar

_Please provide the EXACT steps required to reproduce the problem..._
Just download the plugin and then reboot the server and it started giving an error on the console and kicked everyone who was connected. Then change "LockdownOnError: true" to "false" and it stopped kicking users but it didn't stop throwing errors on the console.
And then I tried to add:
  Properties: 'verifyServerCertificate = false & useSSL = false & useUnicode = true & characterEncoding = utf8 & serverTimezone = UTC'
But it did not work, the error continues to appear.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/GYtVpy00

_Add any additional information below._
No one could enter the server when this error occurred, until I configured what was previously named. But still, the error persists.

Config.yml:
https://pastebin.com/7WRkzrgq

![Nuevo Lienzo](https://user-images.githubusercontent.com/66584605/84784349-94029400-afc0-11ea-9cb8-e09fa110e2ff.jpg)

**Comment by DevLeoko** [comment]
Check if your MySQL data is correct and if your MySQL-Server is online

The helpful error messages can be found in `plugins/AdvancedBan/logs/latest.log`

Also please check whether this build fixes your issue: https://github.com/DevLeoko/AdvancedBan/actions/runs/136433739
