### ISSUE TITLE
Can't connect to mysql

### ISSUE THREAD

**Issue by rosellonsito** [DevLeoko/AdvancedBan#369]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.9
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single Server
 
_What server version (/version) are you using?_
This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. Use Mysql
2. Put database credentials
3. Get an error

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/eRESujWs

_Add any additional information below._
I can access to the database in the mysql console and the credentials are fine, I can't get it working...
Server running on debian 9 and mariadb 10.4.12

**Comment by DevLeoko** [comment]
Seems like your MySQL Server crashed or does not allow connections.

You could also check `plugins/AdvancedBan/logs/latest.log` for more detailed error messages
