### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by xANoyU** [DevLeoko/AdvancedBan#372]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
2.1.8
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
BungeeCord, connect to MySQL
 
_What server version (/version) are you using?_

1.12.2

_Please provide the EXACT steps required to reproduce the problem..._

1.i don't known

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

https://pastebin.com/rh2GmRjb

_Add any additional information below._

...

**Comment by DevLeoko** [comment]
Please update to 2.1.9 and if the error persists post the contents of `plugins/AdvancedBan/logs/latest.log`

**Comment by xANoyU** [comment]
> Please update to 2.1.9 and if the error persists post the contents of `plugins/AdvancedBan/logs/latest.log`

ok , I upgraded , If I don't report error the mistake tomorrow , Then you can close this issue .
thanks!
