### ISSUE TITLE
Layered Exempt Permission Could Work Offline?

### ISSUE THREAD

**Issue by ShreyasAyyengar** [DevLeoko/AdvancedBan#375]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 v.2.1.9
 
_What kind of server do you have (`Bungeecord/single server`)?_
Bungee cord
 
_What server version (/version) are you using?_
1.16

This isn't really a bug report but more of a question. I'm trying to setup layered permissions, but they don't seem to work when the player is offline. Will that be changed, or has that already been changed and maybe I need to update my version?

Thank you!
Shreyas

**Comment by DevLeoko** [comment]
We don't support that for bungeecord yet. Currently this only works on Spigot with Luckperms
