### ISSUE TITLE
Tempipban (and other such aliases) Not Working Properly

### ISSUE THREAD

**Issue by ShreyasAyyengar** [DevLeoko/AdvancedBan#378]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.2.0 Stable
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungee cord with 3 Backend Servers
 
_What server version (/version) are you using?_
 This server is running CraftBukkit version git-Spigot-a99063f-be6aaf0 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. Place Advancedban in bungee cord, and in all backend servers
2. Sync them up with MySQL

Firstly, I would like to know how to IP ban someone. For example, I, for some reason have 3 IP addresses that I'm trying to ban, all come down to my location. When I try to ban the IP that shows up when I do /check (myign). It doesn't immediately ban all players with that IP. When I try to relog when the ban is in place, I get this. 

<img width="1792" alt="Screenshot 2020-07-13 at 6 27 18 PM" src="https://user-images.githubusercontent.com/65931801/87294536-7f210e00-c536-11ea-9830-b652fd7114fe.png">

When I check my Console I get this exact message.

[w8KExmZC.txt](https://github.com/DevLeoko/AdvancedBan/files/4911860/w8KExmZC.txt)

And until the IP ban in over, I still get the "Failed! Please see console for details!"

I'm not entirely sure how to ban IP's and Unban them either. And wheater doing /tipban (or /tempipban) (my IGN) actually works or not.

This is probably very confusing so if you need any more information, I'd be happy to provide it. 

Any solid answers will be greatly appreciated.

Shreyas
_

**Comment by DevLeoko** [comment]
AdvancedBan should only be installed on the Bungeecord server and not the spigot servers.
The error message you get seems to be caused by a broken message file. Delete your message file and try again.

**Comment by ShreyasAyyengar** [comment]
I also have an anti-cheat plugin that automatically bans targets using Advancedban. However, when I install advanced ban solely on bungeecord, my anti-cheat plugin doesn't know what plugin the /ban command is associated with. It could be Advancedban, or EssentialsX, or the basic Minecraft ban. The reason why I have Advancedban on my backend servers as well is that I can include a prefix so my anti-cheat knows which plugin to ban with. So I would have, /advancedban:tempban (user) #TimeLayout @Layout.

Having my advancedban on bungeecord only removes this option.

Do you have any suggestions to this issue. 

And could you also teach me a bit about IP banning and so and so. 

Thanks,
Shreyas

**Comment by DevLeoko** [comment]
Please use our discord for this kind of support: https://discord.gg/ycDG6rS
GitHub is rather for Bug-Tracking.
