### ISSUE TITLE
/note tab completion

### ISSUE THREAD

**Issue by JasonHorkles** [DevLeoko/AdvancedBan#381]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.2.1
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungee
 
_What server version (/version) are you using?_
Paper-115 1.16.1

_Please provide the EXACT steps required to reproduce the problem..._
1. Type `/note `
2. Start typing someone's username
3. See that it's not filtering tab complete like other commands (such as /ban)

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
No errors

_Add any additional information below._
Works fine on other commands as mentioned above, just not note from what I've seen (but there could be others)

**Comment by DevLeoko** [comment]
That's weird as the note command uses the exact same tab-completion code as the ban command. Also, it works fine on my test server.
Is it possible that you have any other plugin on your server that might conflict with this commands tab completion?
Or maybe you don't have the permission `ab.note.use`?

**Comment by JasonHorkles** [comment]
I should have the permission node and everything but I'll have to do some
testing later. Did you test it on a proxy or spigot server?

**Comment by DevLeoko** [comment]
I tested it on both

**Comment by JasonHorkles** [comment]
Sorry for the delay. It seems to work fine but is just case sensitive while some other ones aren't.
