### ISSUE TITLE
Failed to Connect to MySQL Server

### ISSUE THREAD

**Issue by Antonios-P** [DevLeoko/AdvancedBan#396]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_2.2.0-SNAPSHOT
 
 
_What kind of server do you have (`Bungeecord/single server`)?_ Nukkit Single Server
 
 
_What server version (/version) are you using?_ git-2751f1a 「」 implementing API version 1.0.11 for Minecraft: BE v1.16.20 (protocol version 408)

_Please provide the EXACT steps required to reproduce the problem..._
1. Fill out the MySQL.yml file with the following format: [

MySQL:
  IP: 'ip'
  DB-Name: 'dbname'
  Username: 'username'
  Password: 'password'
  Port: 3306

]
The brackets are just for formatting purposes, and not in the actual file
2. Switch MySQL to true in config.yml
3. Watch as it says "Failes to Connect to MySQL"

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_ NO LOGS RECORDED EVEN WITH DEBUG ON

_Add any additional information below._

**Comment by Hopefuls** [comment]
The mysql file was removed inbetween version 2.1.6 and 2.1.9. It is now inside the actual config.yml file. Delete the MySQL file and config file and restart your server.

**Comment by Antonios-P** [comment]
Thank you for your reply. However, this all doesn't add up. Number one, I would think if this is the case, that you would remove the file in subsequent versions. Number two, I don't see anything in the config for MySQL other than to turn it on. This is my first using the plugin, so I haven't done any upgrades.

My ```config.yml``` part that has SQL code:

```
# AdvancedBan v3 - Coded by Leoko
# For each setting, there is a small description.
# Please read each description carefully before changing anything.
# For more information visit: https://www.spigotmc.org/resources/advancedban.8695/
# Do you want your own Plugin or Website? Check out our Dev-Page: http://dev.skamps.eu
# If set to false all bans will be saved locally in a HSQLDB-Database
UseMySQL: true
```

That's it. Nothing more, nothing less. Thanks.

**Comment by Antonios-P** [comment]
Well...It turns out that the problem was super simple to solve. I apparently forgot to grant MySQL privileges to the AdvancedBan MySQL user. I thought I took care of this, but it must've slipped somehow. I apologize.
