### ISSUE TITLE
Failed to Get Ban List (or Anything Really) on Player Join

### ISSUE THREAD

**Issue by Antonios-P** [DevLeoko/AdvancedBan#400]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_ ```2.2.0-SNAPSHOT```
 
 
_What kind of server do you have (`Bungeecord/single server`)?_ Nukkit | Single Server
 
 
_What server version (/version) are you using?_ ```git-2751f1a 「」 implementing API version 1.0.11 for Minecraft: BE v1.16.20 (protocol version 408)```

_Please provide the EXACT steps required to reproduce the problem..._
1. Setup AdvancedBan with MySQL set to true and the MySQL connection info file filled out correctly. Format:

```
MySQL:
  IP: 'localhost'
  DB-Name: dbname
  Username: 'uname'
  Password: 'password'
  Port: 3306
```

2. Start The Server
3. Have a player join
4. Look in the console and there should be an error (There was for me). 

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_ [pastebin.com](https://pastebin.com/BEp022Jx). This is also the ```latest.log```

_Add any additional information below._

It says in the console:

```
---------------------------------------------------------------
An error has ocurred loading the punishments from the database.
---------------------------------------------------------------
```

**Comment by DevLeoko** [comment]
please include /plugins/AdvancedBan/logs/latest.log)

**Comment by Antonios-P** [comment]
@DevLeoko I stated that they we're both the same. All the logs had the same error. 

>This is also the ```latest.log```

**Comment by DevLeoko** [comment]
Oh, you renamed the link to "pastebin.com" I didn't even see the link :D
It appears you are not using the official AdvancedBan as we don't have nukkit support.

Sorry but we only provide support for the latest and official version of AdvnacedBan.

**Comment by Antonios-P** [comment]
@DevLeoko Oh. Umm...ok. Then what is [this]() doing here? Anyway, in the last issue that I posted I was mentioned that the MySQL configuration was inside of the config now. As my last resort, I was thinking of putting the config for the SQL into the config file. Is it the same text just put into the config.yml? Thank you.

**Comment by DevLeoko** [comment]
Yes, it is exactly the same in the config, but that should make no difference.
You could check your logs when you start the server, as the error above indicates that there has been some connection issue earlier.

**Comment by Antonios-P** [comment]
@DevLeoko I don't think there has beena connection. This was another issue that I had and I solved it by granting SQL Permissions server-side. I know what the issue is in Java, and it is related to connection objects. However, keeping in mind that the plug-in was no made using this repo, I don't have the source code to attempt and fix it (and my version is slightly outdated).

**Comment by Antonios-P** [comment]
All the tables appear in the database as well. If there was a connection issue, it would say something like "Failed to connect to MySQL database" in the console.
