### ISSUE TITLE
unexpected error has occurred executing an Statement in the database

### ISSUE THREAD

**Issue by FuchiK0ma** [DevLeoko/AdvancedBan#408]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
  Version: 2.2.1
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Spigot
 
_What server version (/version) are you using?_
Spigot 1.16.2

_Please provide the EXACT steps required to reproduce the problem..._
/tempban User 10m You are temporarily banned because you have destroyed other peoples buildings - You can login later today.

[latest.log](https://github.com/DevLeoko/AdvancedBan/files/5187837/latest.log)

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

_Add any additional information below._

**Comment by DevLeoko** [comment]
Your reason is probably too long. You should use message layouts for something like this
