### ISSUE TITLE
An error is reported when entering the ban command and using the database, but all settings are normal

### ISSUE THREAD

**Issue by Kokored7214** [DevLeoko/AdvancedBan#409]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.2.1
 
_What kind of server do you have (`Bungeecord/single server`)?_
single server
 
_What server version (/version) are you using?_
Paper 1.16.1

_Please provide the EXACT steps required to reproduce the problem..._
1. /ban Pinochio3064 hacker

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

[link](https://pastebin.com/ZSn4cJtS)

_Add any additional information below._

**Comment by DevLeoko** [comment]
Is the log you posted from `/plugins/AdvancedBan/logs/latest.log` or from console?

**Comment by Kokored7214** [comment]
console

this from /plugins/AdvancedBan/logs/latest.log
https://pastebin.com/ULb3UzVa

**Comment by Kokored7214** [comment]
Maybe this is a problem with the ServerPro database

**Comment by DevLeoko** [comment]
Yes, your MySQL Server is reporting a general error code. This has probably nothing to do with AdvancedBan

**Comment by Kokored7214** [comment]
Okay, thank you very much for your assistance. I will contact server pro. thx
