### ISSUE TITLE
ViaBackwards Ignoring Plugin Channel (Simple Solution)

### ISSUE THREAD

**Issue by tedders5** [DevLeoko/AdvancedBan#410]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.2.1
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
Paper-186 1.16.2

_Please provide the EXACT steps required to reproduce the problem..._
1. Install ViaVersion / ViaBackwards on Bungeecord with 1.16.2 Spigot
2. Join the server on a lower minecraft version (for example 1.12.2)
3. On the Spigot server console, the error "ViaBackwards: ignoring plugin channel: advancedbans" will show

The solution is to make all the channel keys/parameters lowercase:

Screenshot of solution from ViaVersion discord support:
![](https://puu.sh/Gvz0E/a385f06dd3.png)

**Comment by DevLeoko** [comment]
Will be changed with the next update, thanks for the report 👍
