### ISSUE TITLE
Impossible to ban players

### ISSUE THREAD

**Issue by Mast3rrr** [DevLeoko/AdvancedBan#411]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single server
 
_What server version (/version) are you using?_
1.12.2

_Please provide the EXACT steps required to reproduce the problem..._
1. I ban a player (with /ipban or /ban)
2. He is kick of the server and I have this error in the console
3. When he try to reconnect on the server he can, like he is unbanned
4. I tried this 7-8 times, it didn't work (but with essentials' ban command it worked)

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

https://pastebin.com/3M7Lk3JW

_Add any additional information below._

**Comment by Hopefuls** [comment]
Hey hey,
This error was present in the Version 2.1.5 and was fixed in 2.2.1. Please update your AdvancedBan through [here!](https://www.spigotmc.org/resources/advancedban.8695/)

**Comment by Mast3rrr** [comment]
Oh I see, thanks =)
