### ISSUE TITLE
Get all ban on the same IP

### ISSUE THREAD

**Issue by Elikill58** [DevLeoko/AdvancedBan#413]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.2.1
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Both
 
_What server version (/version) are you using?_
1.7 to 1.16

_Add any additional information below._
I'm the main developer of Negativity, an AC. I have a support for your plugin which works great (to auto ban/get ban).

I would like to add a check for all ban on the same IP. But, I just find how to get IP bans.

How to do it ?

**Comment by DevLeoko** [comment]
PunishmentManager#getPunishments should do what you are looking for just use the IP as `target`
https://github.com/DevLeoko/AdvancedBan/blob/master/src/main/java/me/leoko/advancedban/manager/PunishmentManager.java#L118

**Comment by Elikill58** [comment]
Ok thanks ! It will return all ban with this IP, but only IP ban or also basic one ?

Just, how do I get the IP of basic Punishment ?

**Comment by DevLeoko** [comment]
Just take a look at the code. For IP Punishments the UUID is the IP. So #getUuid() gives you the IP

**Comment by Elikill58** [comment]
Ok :/ that's a problem for me.
Because I need a link between UUID and IP. Like a UUID is ban with specific IP.
