### ISSUE TITLE
Unable to connect to MySQL database

### ISSUE THREAD

**Issue by InventionYT** [DevLeoko/AdvancedBan#414]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
  Version: 2.1.9
 
_What kind of server do you have (`Bungeecord/single server`)?_
Bungeecord
 
 
_What server version (/version) are you using?_
Flamecord 0.4.2

_Please provide the EXACT steps required to reproduce the problem..._
1. AdvancedBans can't connect to my MySQL Database

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
https://pastebin.com/WVJBSa69

_Add any additional information below._
Please help

**Comment by A248** [comment]
Upgrade to the latest version of AdvancedBan
