### ISSUE TITLE
RevokePunishmentEvent and automatic expiration

### ISSUE THREAD

**Issue by BlueTree242** [DevLeoko/AdvancedBan#415]
_version: 2.2.1
 
 
_Server Type: bukkit/paper
 
 
_Server version: 1.16.3

Problem:

**Hello, I a making an addon for advancedban, I have noticed that RevokePunishmentEvent is fired when player is automatticly unpunished (tempban/tempmute) which is not good for the addon, I just want this change in the api so I can continue making my addon.**

**Comment by Hopefuls** [comment]
Isn't that what the RevokePunishmentEvent is supposed to do? It fires when the Player gets unpunished, in your case the player's Punishment Temporary Punishment expired, thus firing the Event.

**Comment by DevLeoko** [comment]
We could add a boolean field to the event indicating whether the revoke was caused by automatic expiration.
(Feel free to implement these changes yourself and to create a PR if you don't want to wait for us to make them ^^)

**Comment by BlueTree242** [comment]
> We could add a boolean field to the event indicating whether the revoke was caused by automatic expiration.
> (Feel free to implement these changes yourself and to create a PR if you don't want to wait for us to make them ^^)

You can add this boolean, but please fast i need to finish the addon

**Comment by A248** [comment]
There doesn't even need to be a field; it can be implemented based on the expiration time:

```java
public boolean isAutomatic() {
  return getPunishment().getEnd() < TimeManager.get().getTime();
}
```

**Comment by BlueTree242** [comment]
> There doesn't even need to be a field; it can be implemented based on the expiration time:
> 
> ```java
> public boolean isAutomatic() {
>   return getPunishment().getEnd() < TimeManager.get().getTime();
> }
> ```

Thanks A248!
