### ISSUE TITLE
BungeeCord sets UUID to user's name

### ISSUE THREAD

**Issue by Comstepr** [DevLeoko/AdvancedBan#419]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.2.1 stable
 
_What kind of server do you have (`Bungeecord/single server`)?_
Waterfall/BungeeCord, Tuinity

_What server version (/version) are you using?_
[08:39:48 INFO]: This server is running Tuinity version git-Tuinity-"5df4a4f" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[08:39:48 INFO]: Previous version: git-Tuinity-"de1983b" (MC: 1.16.3)
[08:39:48 INFO]: You are running the latest version
_Please provide the EXACT steps required to reproduce the problem..._
1. Use BungeeCord.
2. Type /check <username>
3. UUID is the user's name, which should not happen.

ip-forward enabled in Bungee config, bungeecord enabled in spigot config.
_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
That file is empty.
_Add any additional information below._

**Comment by Hopefuls** [comment]
May i ask where is AdvancedBan running on?

**Comment by Comstepr** [comment]
It is running on Tuinity.

**Comment by Comstepr** [comment]
Issue seems to be resolved. (possibly because of the UUID fetcher)

**Comment by Hopefuls** [comment]
AdvancedBan is supposed to be installed on Bungeecord if used in a Network.
