### ISSUE TITLE
AdvancedBan bans and makes bans longer in the minecraft banlist?

### ISSUE THREAD

**Issue by Comstepr** [DevLeoko/AdvancedBan#421]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.2.1 stable
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Waterfall (Bungee) -> Tuinity (Paper/Spigot)
 
_What server version (/version) are you using?_
git-Tuinity-"5df4a4f" 1.16.3
_Please provide the EXACT steps required to reproduce the problem..._
1. Tempban someone for 1h
2. Look in banned-players.json
  {
    "uuid": "<user redacted>",
    "name": "<user redacted>",
    "created": "2020-10-18 23:23:23 +0000",
    "source": "Comstepr",
    "expires": "2020-10-19 08:23:23 +0000",
    "reason": "Stop it"
It changes from 1h to 9h. What is that about?

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

_Add any additional information below._

**Comment by Hopefuls** [comment]
AdvancedBan does **not** store bans in banned-players.json, it uses it's own storage inside the data folder of AdvancedBan ban or MySQL, depending on which one you've chosen.

**Comment by Hopefuls** [comment]
> AdvancedBan does **not** store bans in banned-players.json, it uses it's own storage inside the data folder of AdvancedBan ban or MySQL, depending on which one you've chosen.

This is most likely due to plugins overriding AdvancedBan's Commands.

Also, see response on your last issue.

**Comment by Comstepr** [comment]
I would like an actual answer. Is this related to the syncing of bans with banned-players.json or what?

**Comment by Hopefuls** [comment]
2 things: The Issue you mentioned is a fix that was committed into the **development** branch of AdvancedBan, not the master(stable), thus making "2.2.1 stable" not correct.

Second: Since you mention Bungeecord, why bother using AdvancedBan on Spigot when you're supposed to use it on Bungeecord on a Network?

**Comment by Comstepr** [comment]
> 2 things: The Issue you mentioned is a fix that was committed into the **development** branch of AdvancedBan, not the master(stable), thus making "2.2.1 stable" not correct.
> 
> Second: Since you mention Bungeecord, why bother using AdvancedBan on Spigot when you're supposed to use it on the Proxy on a Network?

I have multiple proxies just to connect to one network. I will not be explaining further on my use case.
Secondly, thank you for letting me know. I shall use the development version of AdvancedBan.

Also, if I was being a bit harsh in this ticket then please do not be offended. Thank you very much and have a great day ahead.
