### ISSUE TITLE
Not able to update ID of punishment!

### ISSUE THREAD

**Issue by ThorinEk** [DevLeoko/AdvancedBan#422]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.2.1
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single server
 
_What server version (/version) are you using?_
This server is running Paper version git-Paper-191 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. Tempban a player
2. I believe the player was already tempbanned/banned, not sure.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
https://paste.ubuntu.com/p/QfhfCTYwhZ/

The player who banned someone used commas (,) in the reason text, perhaps this could be the issue? I know some databases separate cells  by commas.  
I am guessing this might be the interesting part of the error log:
java.sql.SQLDataException: data exception: string data, right truncation;  table: PUNISHMENTHISTORY column: REASON

**Comment by DevLeoko** [comment]
No, I think commas should work fine. 
I suspect that the reason is too long. 
Try to use message layouts for very long reasons.

**Comment by ThorinEk** [comment]
Alright, I will inform my staff about that. Thanks!
