### ISSUE TITLE
Tab complete does not work

### ISSUE THREAD

**Issue by SrBedrock** [DevLeoko/AdvancedBan#423]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_

```
[08:35:59 INFO]: -===== AdvancedBan v2 =====-
[08:35:59 INFO]: Dev • Leoko
[08:35:59 INFO]: Status • Stable
[08:35:59 INFO]: Version • 2.3.0
[08:35:59 INFO]: License • Public
[08:35:59 INFO]: Storage • MySQL (external)
[08:35:59 INFO]: Server • Bungeecord
[08:35:59 INFO]: RedisBungee • false
[08:35:59 INFO]: UUID-Mode • DISABLED
[08:35:59 INFO]: Prefix • [Aviso]
[08:35:59 INFO]: -=========================-
```

_What kind of server do you have (`Bungeecord/single server`)?_
 
> Bungeecord

`[08:36:36 INFO]: This server is running Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:c1ac7d5:377 by md_5`

 
_What server version (/version) are you using?_

`[08:36:57 INFO]: This server is running Tuinity version git-Tuinity-"5df4a4f" (MC: 1.16.3)`

_Please provide the EXACT steps required to reproduce the problem..._
1. With online players, try to use punishment commands like `/ban` or `/ban-ip` and try to complete the players' names.
2. No name is suggested for punishment
![image](https://user-images.githubusercontent.com/51332006/97296871-04070d80-1830-11eb-9a4c-f4133dea3230.png)

**Comment by DevLeoko** [comment]
Does tab completion work for any other advancedban commands?
Are there any errors in the console?
Do the commands themselves work?

Notice that the player needs to have permission to use the command in order to use tab completion.

**Comment by SrBedrock** [comment]
> Does tab completion work for any other advancedban commands?

No, tab completion does not work on any command.

> Are there any errors in the console?

No, everything working normally, no error when starting the server or when using commands.

> Do the commands themselves work?

Yes, all commands work correctly.

> Notice that the player needs to have permission to use the command in order to use tab completion.

Yes, I have the correct permissions, I can execute all the commands I need.

**Comment by Hopefuls** [comment]
Do you have any other plugins that have tab completion on their commands? Do they work?

Do you have some kind of Antitab Plugin for example?

**Comment by SrBedrock** [comment]
> Do you have any other plugins that have tab completion on their commands? Do they work?

I have and they work normally, both plugins on the proxy and on the backend server.

> Do you have some kind of Antitab Plugin for example?

Yes but I have permission to receive suggestions for all existing commands on the server.

**Comment by Hopefuls** [comment]
> Yes but I have permission to receive suggestions for all existing commands on the server.

Do you mind disabling thst plugin and trying again?

**Comment by SrBedrock** [comment]
> Do you mind disabling that plugin and trying again?

I will remove the plugins and try again.
