### ISSUE TITLE
Error enabling AdvancedBan

### ISSUE THREAD

**Issue by nuggs13** [DevLeoko/AdvancedBan#43]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_ 2.0.6
 
 
_What kind of server do you have (`Bungeecord/single server`)?_ single
 
 
_What server version (/version) are you using?_ spigot 1.11.2

_Please provide the EXACT steps required to reproduce the problem..._
1. onloadup throws an error on line 334 of pastebin
2. commands not doing anything ingame  /tempmute (name) 10s
3. 

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
http://pastebin.com/f6UrMFgV

_Add any aditional information below._

**Comment by DevLeoko** [comment]
Did you modify the plugin.yml, try to block the /warn command or have any other plugin containing the /warn command?

**Comment by nuggs13** [comment]
Well that was an easy fix :) . It was staff+ that was causing the issue with /warn in it. 
AB works perfectly now that warn is disabled on staff+. Thanks.
