### ISSUE TITLE
Command ban form Minecraft

### ISSUE THREAD

**Issue by Rollczi** [DevLeoko/AdvancedBan#441]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.2.1
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
![image](https://user-images.githubusercontent.com/49173834/100132339-95948a00-2e85-11eb-9077-7e3993ad095d.png)

_Please provide the EXACT steps required to reproduce the problem..._
1. I execute the command /ban
2. Two commands are executed /minecraft:ban /advancedban:ban
3. I have to use /ban and /pardon to unban a player

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

https://pastebin.com/hDzFiawy

_Add any additional information below._

this does not always happen (usually around 50%)

**Comment by Hopefuls** [comment]
Hey hey,

Would you mind to tell me where you installed AdvancedBan?

What command are you using to ban a player?


Also, don't mind updating to 2.3.0 👍

**Comment by Rollczi** [comment]
_Would you mind to tell me where you installed AdvancedBan?_
- in /plugins 
If I did not install it, it would not work /unban /advancedban etc.

_What command are you using to ban a player?_
"I execute the command **/ban**"

**Comment by Hopefuls** [comment]
And you only installed it on your Proxy, correct? Are there any other
plugins overriding the ban command maybe?

Also, try updating like i said.

**Comment by Rollczi** [comment]
I installed the plugin on my PaperSpigot server. It's not on BungeeCord.

there are no other plugins of this type

**Comment by Rollczi** [comment]
Sorry, I was wrong, but the command /tempban gives a ban with 2 commands.

1. I execute the command **/tempban**
2. Two commands are executed /minecraft:ban /advancedban:ban
3. I have to use /ban and /pardon to unban a player

Add any additional information below.
**it is always like that (100%)**

**Comment by Hopefuls** [comment]
> I installed the plugin on my PaperSpigot
>

Then you are doing it wrong. You have to install it on your Bungeecord
Proxy if used in a Network.

**Comment by Rollczi** [comment]
Works but can i have a plug on my spigot? I need it to auto censor players.

**Comment by Rollczi** [comment]
and for Sign
![Uploading image.png…]()

**Comment by Hopefuls** [comment]
Can't help you with that. You won't be able to use them when AdvancedBan is on Bungeecord.

**Comment by Rollczi** [comment]
In that case I won't have plugin on bungeeCord :(
