### ISSUE TITLE
Ban failed

### ISSUE THREAD

**Issue by JetCrooked** [DevLeoko/AdvancedBan#445]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single server
 
_What server version (/version) are you using?_
1.16.4

_Please provide the EXACT steps required to reproduce the problem..._
1. ban someone
2. they attempt to rejoin the game
3. expected result: they can't join because they're banned. actual result: they apparently aren't banned, and could rejoin

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
https://pastebin.com/MyU9af7w

_Add any additional information below._

**Comment by jeeukko** [comment]
We had this same issue. The database field has a 100 character limit for the reason. We fixed by manually changing it to 256 chars (which is couple more than you can fit into one chatmessage with everything else (command, player etc)) on both tables.

**Comment by JetCrooked** [comment]
why is this issue still open it's been over two months

**Comment by DevLeoko** [comment]
Because you have been presented with a solution and did not give us an update on the status of this issue. 
I'll gladly close this issue for you and assume this to be resolved.
