### ISSUE TITLE
CloudNet Repos Hosting Artifacts They Shouldn't

### ISSUE THREAD

**Issue by A248** [DevLeoko/AdvancedBan#448]
By pure happenstance, I noticed one of the repositories AdvancedBan uses was serving the `org.spigotmc:spigot` artifact.

I tracked this down to the CloudNet3 repository:
https://cloudnetservice.eu/repositories/org/spigotmc/

To my knowledge, the spigot jar cannot be directly distributed in this way without violating the CraftBukkit DMCA. The `org.spigotmc:minecraft-server` jar, which is the vanilla server, is also in the same repo, and its distribution is too is legally unsound. Both jars contain proprietary software by Mojang.

Even if the DMCA and proprietary licensing is not enforced, it would still be wise to avoid association with any potentially illegal operations.

Disclaimer: I am not a lawyer. My words are not legal advice.

**Comment by A248** [comment]
org.spigotmc:spigot-api is also on one of the CloudNet Repos:
https://github.com/CloudNetService/CloudNet-v3/issues/394

**Comment by juliarn** [comment]
And what should he do now? He has no risk by just using our repositories. Only hosting of Mojang property is prohibited, not downloading. And he is not even using the illegal dependencies in our repo.

**Comment by A248** [comment]
I expected CloudNet to solve the issue, and you guys did, so thanks

**Comment by juliarn** [comment]
We removed all inappropriate dependencies from our repos now.
