### ISSUE TITLE
[SOLVED] Problem with banip offline players / unban ip request. 

### ISSUE THREAD

**Issue by Nachodiazv** [DevLeoko/AdvancedBan#45]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Latest. 2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single
 
_What server version (/version) are you using?_
Paperclip 1.10.2

_Please provide the EXACT steps required to reproduce the problem..._

1. Ban a player's nickname
2. Try to ipban that player
3. Cry. !important

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
Nop

_Add any aditional information below._
Ok so additional to adding the possibility to ban offline players IP (As first we always ban the player nick and then the IP so obviously it will be offline) Other thing that would be great to fix/add is when trying to unban a player's IP, we have to write down the IP instead of the player name. It's a little more difficult and slower to write down the hole IP to unban it instead of just writing the player's nick, as the original essentials bans or other ban manager plugins do.

**Comment by dutchy1001** [comment]
I have no problem banning an IP that is offline in v2.0.6. 

The name and IP are not combined for a reason, hense we dont use the Essentials ban therefore.

Adding a plugin like IP-Check (I'm looking for a dev to update this plugin, but that is besides the point) can very easy show the IP of any player that has been on the server and then used a lot faster to ban or unban.

**Comment by Nachodiazv** [comment]
Can this be a problem for cracked servers then? As it seems I can't ban offline players IP :c

**Comment by dutchy1001** [comment]
dunno, I dont have a cracked server.
But I doubt it would matter, IP's are not mojang related. 
What command are you using?

**Comment by Nachodiazv** [comment]
Okay... I tasted it and it works... it seems that there is a player that show "Not IP found for that player" when is offline. But I tested with other players and it worked. Sorry for make you lose your time. 
But I still have a question: If you can ban a players IP by using his name, why can we unban his IP using his name too?.

**Comment by dutchy1001** [comment]
There stored in 2 different tables in your db, that's probably why.

**Comment by DevLeoko** [comment]
The IPs are only cashed temporarily to improve the server performance, so it may be that some Players IPs are not available.

_If you can ban a players IP by using his name, why can we unban his IP using his name too?._
Will be added in a further version of advanced ban :)
