### ISSUE TITLE
Could not pass event RevokePunishmentEvent to AdvancedBan v2.1.9

### ISSUE THREAD

**Issue by 49N123** [DevLeoko/AdvancedBan#453]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
I used these versions: 2.3.0, 2.2.1 and 2.1.9. I tested them to see if they would work.

_What kind of server do you have (`Bungeecord/single server`)?_
 Single
 
_What server version (/version) are you using?_
1.12.2

_Please provide the EXACT steps required to reproduce the problem..._
1. I tried those 3 versions, downloaded them and put them in versions.
2. I went in-game and saw the plugin had worked, then I tried banning someone, I typed /ban (anything) test and saw that nothing appeared in chat until like 10 seconds after. Then I tried unbanning but got an error in the console.
3. 

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
here's the error I got:
https://pastebin.com/7WRMiDP0 

_Add any additional information below._
I saw that someone had the same problem and it was fixed, I tried out the version but it didn't work.

**Comment by DevLeoko** [comment]
Please post the error message for the latest AdvancedBan version.

It looks like it might be an issue with your Paper Spigot version, can you check if switching to a different version/build fixes the issue?

**Comment by 49N123** [comment]
I changed the server version to 1.8 so there are no errors now, thanks anyway!
