### ISSUE TITLE
Failed to load player data

### ISSUE THREAD

**Issue by waveteams** [DevLeoko/AdvancedBan#456]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 PaperSpigot
 
_What server version (/version) are you using?_
Paper(1618) 1.12.2-R0.1-SNAPSHOT

_Please provide the EXACT steps required to reproduce the problem..._
1. I start my server
2. I log in to check it
3. And it kicks me: **[AdvancedBan] Failed to load player data!**

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
[Console log and /plugins/AdvancedBan/logs/latest.log](https://pastebin.com/qe7zZVth)

_Add any additional information below._
**I did NOT change any advancedban settings (it was working before i restarted the server)
(I only changed a custom texture pack and fixed config error for CrazyEnchantments)**

**Comment by Hopefuls** [comment]
Whatever host you're uisng, you have reached the maximum capacity of storage. Free some space.

**Comment by waveteams** [comment]
Sry, this was hosting-side problem ¯\_(ツ)_/¯
