### ISSUE TITLE
Won't let me unban someone on the banlist

### ISSUE THREAD

**Issue by DasJuise** [DevLeoko/AdvancedBan#460]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Spigot/Bukkit
 
_What server version (/version) are you using?_
Paper 1.16.5

_Please provide the EXACT steps required to reproduce the problem..._
1. someone is banned
2. attempt to unban
3. says they arent banned
4. check banlist and they are there

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

_Add any additional information below._

**Comment by Hopefuls** [comment]
Does the ban entry show up with their ip too? If so, try unbanning their ip with `/unban <ip>`

**Comment by DasJuise** [comment]
no, but I can check them and it will give me their IP, and I did try that it held the same result

**Comment by Hopefuls** [comment]
What is the environment you're using AdvancedBan in? A single server (Spigot) or a Network (Bungeecord)?

**Comment by DasJuise** [comment]
it's only one server. i'm not totally sure what you mean but.

**Comment by Hopefuls** [comment]
> it's only one server. i'm not totally sure what you mean but.

Do you mind joining our discord server so we can help you better? It is linked on AdvancedBan's Spigot page.

**Comment by DasJuise** [comment]
sure thank you
