### ISSUE TITLE
Maven can't find api

### ISSUE THREAD

**Issue by LaserSlimeHD** [DevLeoko/AdvancedBan#464]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0

_Please provide the EXACT steps required to reproduce the problem..._
1. Put 
`<dependency>
  <groupId>me.leoko.advancedban</groupId>
  <artifactId>AdvancedBan</artifactId>
  <version>2.1.6</version>
</dependency>`
in your pom.xml
2. It doesn't work even if the version is changed to 2.3.0 or 2.3.0-BUNDLE

_Add any additional information below._
I'm using eclipse.

**Comment by Hopefuls** [comment]
[Please use JitPack to get the required dependencies for working with AdvancedBan](https://jitpack.io/p/DevLeoko/AdvancedBan)

**Comment by LaserSlimeHD** [comment]
Add this to readme then.

**Comment by Hopefuls** [comment]
Anything else? Otherwise close this issue
