### ISSUE TITLE
Banning IP through /ban 

### ISSUE THREAD

**Issue by brysondev** [DevLeoko/AdvancedBan#465]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
paper-1.16.5-468
 
_What server version (/version) are you using?_
This server is running Paper version git-Paper-468 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. `/ban <ip>` 
2. User will be ip banned under the username and will not be able to be unbanned via `unbanip`, only `unban <ip>`

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

_Add any additional information below._

Kindly make it impossible to ban someone via IP with the `/ban` command. We recently had an admin ban someone via ip using the ip as a username and struggled to figure out how to unban the individual because of this bug(?).

**Comment by Hopefuls** [comment]
The command is `/ban-ip`, not `/ban`, this is common sense with punishment plugins. 
Unbanning ips is only possible with `/unban <ip>`.

**Comment by brysondev** [comment]
> The command is `/ban-ip`, not `/ban`, this is common sense with punishment plugins.
> Unbanning ips is only possible with `/unban <ip>`.

Apologies, I figured out the issue, a user had banned someone using `essentialsX` instead of this plugin.
