### ISSUE TITLE
Exception when tab-completing using /ban

### ISSUE THREAD

**Issue by Tikkle** [DevLeoko/AdvancedBan#466]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single
 
_What server version (/version) are you using?_
1.16.5-R0.1-SNAPSHOT git-Paper-484 (MC: 1.16.5)

_Please provide the EXACT steps required to reproduce the problem..._
1. Have 1 person online only.
2. Have AdvancedBan version 2.3.0 installed.
3. Have EssentialsX & Spawn module version 2.18.2.0 installed.
4. Use Paper 1.16.5 build 484 running.
5. Run "/ban username reason"
- As you **type out** the reason the error will spam as well as the in-game message.
- You can execute the command just fine and the user will be banned through AdvancedBan.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

latest.log (from server) - https://gist.github.com/Tikkle/761306891f5eb6e204a43c4ed97d51e8
There is no file called "latest.log" in /plugins/AdvancedBan/logs https://gyazo.com/5bda940f133ee4fdf89b3ef5a1d3d17a.png

_Add any additional information below._
When running "/ban playername reason" essentials spams in chat "An internal error occurred while attempting to tab-complete this command". Upon inspection of the console, the Error log attached displays an "Exception when Tikkle attempted to tab complete ban Michaeloky Theft".

Error: https://gist.github.com/Tikkle/181b7a8df264857a66237254353d800e

I reported this to essentials, this was their reply:
https://github.com/EssentialsX/Essentials/issues/4005#issue-814033571
https://gyazo.com/5b5e9a5469f224f374e176f22727a5b6.png

**Comment by Tikkle** [comment]
Hello?

**Comment by Tikkle** [comment]
Another error that looks different, i think: https://gist.github.com/Tikkle/80b54b4bb3d548d29b92a83695406fed

**Comment by DevLeoko** [comment]
Are you using the official AdvancedBan build from SpigotMC? You can try to delete your config, message, and layout files and see if the error persists. You could also try to use a different PaperSpigot build.

**Comment by Tikkle** [comment]
When i reloaded the config, message, and layout files it works fine, would you mind taking a look at my version of these files and help me find what is causing this issue:

All 3 files are in this GIST: https://gist.github.com/Tikkle/586387f7a4c014707da7b8f771ec5fe2

**Comment by DevLeoko** [comment]
My guess is that the issue is caused because you removed the example layout and our system assumes there to be at least one layout.

**Comment by Tikkle** [comment]
> My guess is that the issue is caused because you removed the example layout and our system assumes there to be at least one layout.

That seemed to work, thanks.
