### ISSUE TITLE
Sending commands through the console not working?

### ISSUE THREAD

**Issue by Nev3rGiveUp** [DevLeoko/AdvancedBan#48]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord
 
_What server version (/version) are you using?_
version git:Bungeecord-Bootstrap:1.11-SNAPSHOT:db1516b:1222 by md_5

_Please provide the EXACT steps required to reproduce the problem..._
1.sending the command through buycraft or console
2.the command is /unban player
3.player is still banned...

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No errors.

_Add any aditional information below._
I want to add a unban feature in my store.

**Comment by DevLeoko** [comment]
If you are using the BungeeVersion of AdvacnedBan you will also need to send the command to the Bungee-Server

**Comment by DevLeoko** [comment]
Closed issue due to no further reply from @Nev3rGiveUp
