### ISSUE TITLE
Getting a "Failed to warn" message

### ISSUE THREAD

**Issue by Condensed-Air** [DevLeoko/AdvancedBan#485]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
 2.2.1
_What kind of server do you have (`Bungeecord/single server`)?_
 
 Bungeecord
_What server version (/version) are you using?_
Paper on backend and waterfall for the proxy

_Please provide the EXACT steps required to reproduce the problem..._
1. Warn a player
2. Get a warning that it failed and to check console
3. See error in console

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. 
[Waterfall log](https://pastebin.com/AkuahciX)
If you need more of the log let me know

**Comment by Hopefuls** [comment]
Invalid pastebin, please make sure to post the correct pastebin url and have it set to never expire.

**Comment by Hopefuls** [comment]
also, update AdvancedBan

**Comment by OwlmanMC** [comment]
Tried updating AdvancedBan but I still am having the problem. Also I updated my post with a working link.

**Comment by Hopefuls** [comment]
>
> [12:28:46] [AdvancedBan Pool Thread #1/INFO]: !! Message-Error in [Only
> available on Bukkit-Version!]!
> [12:28:46] [AdvancedBan Pool Thread #1/INFO]: In order to solve the
> problem please:
> [12:28:46] [AdvancedBan Pool Thread #1/INFO]: - Check the [Only available
> on Bukkit-Version!]-File for any missing or double " or '
> [12:28:46] [AdvancedBan Pool Thread #1/INFO]: - Visit yamllint.com to
> validate your [Only available on Bukkit-Version!]
> [12:28:46] [AdvancedBan Pool Thread #1/INFO]: - Delete the message file
> and restart the server


check your messages.yml
