### ISSUE TITLE
Extensive log when Banned IP log in

### ISSUE THREAD

**Issue by dutchy1001** [DevLeoko/AdvancedBan#50]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 v2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 bungee
 
_What server version (/version) are you using?_
mc 1.11.2

_Please provide the EXACT steps required to reproduce the problem..._
1.banned IP tries to login
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
http://pastebin.com/gUTfyP6Q
Not sure if this should be classed as an error, but it's a bit much for when a banned IP tries to login.
It looks like a colourful rainbow in console due to the colour "codes" in the log 
![img_20170214_205600](https://cloud.githubusercontent.com/assets/5569980/22949056/cb69653c-f2f8-11e6-8de3-acb56dca1d78.jpg)
(I can not take a screenshot unfortunately from the server pc). 
 I suppose those are the colours are a message that isn't coming over properly.

_Add any aditional information below._

**Comment by DevLeoko** [comment]
I'll try to avoid this messages in the next version but because they are from bungee cord I'm not sure if it will be possible

**Comment by Beelzebu** [comment]
The plugin can't do anything about this, is a debug message from BungeeCord to inform that the event "PreLoginEvent" took too much time to process, that happen when the database response is slow.
