### ISSUE TITLE
MySQL Error (Database Manager) on Waterfall

### ISSUE THREAD

**Issue by flashbtw** [DevLeoko/AdvancedBan#507]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
Newest Version 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord Network (Waterfall)
 
_What server version (/version) are you using?_
Paper 1.16.5 

_Please provide the EXACT steps required to reproduce the problem..._
1. Java 16
2. MariaDB

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
https://pastebin.com/b3CDxVxQ

_Add any additional information below._
The server is crashing because of this error after a restart and can't start up again. 
all servers except the one without having advancedban on it, aren't restarting until I restart the MariaDB service.

**Comment by tobgen** [comment]
@flashbtw 
The logs tell you: "Caused by: java.net.ConnectException: Connection refused"

You need to have a look at your database configuration in AdvancedBan or your configuration for the MySQL/MariaDB server itself, there is a missmatch.

// T

**Comment by flashbtw** [comment]
yup, my MariaDB Server was overloaded (I had to edit some things in the config).
Anyway thanks for the help!
