### ISSUE TITLE
Not an issue per-say, but more of a request

### ISSUE THREAD

**Issue by PyricDemon** [DevLeoko/AdvancedBan#509]
Not an issue, but a request.
Could you add support for Velocity a bungeecord alternative?

**Comment by Hopefuls** [comment]
Please refer to the template nonetheless.

There's currently an ongoing pr for velocity.

**Comment by PyricDemon** [comment]
The where? I'm not very familiar with github yet. Also I did look at the 7 open pr's before I opened this issue, but I didn't see anything about it. I was unsure how to make my own as it made me pick directories to where to create it and none of them seemed right, my bad.

**Comment by A248** [comment]
Closing in favor of #517
