### ISSUE TITLE
Specific server banning

### ISSUE THREAD

**Issue by YourDoubleN** [DevLeoko/AdvancedBan#51]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 N/a
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungee
 
_What server version (/version) are you using?_
N/a

_Please provide the EXACT steps required to reproduce the problem..._
1. N/A
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any aditional information below._

Is there a way to ban players from a specific server and not the whole network in whole?

**Comment by dutchy1001** [comment]
Only if you have the plugin installed per server. 
You can't have 1 MySQL, each server needs it's own (or the default data.yml).
We don't recommend this but it is possible.
