### ISSUE TITLE
A way to make the punishment announcement get announced to everybody?

### ISSUE THREAD

**Issue by MaxDaFoxHybridz** [DevLeoko/AdvancedBan#510]
More of a question than an issue. But is there a way to make the punishment announcement be announced to everybody other than Op's. I have tested it with an alt that is not opped and it didnt show the punishment message. Either i tested it wrong or im suppose to do someting with the settings. Is there a way to configure?

**Comment by averwhy** [comment]
Give the `.notify` permission to everyone

**Comment by MaxDaFoxHybridz** [comment]
alright thanks
