### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by Skestle01** [DevLeoko/AdvancedBan#52]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
Recent
 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Spigot
 
_What server version (/version) are you using?_
1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. I created a new layout called Blacklist
2.I restarted my server
3.I tried blacklisting a player and it didn't work
4. yes i did watching videos on how to make a new layout

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any additional information below._

**Comment by dutchy1001** [comment]
Would be nice to have that "layout" posted here to see what is going wrong.
What do you mean with "blacklisting", same as banning a player from the server?
Can you give the command used for your "blacklist" layout?

ps.
"resent" was never a version name, be more specific and add the version number.

**Comment by Skestle01** [comment]
it version 2.0.6

**Comment by md678685** [comment]
@Skestle01
* What command did you use to "blacklist"?
* Can you post your full config on [Pastebin](http://pastebin.com/) and give us the link to it?

**Comment by Skestle01** [comment]
i used /ban {player}  @Blacklist

**Comment by DevLeoko** [comment]
Thanks for the great support @md678685 and @dutchy1001

@Skestle01 if you don't post your layout-file within 48 hours this issue will be closed

**Comment by Skestle01** [comment]
i removed the plugin since it didn't even work correctly

**Comment by dutchy1001** [comment]
The plugin works fine, if you don't allow us to help that is not the plugins fault but a lack on your side.
