### ISSUE TITLE
Error on Tempban layout/ reason

### ISSUE THREAD

**Issue by ItzRonaldMLG** [DevLeoko/AdvancedBan#529]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.17.1

_Please provide the EXACT steps required to reproduce the problem..._
1. Temp-Ban someone.
2. The reason is a error in the layout, in /history it doesn't have that, reason is blanked out there

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include 
AdvancedBan log: https://pastebin.com/QFzZZ8Vy

_Add any additional information below._

**Comment by Hopefuls** [comment]
That error log does not contain any information regarding the issue you stated.

If you're able to, please provide a full log from start to finish.

**Comment by ItzRonaldMLG** [comment]
Everything in the server .log that is from AdvancedBan: https://pastebin.com/eRhVyMuZ
Messages.yml: https://pastebin.com/SpnunwhH
Screenshots attached below.
![Screenshot_4](https://user-images.githubusercontent.com/34626472/132367583-926b996a-9c49-4eab-b8d0-3573b1d7c876.png)
![Screenshot_3](https://user-images.githubusercontent.com/34626472/132367616-eb504231-a20c-4f8d-9026-f910200ae316.png)

**Comment by Hopefuls** [comment]
More information about your environment please. The reason on the ban command seems to be caused by another plugin or system interfering with your commands

**Comment by ItzRonaldMLG** [comment]
I found the problem, its something with InteractiveChat. I will contact the Dev.
