### ISSUE TITLE
"Web-Panel" Not detecting mysql tables.

### ISSUE THREAD

**Issue by Corcustos** [DevLeoko/AdvancedBan#53]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.06
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single Server
 
_What server version (/version) are you using?_
Spigot 1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. Enter MySQL information

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
http://prntscr.com/eaxggl

_Add any aditional information below._
AB isn't detecting my AdvancedBan Tables, but they are indeed there, and I'm using correct login information. I'm not sure why it's not. I'm trying to change it from my previous mysql database to a new one. Proof that the tables are there: http://prntscr.com/eaxgxr

**Comment by dutchy1001** [comment]
What port have you used?
There is a known issue that it only will use the default 3306 port for now

**Comment by Corcustos** [comment]
I am using the default 3306 port.

**Comment by dutchy1001** [comment]
then it should work, double check all MySQL fields for a typo

**Comment by Corcustos** [comment]
I directly copied and pasted everything from my hosting provider.

**Comment by Corcustos** [comment]
I'm trying to go to a new mysql database from the free hosting suggested on the spigot page. I just tested making a new test account and inserting the mysql information on the register page, and it worked perfectly. However, I can't change the already existing database linked to my actual account to the database I want, which is my own and not the free one so I don't have to check it every week to keep it there.

**Comment by dutchy1001** [comment]
I never used their services as I host it all at the same place, but I'm going to test this in a bit and will let you know this afternoon (UK time)

**Comment by Corcustos** [comment]
I meant I'm trying to switch from the free hosting to a new host, not to a database from the free hosts.

**Comment by dutchy1001** [comment]
ok, in that case it saves me checking the free host out.
Are you going to host it from home?

**Comment by Corcustos** [comment]
My server host also gives mysql hosting for people who buy premium packages. I have that, which gives me a mysql database. That is the database that I want to use. Sorry for the late reply, I'm over in the US so it was about 5am for me when I last replied.

**Comment by dutchy1001** [comment]
Have you checked what your host's MySQL port is? With many customers they can not have all the same 3306 port for the MySQL.

**Comment by Corcustos** [comment]
The plugin connects to the port fine. The MySQL.yml has the correct information and uses the same default 3306 port. It connect to the mysql fine and creates the tables. My issue is that the ban panel won't do what the plugin is doing fine using the same information. However, I'll check the port just in case.

**Comment by dutchy1001** [comment]
Are you talking about the web page to show bans??

**Comment by Corcustos** [comment]
Yes

**Comment by dutchy1001** [comment]
This is a totally different then the header of your post suggests, I wasn't aware this is about the **web** panel.
I deal with the plugin setup and ingame issue's, the web panel is something different as this is an external viewing and not an "ingame" issue.
If I get time tomorrow (UK times here) I might look into this.

**Comment by Corcustos** [comment]
Ah, sorry. The screenshot of the error is from the web panel I figured somebody would've picked up on that. I should've been more specific. >.<

**Comment by dutchy1001** [comment]
As I didn't pick up on your location (US) and your avatar being from Japanese animation I thought it got lost in translation.
I'll have a look tomorrow

**Comment by Corcustos** [comment]
I was able to fix my issue by completely deleting my webpanel account. Sorry for the inconvenience. Apparently there's an issue transferring databases, but it works fine if I make a new account.

**Comment by dutchy1001** [comment]
OK thx for letting us know you got it sorted.
