### ISSUE TITLE
Commands not showing up

### ISSUE THREAD

**Issue by Mcrich23** [DevLeoko/AdvancedBan#539]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.18 Spigot

_Please provide the EXACT steps required to reproduce the problem..._
1. Normal Install
2. Add ab.all to luckperms

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

_Add any additional information below._

All commands other than ban are just not registered and /ban is connected to an individual server.

**Comment by Hopefuls** [comment]
You installed advancedban wrong then, only install it on your bungeecord

**Comment by Mcrich23** [comment]
Reinstalled AdvancedBan and fixed it
