### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by itzchews** [DevLeoko/AdvancedBan#54]
_What version of AdvancedBan (`/AdvancedBan`) are you using? The most recent one as of right now
 
 
_What kind of server do you have (`Bungeecord/single server`)? Bungee
 
 
_What server version (/version) are you using? all my servers are 1.7.10-1.8.8 on my bungee

_Please provide the EXACT steps required to reproduce the problem..._
1. Download   http://www.mediafire.com/file/0goo53v6c6gg5e6/AdvancedBan.zip
2. Put it in the bunge eplugins folder
3. And it doesnt work

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any aditional information below.

It was working before i put in a custom config

**Comment by dutchy1001** [comment]
Use the provided downloads from the Bukkit or Spigot websites, custom downloads from MediaFire is dangerous and not suported

**Comment by itzchews** [comment]
Dude that is the custom config i added

**Comment by md678685** [comment]
Put your config on [Pastebin](http://pastebin.com/) and link it here.

**Comment by dutchy1001** [comment]
The way you put it in your post looks to me that you downloaded the plugin through MediaFire, I'm not taking any chance to download a file that could (I'm not saying it will) harm my pc.
I hope you will understand this.
As md678685 said, use pastebin to show config files.

You say "custom" config, what do you mean with that? 
Only use the configs that are provided by the plugin. The use of a "custom" config will not work to the code as it's not made for it.
The plugin works fine strait out the box (as they say). Adding the permissions correctly is one of the main issue's the plugin is not working correct. 
Have a look [here](https://www.spigotmc.org/threads/advancedban.74229/page-60#post-2168126) to see how and were to add the permissions.

**Comment by DevLeoko** [comment]
Thanks for the great support @md678685 and @dutchy1001

@itzchews if you don't reply to this issue within 48 hours it will be closed

**Comment by dutchy1001** [comment]
No answer after 5 days
