### ISSUE TITLE
No SSL / Deprecated com.mysql class

### ISSUE THREAD

**Issue by DonZekane** [DevLeoko/AdvancedBan#543]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungee/Waterfall
 
_What server version (/version) are you using?_
1. Waterfall v474 (1.18.1?)

_Please provide the EXACT steps required to reproduce the problem..._
1. Install plugin (or "have it")
2. Boot up the server
3. Read the console/log in horror

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
[Click Here](https://pastebin.com/AmiGgPXj)

_Add any additional information below._
I think it worked before I updated Java? I mean the plugin's connection to the database certainly worked a month or two ago.
This part is interesting:
```Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.```

Most of the times I go and complain to my host providers they end up rightfully telling me that the plugin is at fault so this is the first time I've addressed an issue to the dev directly.

**Comment by A248** [comment]
Closing in favor of #525 (this issue is a duplicate -- no worries though)
