### ISSUE TITLE
I have a problem with api!

### ISSUE THREAD

**Issue by jimmy57000** [DevLeoko/AdvancedBan#55]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 New
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single server for test
 
_What server version (/version) are you using?_
1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. I created a command with the API for test
    When I execute the command it returns nothing to me ..

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

Code: 

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import me.leoko.advancedban.manager.PunishmentManager;
import me.leoko.advancedban.manager.UUIDManager;

public class TestCommand
implements CommandExecutor
{
public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args)
{
  if (!(sender instanceof Player))
  {
    System.out.println("Commande disponible uniquement en joueur !");
    return true;
  }
  Player p = (Player)sender;
  UUIDManager.get().getUUID(p.getName());
        PunishmentManager.get().getCurrentWarns("jimmy57000");
		return false;
}
}

**Comment by DevLeoko** [comment]
Your code is just wrong and makes no sense at all :D so please improve your java skills before working with APIs.
