### ISSUE TITLE
[Feature Request] Notify permission for silenced punishments.

### ISSUE THREAD

**Issue by SiuanSong** [DevLeoko/AdvancedBan#557]
**Suggestion**
Add a permission node so staff will be able to view silenced punishments.

This would help prevent double punishments.  Currently, if I see someone doing something that requires immediate intervention with a punishment and I use -s, none of the other staff can see it.  And I can't see if anyone else did anything either, if they use -s.  This can sometimes lead to a person getting a double mute or warning for the same infraction and we wouldn't know until viewing their /history or the player alerts us to it.

**Comment by DevLeoko** [comment]
Implemented by @tWizT3ddreaMr in #624
