### ISSUE TITLE
Advanced ban issue: overlay doesnt exist

### ISSUE THREAD

**Issue by thomaspj10** [DevLeoko/AdvancedBan#56]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 The latest version
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
18.8

_Please provide the EXACT steps required to reproduce the problem..._
1. If I type: /ban (name) @hacking it says overlay doesnt exist but yesterday I tested it to but then it worked
2. I dont know if is because I have multiple bungeecord servers up? our the plugin broke when I restarted the server
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
It doesnt show error logs

_Add any aditional information below._

**Comment by dutchy1001** [comment]
can you post the Layout config through [pastebin](http://pastebin.com/) plz

**Comment by DevLeoko** [comment]
Thanks for the great support @dutchy1001

@thomaspj10 if you don't reply to this issue within 48 hours it will be closed
