### ISSUE TITLE
MySQL Access Denied Error

### ISSUE THREAD

**Issue by Kaludii** [DevLeoko/AdvancedBan#565]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Spigot
 
_What server version (/version) are you using?_
1.18.2

_Please provide the EXACT steps required to reproduce the problem..._
I'm using Database made through hostinger. Everytime I try to input the credentials, I get the error listed in the link below. I made sure the IP and the database info is correct.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
Error: https://pastebin.com/MazdNABY
Config: https://pastebin.com/4fQD7MTD

_Add any additional information below._

**Comment by Hopefuls** [comment]
Issue related to your MySQL database, could be the following:
- Password wrong
- Password correct, but does not allow connections from where you've tried to connect from.
