### ISSUE TITLE
Add blocked commands when muted 

### ISSUE THREAD

**Issue by Eufranio** [DevLeoko/AdvancedBan#57]
Some plugins have commands like /g and /l, where they can send messages in a specific channel. Would be nice if you add a config node that allow us to write the chat commands, so when a player gets muted, they wont be able to use the command. 

How would that work? 
In config, we put the commands that should be blocked on mute. 
If a player is muted, he will not be able to run those commands. Instead, they would get the muted message.

**Comment by dutchy1001** [comment]
There is already a section added for this in the config:
```
# This commands will be disabled for muted players
# A player woun't be able to bypass with eg "/minectaft:me"
MuteCommands:
- 'me'
- 'say'
- 'r'
- 'msg'
```

**Comment by DevLeoko** [comment]
Thanks for the great support @dutchy1001

@Eufranio if you don't reply to this issue within 48 hours it will be closed

**Comment by Eufranio** [comment]
Oh, forgot about this, and it works, thanks!
