### ISSUE TITLE
Unban IP not working.

### ISSUE THREAD

**Issue by Sxlect** [DevLeoko/AdvancedBan#572]
Im using advanced bans 2.3.0
 
 
Minehut with spigot
 
 
1.18

So I IP banned a player from my server, I tried doing /unbanip [username] and it still didn't let him join, so I tried doing /unbanip and then I did the IP linked to their username, and the IP that got sent in the console when they joined, I also did /pardon IP and pardon-IP and did both ips and usernames. In the chat, it said the IP and username were unbanned but they still couldn't join back. I've restarted the server, and they have refreshed the server IP

No error logs, it just said they were unbanned but the player still couldn't join

**Comment by Hopefuls** [comment]
Please use the issue format next time.

AdvancedBan does not have a command called /unbanip. To unban an IP, use /unban <IP>
