### ISSUE TITLE
hex color support

### ISSUE THREAD

**Issue by AkariDream** [DevLeoko/AdvancedBan#578]

**Comment by Hopefuls** [comment]
Hexcolors:

&F&F&F&F&F&F&F - you just replace F with whatever the hex code is, in that position, so like:

&#BE03F2 would be the normal way - if it had hex support, but you can also do it as:
&B&E&0&3&F&2 and that should give the same hex colour out

Advancedban only supports the second option

**Comment by AkariDream** [comment]
thx. ill try it later
if available. i will come back to close issue

**Comment by AkariDream** [comment]
it gives the color of the last bit formatting code
did i do something wrong?
![image](https://user-images.githubusercontent.com/71176602/180070200-a77fe999-1c4b-401c-ac69-e81e5aff8d5e.png)
![image](https://user-images.githubusercontent.com/71176602/180070240-337565f9-d153-414b-b7ff-162c56b85417.png)

**Comment by AkariDream** [comment]
or should i set hex color in layout in Messages.yml?

**Comment by AkariDream** [comment]
i gave up. i will continue to use the 16 colors that look boring to me.
this plugin is still good. Easy to configure, free, open source.
not everyone can writes code. if it will support the "first" in the future. then i would be grateful

**Comment by Faustyu1** [comment]
up hex

**Comment by postyizhan** [comment]
support https://github.com/DevLeoko/AdvancedBan/pull/662

**Comment by faustyu1** [comment]
WOW
