### ISSUE TITLE
BungeeCord Ban

### ISSUE THREAD

**Issue by GuilleCastillo** [DevLeoko/AdvancedBan#58]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
 AdvancedBan 2.0.6
_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord
 
_What server version (/version) are you using?_

1.9
_Add any aditional information below._
Hi, I have BungeeCord server
I have AdbancedBan with the MySql database... When i ban in the server 1 (for Example) and the user that i am baning is in the server 2 he dosent got ban in there
i want dat when i ban a user that is in a other server olso get ban there
Sorry my English i am form Chile conchetumadre

**Comment by dutchy1001** [comment]
As far I know this should be possible. I will (re)test this in a few when I have a second pc is available

**Comment by dutchy1001** [comment]
I just banned my alt who was on a different server then myself and it worked as expected. 
Were is the AdvancedBan plugin installed? On _all servers_ or only on the _bungeecord server_?

Any other information you can give were or how it's installed would be great.

**Comment by GuilleCastillo** [comment]
I have the plugin only in lobby

**Comment by dutchy1001** [comment]
ahhh this is were it goes wrong. 
You need to add the plugin to your bungeecord server and give permissions in the bungee config like explained [here](https://www.spigotmc.org/threads/advancedban.74229/page-60#post-2168126). If you only have it only in the "lobby" then the plugin thinks it's a single server, not a bungee setup therefore only players in the lobby can be banned.
For easy use to copy/paste the permissions needed you can use this post I made [here](https://www.spigotmc.org/threads/advancedban.74229/page-69#post-2246345).

**Comment by DevLeoko** [comment]
Thanks for the great support @dutchy1001

@GuilleCastillo if you don't reply to this issue within 48 hours it will be closed
