### ISSUE TITLE
No permissions?

### ISSUE THREAD

**Issue by MisfitNetwork** [DevLeoko/AdvancedBan#59]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 lastest
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.8

_Please provide the EXACT steps required to reproduce the problem..._
1. No matter what even in op it says I don't have permissions
2. I add permissions and it still does that exact same thing

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
no

_Add any aditional information below._
There isnt any errors so I have no idea!

**Comment by dutchy1001** [comment]
Were have you added the Advancedban.jar?
Were have you added the permissions?

**Comment by MisfitNetwork** [comment]
pex
and plugins folder in my hub server

**Comment by dutchy1001** [comment]
That's were it goes wrong
With a bungee setup the plugin goes in your bungeeserver plugins folder and the permissions in the bungee config as shown [here](https://www.spigotmc.org/threads/advancedban.74229/page-60#post-2168126)

**Comment by MisfitNetwork** [comment]
ah ok thanks man!
