### ISSUE TITLE
Error Database

### ISSUE THREAD

**Issue by Altexx87** [DevLeoko/AdvancedBan#597]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBan-Bundle-2.3.0-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord
 
_What server version (/version) are you using?_

BungeeCord
This server is running Waterfall version git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:47fa16d:431 by md_5

Spigot
This server is running CraftBukkit version 3096-Spigot-9fb885e-296df56 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. Conect MySQL Database
2. Join Server
3.Error!

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

LOG
https://pastebin.com/uaJDeurd

_Add any additional information below._
[BUNGEECORD_LOG.txt](https://github.com/DevLeoko/AdvancedBan/files/10294767/BUNGEECORD_LOG.txt)

**Comment by Hopefuls** [comment]
Hello,

that error sounds like you have tried to set a port within the hostname section on your config.yml, which is not required.

If you are using a different port that 3306, change the port value within the port setting in your config.yml.

**Comment by Altexx87** [comment]
@Hopefuls  Very thanks, it was that!
