### ISSUE TITLE
Wont let me run any commands

### ISSUE THREAD

**Issue by Jacobvs** [DevLeoko/AdvancedBan#60]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single
 
_What server version (/version) are you using?_
spigot 1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. run any ab command such as /kick darkm4tter saying hi
2. console says you are not allowed to kick darkm4tter
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any aditional information below._
i turned on pex debug and it says: 06.03 16:17:27 [Server] INFO User Darkm4tter checked for permission 'ab.kick.exempt', no match found (CACHE MISS)

**Comment by dutchy1001** [comment]
did you give the permissions in the pex file? If so what perms did you give.

**Comment by Jacobvs** [comment]
I gave all the permissions necessary, yet it doesnt work. I even tried from the console and it says the same thing.

**Comment by dutchy1001** [comment]
Ok maybe asking it in a different way, can you post the pex file?

**Comment by Jacobvs** [comment]
Yeah sorry: https://hastebin.com/onokavobut.yml

**Comment by dutchy1001** [comment]
have you tried as admin or as mod?

**Comment by Jacobvs** [comment]
yeah all of them and also op

**Comment by dutchy1001** [comment]
Still a vague answer again.
The permission ab.* is not a valid perm and as far I have seen is not working. Copy the perms you need from [here](https://www.spigotmc.org/threads/advancedban.74229/page-69#post-2246345) into your admin rank and try again (make sure the indentation is correct).

**Comment by Jacobvs** [comment]
I honestly think it could be a bug as ive tried running any of the commands from the console and from an opped player (both having access to all perms) and neither of them work. I can talk more tomorrow if you need my plugin list, console logs, or anything else.

**Comment by Jacobvs** [comment]
Also i did put those perms in with no luck

**Comment by dutchy1001** [comment]
It's not a bug the plugin works, no doubt about this. All commands work from ingame.
A console log might help and a new pex file with the perms added the correct way.

**Comment by Jacobvs** [comment]
Here's the new permissions: https://hastebin.com/wapuhiqele.php
Here's the console on startup: https://hastebin.com/unezabupuk.erl
and heres the console after executing an ab command (with pex debug mode): https://hastebin.com/jikutemuqo.sql

**Comment by DevLeoko** [comment]
In which permission group is the User you are trying to mute/ban?
Is the command working for other users?

Also, ab.* should work with PEX only BungeeCord seems not to support *-Perms

**Comment by Jacobvs** [comment]
Any group yt and below

**Comment by DevLeoko** [comment]
Are you able to ban "Any group yt and below" or not?

**Comment by Jacobvs** [comment]
No not able to ban any of the groups actually, not even through console

**Comment by DevLeoko** [comment]
But in the logs you have posted above you tried to ban Darkm4tter, who is in the owner group

**Comment by Jacobvs** [comment]
Yeah sorry that's confusing as I left out the part of the config where I demoted him to t1

**Comment by DevLeoko** [comment]
did you maybe add the name of the user in the config.yml to the offline exempts?

**Comment by dutchy1001** [comment]
or is Darkm4tter still OP?
He is exempt as far the debug is telling.

**Comment by Jacobvs** [comment]
Ugh im actually so dumb. Ofc its the offline exempts. Thanks so much for the help anyways!
