### ISSUE TITLE
Can't use special characters on MYSQL (password)

### ISSUE THREAD

**Issue by JoeDalton9027** [DevLeoko/AdvancedBan#603]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
latest
 
 
_What kind of server do you have (`Bungeecord/single server`)?_
Paper 1.19.3 - build 381
 
 
_What server version (/version) are you using?_
1.19.3

_Please provide the EXACT steps required to reproduce the problem..._
1. Set UseMySQL: true
2. Entering database informations
3. When using a " # " character into my password, the plugin can't connect to database, but, when special character is not set, plugin can connect to database, ths issue comes when the password contain special character.
[latest.log](https://github.com/DevLeoko/AdvancedBan/files/10472669/latest.log)

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

the issue, displays the same thing that is into " latest.log " file

_Add any additional information below._

Please, is there any way to use special char?
[latest.log](https://github.com/DevLeoko/AdvancedBan/files/10472671/latest.log)

**Comment by Hopefuls** [comment]
the issue seems to be more related to your password being incorrect

> but, when special character is not set, plugin can connect to database

which I assume you're referring to it connecting to your database correct?

**Comment by JoeDalton9027** [comment]
Hello
I'm 100% sure database information is correct.

The plugin just don't support special chars.

Le dim. 22 janv. 2023, 01:35, Aurel Ballin ***@***.***> a
écrit :

**Comment by Hopefuls** [comment]
I was unable to reproduce your issue with a password with the following text: `A-Password!!!With###Hashtags`

Relevant configuration section, this was the only thing I have changed on AdvancedBan:
```
# If set to false all bans will be saved locally in a HSQLDB-Database
UseMySQL: true

MySQL:
  IP: localhost
  DB-Name: AdvancedBan
  Username: root
  Password: A-Password!!!With###Hashtags
  Port: 3306
  Properties: 'verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf8'
  ```
  
  Tested on spigot 1.19 on a linux virtual machine, using the latest version of AdvancedBan, which is 2.3.0.
  
  The error you have provided is telling me that whatever password you have provided, is incorrect. I am still unsure what you're referring to with "but, when special character is not set, plugin can connect to database". This sounds like to me as if you're trying to add a # to your password, but that being the incorrect one as you have not changed it on your database-side.

**Comment by gamer50082** [comment]
can be reproduce

**Comment by gamer50082** [comment]
maybe try another password

**Comment by Hopefuls** [comment]
If i actually use a password that is incorrect, by just adding a # to the password field, then it is intentional that it does not work, as the password does not match.

@JoeDalton9027 check if you're able to connect with the # based password through tools such as heidisql.

**Comment by Hopefuls** [comment]
I am getting the exact same nature of error when providing a wrong password, as indicated by the exception message of `java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)`

![image](https://user-images.githubusercontent.com/47116705/213920172-4baf2c6e-fc3f-4ad0-aac1-74837c9f43bd.png)

**Comment by JoeDalton9027** [comment]
So how could you explain this ?

First screen is database informations
Second, plugin config.yml

![Screenshot_2](https://user-images.githubusercontent.com/114250119/213924500-b77dd5f6-282d-4c59-9e85-4832d74b448e.png)
![Screenshot_3](https://user-images.githubusercontent.com/114250119/213924506-fe0df170-3c44-4316-84c9-d34ca1c810a0.png)

**Comment by JoeDalton9027** [comment]
After checking informations, reload the server, then, got this.
[latest.log](https://github.com/DevLeoko/AdvancedBan/files/10474756/latest.log)

**Comment by Hopefuls** [comment]
The way YAML is reading that is as a comment due to the starting `#` on your password. You can read more about the YAML Usage regarding comments [here](https://yaml.org/spec/1.2.2/#:~:text=an%20explicit%20comment%20is%20marked%20by%20a%20%E2%80%9C%23%E2%80%9D%20indicator.%20comments%20are%20a%20presentation%20detail%20and%20must%20not%20be%20used%20to%20convey%20content%20information.).

This is not a bug, but intentional behaviour by the YAML Language. In order to have the plugin correctly read it, encase it with quotation marks.

Example:

```yaml
MySQL:
 ...
 Password: "#bbMIX570"
 ```
 
 This should then allow AdvancedBan to correctly parse the YML file and get the password to use to connect with your Database.

**Comment by Hopefuls** [comment]
> After checking informations, reload the server, then, got this. [latest.log](https://github.com/DevLeoko/AdvancedBan/files/10474756/latest.log)

This error is caused by the database still being disconnected on reload. A server restart is required to apply database credentials-related changes.

**Comment by JoeDalton9027** [comment]
I will try thanks 😉

Le dim. 22 janv. 2023, 17:26, Aurel Ballin ***@***.***> a
écrit :

**Comment by JoeDalton9027** [comment]
It works like this, thank you for help !
