### ISSUE TITLE
plugin has issues while using "CMI" plugin

### ISSUE THREAD

**Issue by SistineFibelKen** [DevLeoko/AdvancedBan#604]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0 Stable
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single Server - paper 1.19.3
 
_What server version (/version) are you using?_
git-Paper-420 (MC: 1.19.3)

_Please provide the EXACT steps required to reproduce the problem..._
1.Download CMI-9.3.1.5 CMILib1.2.4.5 AdvancedBan and install to the server
2.Start the Server , join it using advancedban:kick command.
3.nothing happen,and no error
4.some command still work,but the main command all may blocked by cmi?

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
![20230226015220](https://user-images.githubusercontent.com/57359004/221372108-c00a1195-6327-4ffa-873f-923719fbd3bb.png)
![QQ20230226015254](https://user-images.githubusercontent.com/57359004/221372127-5eee68f1-ea0c-4f20-b2f2-538efb63773e.png)

_Add any additional information below._
Server only have CMI-9.3.1.5 CMILib1.2.4.5 AdvancedBan three plugins.
![QQ20230226015606](https://user-images.githubusercontent.com/57359004/221372264-08e9a781-43dc-4a6b-81c9-32972f31379e.png)

https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/updates

**Comment by Hopefuls** [comment]
AdvancedBan is not having issues, its unable to register commands as CMI has done that already.

If you're using a CMI configuration that uses commands that AdvancedBan uses, try removing these and check again.

**Comment by SistineFibelKen** [comment]
> AdvancedBan is not having issues, its unable to register commands as CMI has done that already.
> 
> If you're using a CMI configuration that uses commands that AdvancedBan uses, try removing these and check again.

Thanks for the reply.what should I do for solve the CMI register commands first problem ? In my other version server like paper 1.19 it run without any problem.

**Comment by SistineFibelKen** [comment]
> AdvancedBan is not having issues, its unable to register commands as CMI has done that already.
> 
> If you're using a CMI configuration that uses commands that AdvancedBan uses, try removing these and check again.

OK , thanks for again , I tried to adjust the startup order, and now it has been successfully registered.
