### ISSUE TITLE
Obtaining .jar development branch file for velocity

### ISSUE THREAD

**Issue by YesItsWaffle** [DevLeoko/AdvancedBan#606]
How can I get a .jar file from the development branch? I need it the plugin for velocity as I am trying to implement a server-wide punishment system.

**Comment by Hopefuls** [comment]
Within our server (check the spigot page for the discord server) is s testing channel you can get access to by selecting a role. It is in that channel then.

Keep in mind that:
- the velocity version is unmaintained
- has issues/reported not working

Use it at your own risk.
