### ISSUE TITLE
Unable to enable AdvancedBan on server start

### ISSUE THREAD

**Issue by ASCIIcat** [DevLeoko/AdvancedBan#61]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_ 2.0.6
 
 
_What kind of server do you have (`Bungeecord/single server`)?_ single
 
 
_What server version (/version) are you using?_ Paper Spigot 1.11.2

_Please provide the EXACT steps required to reproduce the problem..._
1. Start server
2. ???
3. No profit

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
[http://pastebin.com/TuMXUkh5](http://pastebin.com/TuMXUkh5)

_Add any aditional information below._

**Comment by dutchy1001** [comment]
Try and see if disabling MassiveLag plugin helps, seems that interferes with the startup.
``` at com.massivecraft.massivelag.inject.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:215) [MassiveLag.jar:?]```
If MassiveLag is the cause then that needs looking into as it's a way to expensive plugin not to use after you bought that.

**Comment by ASCIIcat** [comment]
Tried starting the server without MassiveLag still getting the following error:
`java.lang.NullPointerException: Name is null
        at java.lang.Enum.valueOf(Enum.java:236) ~[?:1.8.0_121]
        at me.leoko.advancedban.utils.PunishmentType.valueOf(PunishmentType.java:6) ~[?:?]`

Pastebin of full error:
[http://pastebin.com/D01AzkE8](http://pastebin.com/D01AzkE8)

**Comment by dutchy1001** [comment]
could you upload a full startup log?

**Comment by ASCIIcat** [comment]
I have tried grabbing it again just in case there might have been an update.
Here is the startup log of my server:
[http://pastebin.com/ZRRL8v9x](http://pastebin.com/ZRRL8v9x)

**Comment by DevLeoko** [comment]
There seems to be a problem with the stored punishments. Do you use MySQL or File?

**Comment by dutchy1001** [comment]
It seems that the issue might be with the "PluginClassLoader" as shown in a few lines before the error message. This is also happening for some other plugins, this indicated to me that there is an other plugin that causes this.

**Comment by dutchy1001** [comment]
Their using file for data storage.

**Comment by DevLeoko** [comment]
Then please paste the file into this validator and check if there are any problems.
http://codebeautify.org/yaml-validator
If there aren't any problems but it still does not work either delete the file (so all punishments get reset) or paste in here so we can have a look at it ;)

**Comment by ASCIIcat** [comment]
Deleted the data.yml and tried loading it again got the following:
[http://pastebin.com/N0yu3ab9](http://pastebin.com/N0yu3ab9)

**Comment by DevLeoko** [comment]
This error normally occurs when there is an incompatible plugin.
Could you please post a list of plugins you are using?
Do you know any of your plugins that uses the same commands as AdvancedBan?

**Comment by dutchy1001** [comment]
I think the issue starts here 

```[17:14:40] [Server thread/INFO]: Set PluginClassLoader as parallel capable```

**Comment by DevLeoko** [comment]
Thanks for the great support @dutchy1001

@ASCIIcat if you don't reply to this issue within 48 hours it will be closed

**Comment by md678685** [comment]
@ASCIIcat Can you post the output of `/version` and `/plugins`? I'm running Paper 1.11.2 with no issues.
