### ISSUE TITLE
Problem with Database

### ISSUE THREAD

**Issue by TomHo41** [DevLeoko/AdvancedBan#611]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord 
 
_What server version (/version) are you using?_
1.19 bungeecord

_Please provide the EXACT steps required to reproduce the problem..._
I used /unpunish or any other CMD of Advancedban

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
https://pastebin.com/SPXTj1B5 - latest.log

```
15:06:45 [INFO] [AdvancedBan] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
```

_Add any additional information below._

**Comment by Hopefuls** [comment]
A table has been deleted or renamed within your database, that issue is unrelated to AdvancedBan.
