### ISSUE TITLE
Error command when tabulation (/ban)

### ISSUE THREAD

**Issue by nsvk13** [DevLeoko/AdvancedBan#612]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 velocity & smp
 
_What server version (/version) are you using?_
1.19.2 | Puffrefish.

_Please provide the EXACT steps required to reproduce the problem..._
1. When you tab in the /ban command, you get an error.
Attached the information below, on pastebin.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
nothing

_Add any additional information below._
https://pastebin.com/Kr6bYLVb

**Comment by Onako2** [comment]
Could you include a screnshot if it shows anything on the client?

**Comment by nsvk13** [comment]
You would have answered me in 2024.
