### ISSUE TITLE
When somebody changes their username, they get unpunished.

### ISSUE THREAD

**Issue by JeffreyRCGithub** [DevLeoko/AdvancedBan#620]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single server
 
_What server version (/version) are you using?_
This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
You are running the latest version
Previous version: git-Paper-431 (MC: 1.19.3)

_Please provide the EXACT steps required to reproduce the problem..._
1. Get any type of punishment.
2. Change your username.
3. Your punishment is now gone.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

_Add any additional information below._

**Comment by Hopefuls** [comment]
Are you using a server in cracked/offline mode?

If so, that is a limitation in cracked servers entirely. Consider setting online mode on your server to avoid name changes unbanning users, as bans are then associated with their uuid.

**Comment by JeffreyRCGithub** [comment]
I’m using waterfall so I must have offline mode. When I said single server in the question “What kind of server do you have (Bungeecord/single server)?” I meant I wasn’t using the AdvancedBan plugin on the waterfall proxy server.

**Comment by Hopefuls** [comment]
> I’m using waterfall so I must have offline mode. When I said single server in the question “What kind of server do you have (Bungeecord/single server)?” I meant I wasn’t using the AdvancedBan plugin on the waterfall proxy server.

advancedban does not support being installed on the subserver, put the plugin on your proxy, remove it from your subserver and that should do the trick

**Comment by JeffreyRCGithub** [comment]
I can’t do that because I’m using a host called Minefort which is like Minehut where you don’t have access to the proxy server.

**Comment by Hopefuls** [comment]
Then AdvancedBan is unfortunately not the plugin you're looking for, as it will cause issues like that if not being properly installed

**Comment by Zhou-Shilin** [comment]
Why don't you try `/banip`?

**Comment by JeffreyRCGithub** [comment]
The command `/banip` is pretty extreme if you didn’t know so I don’t want to use that and `/banip` doesn’t block the username directly it blocks the IP so if someone was to get a VPN on, they could still join.

**Comment by Zhou-Shilin** [comment]
> The command `/banip` is pretty extreme if you didn’t know so I don’t want to use that and `/banip` doesn’t block the username directly it blocks the IP so if someone was to get a VPN on, they could still join.

If that's the case, then you'd better turn on the online mode.

**Comment by JeffreyRCGithub** [comment]
I don’t know if you read the previous replies, but I need offline mode for waterfall.

**Comment by Zhou-Shilin** [comment]
Maybe you can try to implement "fake online mod" through a plugin? Ask players to provide accessToken when they first log in, and then verify that the accessToken is paired with the player's uuid. I'm not sure if there is such a plugin, but I'm sure it can be implemented.

**Comment by JeffreyRCGithub** [comment]
My server Is public so that wouldn’t be practical.

**Comment by Onako2** [comment]
The subserver still gets the real UUID of the player. When the subserver recieves the UUID it links the UUID with a username. The server will notice once someone changes their username. Once the username changes you could ban the new player and unban the old player or just directly edit it in the database.

**Comment by A248** [comment]
You have to tell AdvancedBan to use the correct "UUID mode." By default, it will auto-detect if your server is cracked and therefore use player names. There's a config option which lets you set the UUID mode to "intern."

Make sure your backend server has player information forwarding correctly configured, of course.
