### ISSUE TITLE
Join while banned

### ISSUE THREAD

**Issue by einsblack** [DevLeoko/AdvancedBan#628]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
Latest Bungeecord (Stable)

_Please provide the EXACT steps required to reproduce the problem..._
1. /ban (User) or /tempban (User)
2. Ban the User
3. The User rejoint without any problems while banned

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
https://pastebin.com/dXhvt6YE

_Add any additional information below._
Users can just join while banned

_Example video & Images._
https://github.com/DevLeoko/AdvancedBan/assets/69310929/af453347-ab33-4dfe-945c-a5c945a0878b
![image](https://github.com/DevLeoko/AdvancedBan/assets/69310929/c880afa0-e146-4a9f-98ed-dbe959be659e)

**Comment by Hopefuls** [comment]
This looks like a Cloudnet setup to me:

Are you using multiple Proxies that have AdvancedBan on them? AdvancedBan may cause issues on a cloudnet setup.

**Comment by einsblack** [comment]
I am indeed usign CloudNet and I am using one Proxy and Subservers and Advancedban is installed on the Proxy

**Comment by einsblack** [comment]
Problem not working good with CloudNet
