### ISSUE TITLE
Banned After Opping Self

### ISSUE THREAD

**Issue by Seemlyhaddock47** [DevLeoko/AdvancedBan#633]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
2.3.0 (Latest)
_What kind of server do you have (`Bungeecord/single server`)?_
 
 Single Server
_What server version (/version) are you using?_

1.20.2
_Please provide the EXACT steps required to reproduce the problem..._
1.Join Server 
2.Op yourself via console or playerlist (aternos) 
3.Dont need third step already banned at that point 

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
https://pastebin.com/AdgE9wiy

_Add any additional information below._
The reason for ban being your not on the op list oh and everytime it removes me from the op list but doesnt delete previous ops from the list

**Comment by Seemlyhaddock47** [comment]
![image](https://github.com/DevLeoko/AdvancedBan/assets/99023393/7813c994-fd96-4330-b62b-ca60060dfb35)

**Comment by Hopefuls** [comment]
AdvancedBan does not provide features that have anything to do with Operator or keeping people from being opped, you're likely using a plugin that does so, but uses the /ban command to then ban you, which is provided by advancedban.

**Comment by Hopefuls** [comment]
Also, your logs provided are just local file links and I do not have access to your files lol.

**Comment by Seemlyhaddock47** [comment]
Yes sorry i read into it just after and i have a plugin called anti op it just wouldnt let me see it before on my plugin list
