### ISSUE TITLE
When called from the API, "this.mi" is null

### ISSUE THREAD

**Issue by ichiru5555** [DevLeoko/AdvancedBan#639]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 bungeecord
 
_What server version (/version) are you using?_
latest

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
Cannot invoke "me.leoko.advancedban.MethodInterface.log(String)" because "this.mi" is null

_Add any additional information below._
I want to run getMute from the API, but I get the error "Cannot invoke "me.leoko.advancedban.MethodInterface.log(String)" because "this.mi" is null".
Can you tell me how to solve this?

**Comment by Hopefuls** [comment]
This is caused by incorrect maven pom.xml settings, ensure you're not shading/including advancedgui into your exported jar.

**Comment by ichiru5555** [comment]
I have not included Advancedgui in the dependencies in pom.xml.

**Comment by Hopefuls** [comment]
How have you included advancedban then?

**Comment by ichiru5555** [comment]
`<dependency>
    <groupId>com.github.DevLeoko</groupId>
    <artifactId>AdvancedBan</artifactId>
    <version>v2.3.0</version>
</dependency>`

**Comment by Hopefuls** [comment]
That is including advancedban through the pom.xml.

Take a look at https://howtodoinjava.com/maven/maven-dependency-scopes/ to understand how to set scopes on maven dependencies.

**Comment by ichiru5555** [comment]
Was it wrong to write the code written in README.md in pom.xml?

**Comment by Hopefuls** [comment]
> Was it wrong to write the code written in README.md in pom.xml?

It does not have the scope set as I've provided above, you need to include that in order to tell maven to not include the actual advancedban jar into the compiled jar.

**Comment by ichiru5555** [comment]
Is the error "Cannot invoke "net.md_5.bungee.protocol.MinecraftEncoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null" coming from AdvancedBan?

**Comment by Hopefuls** [comment]
What is the full stacktrace/full error? There should be more to it

**Comment by ichiru5555** [comment]
No, it was only this one sentence.

**Comment by ichiru5555** [comment]
The above problem has been resolved.
I would like to mute it, is the following code correct?
`
public void getMute(String uuid){
        PunishmentManager.get().getMute(uuid);
}
`

**Comment by ichiru5555** [comment]
I would like to mute it, is the following code correct?
`manager.getPunishments(player.getUniqueId().toString(), PunishmentType.MUTE, true);`

**Comment by Hopefuls** [comment]
That is not correct, take a look at the uuid manager

**Comment by ichiru5555** [comment]
Thank you
