### ISSUE TITLE
Unable to UnbanIP / "Player not banned"

### ISSUE THREAD

**Issue by yPedx** [DevLeoko/AdvancedBan#64]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 v2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single server.
 
_What server version (/version) are you using?_
1.8.9

_Please provide the EXACT steps required to reproduce the problem..._
1. /banip "I used a player's name"
2. Nothing
3. Nothing

If I tried /unban "player" it only told me the player wasn't banned. I can't unban the player.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No errors.

_Add any aditional information below._
Not even essentials /unbanip works

**Comment by yPedx** [comment]
Sorry !
Fixed by using /unpunish

**Comment by dutchy1001** [comment]
you can also use /unban for unbanning an IP
