### ISSUE TITLE
Error on /banlist command call

### ISSUE THREAD

**Issue by Mrflaxe** [DevLeoko/AdvancedBan#646]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0-REALESE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Velocity
 
_What server version (/version) are you using?_
1.16.5

_Please provide the EXACT steps required to reproduce the problem..._
I suggest,
1. you tempban a player
2. Wait for tempban to expire
3. try to view ban list via /banlist

I'm not sure that it will reproduce the error somewhere else, but I get this exception every time I try to enter the command

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
https://pastebin.com/kTcUcybE
[latest.log](https://github.com/user-attachments/files/17246385/latest.log)

_Add any additional information below._

**Comment by Hopefuls** [comment]
Can you elaborate what "patched_jar" is? Have you modified spigot?

**Comment by Mrflaxe** [comment]
> Can you elaborate what "patched_jar" is? Have you modified spigot?

Yes, we did. Not me personally, but one person from my team

**Comment by Hopefuls** [comment]
Please ensure the issue you're facing is reproducible using a non modified spigot version.

We do not provide support for issues caused by modified spigot versions.
