### ISSUE TITLE
Support FastLogin/provided UUIDs

### ISSUE THREAD

**Issue by Eufranio** [DevLeoko/AdvancedBan#65]
Hey, could you add support for FastLogin? Cracked players have cracked UUIDs, and premium players have premium UUIDs when using it. Banning premium players is being counted by their name, so they can still log in if they change the username. What if you use the provided UUID when banning if the player is online, and/or hook into FastLogin (if it's loaded) to check if the player is premium? If so, use premium UUID, otherwise use the cracked one...

**Comment by DevLeoko** [comment]
You could try to switch to internal uuid in the config.yml maybe this works

**Comment by DevLeoko** [comment]
did it work? can I close this issue?

**Comment by Eufranio** [comment]
Yes it worked, sorry!
