### ISSUE TITLE
Failed to fetch your uuid

### ISSUE THREAD

**Issue by FreeKillGR** [DevLeoko/AdvancedBan#67]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 The most new i downloaded it today 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
Bungeecord but i have the same problem on single server
_What server version (/version) are you using?_

1.10.2 but it supports 1.11 with viavesrion 
_Please provide the EXACT steps required to reproduce the problem..._
1.When you log in to the server
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

04.04 12:46:51 [Server] INFO Error -> Server returned HTTP response code: 429 for URL: https://api.mojang.com/users/profiles/minecraft/howdoinamet=1491302810919
04.04 12:46:51 [Server] INFO !! Failed fetching UUID of howdoiname
04.04 12:46:51 [Server] INFO !! Could not connect to REST-API under https://api.mojang.com/users/profiles/minecraft/%NAME%t=%TIMESTAMP%
04.04 12:46:51 [Server] INFO Trying to fetch UUID form BackUp-API...
04.04 12:46:51 [Server] INFO !! Failed fetching UUID of howdoiname
04.04 12:46:51 [Server] INFO !! Could not find key 'uuid' in the servers response
04.04 12:46:51 [Server] INFO !! Response: OK
04.04 12:46:51 [Server] INFO !! !! Warning we have not been able to fetch the UUID of the Player howdoiname
04.04 12:46:51 [Server] INFO !! Make sure that the name is spelled correctly and if it is change your UUID-Fetcher settings!
_Add any aditional information below._

**Comment by DevLeoko** [comment]
Error:  429	Too Many Requests	
So you can try to either switch to internal UUID-Fetcher or disable it completely

**Comment by FreeKillGR** [comment]
if i disable the UUID-Fetcher and someone who is banned changes his name he will be able to join back in right ?

**Comment by DevLeoko** [comment]
ya

**Comment by FreeKillGR** [comment]
Well then this obviously not an option anything else i can do?

**Comment by DevLeoko** [comment]
> So you can **try to either switch to internal UUID-Fetcher or** disable it completely

**Comment by FreeKillGR** [comment]
If i switch to the internal uuid-Fetcher will they be able to join with a chnaged name ? 

and the settings to swith to it are these ?

UUID-Fetcher:
  # Disable for cracked servers
  Enabled: false
  Intern: true
  REST-API:
    URL: "https://api.mojang.com/users/profiles/minecraft/%NAME%?at=%TIMESTAMP%"
    Key: "id"
  BackUp-API:
    URL: "https://us.mc-api.net/v3/uuid/%NAME%"
    Key: "uuid"

**Comment by DevLeoko** [comment]
you will have to change
Enabled: to true
and Intern to true

to check if the internal UUID matches the real UUID just do /systemprefs 
but if your server runs on online mode it should match

**Comment by bolleboor** [comment]
At my server is says none
28.04 16:54:41 [Server] INFO Your UUID (Intern) » none
28.04 16:54:41 [Server] INFO Server-Time » 16:54
28.04 16:54:41 [Server] INFO AdvancedBan v2 SystemPrefs
