### ISSUE TITLE
No Perms

### ISSUE THREAD

**Issue by 4lpal1632** [DevLeoko/AdvancedBan#68]
I am using the latest version of AdvancedBan
 
 
I have it in my bungee plugins folder
 
 
The server version is 1.11.2

I have owner rank on server which has '*' permissions (all permissions) but it says i have no permissions. Even when I op myself it doesnt work. Is it because I have it in my bungee plugins folder?

Just says i have no perms

**Comment by Beelzebu** [comment]
When the plugin is in bungee, you need add the permissions in the config.yml of the bungee, or use a permission plugin that has bungee support, if you use PEX, you should use this plugin https://www.spigotmc.org/resources/bungeepexbridge.10839/ but I recommend use LuckPerms https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/ that has bungee support and has more features.

**Comment by DevLeoko** [comment]
Please tell us if this has worked for you and if it did close the issue
