### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Minken** [DevLeoko/AdvancedBan#69]
Please take a look at this[1] GitHub issue for another project. The same license rules applies to this project.
[1] = https://github.com/mastercake10/TimeIsMoney/issues/11

Thanks,
Minken

**Comment by ItzSomebody** [comment]
Well seen, not that anything can really be done tho since it is open-sourced xD

**Comment by DevLeoko** [comment]
Sorry for the delay, just added a GNU-License
https://github.com/DevLeoko/AdvancedBan/commit/38a77e9c605de9b836ef2018c8807ee441473548
