### ISSUE TITLE
Problem with working

### ISSUE THREAD

**Issue by BluetoDark** [DevLeoko/AdvancedBan#71]
I have a spigot server with luckperms for the permission I run spiggot 1.11 r0.1 and I`m using advancedban 2.0.6 I Use it for my server and the plugin works but you can`t use the commands so I can`t ban or do somthing else Maybe it`s beaucase essentials but I don`t know it uploads to it to date but not ban the people

**Comment by DevLeoko** [comment]
If you request support please use the Issue-Template:

What version of AdvancedBan (/AdvancedBan) are you using?

What kind of server do you have (Bungeecord/single server)?

What server version (/version) are you using?

Please provide the EXACT steps required to reproduce the problem... 1. 2. 3.

Any error/log post it through pastebin.com and link it here.

Add any aditional information below.

**Comment by DevLeoko** [comment]
@BluetoDark if you don't reply to this issue within 48 hours it will be closed
