### ISSUE TITLE
Help with Permissions

### ISSUE THREAD

**Issue by Techno3600** [DevLeoko/AdvancedBan#72]
Hello,

I was wondering if I could make a way that Moderators couldn't ban other Moderators but Owners could?

**Comment by DevLeoko** [comment]
There is already a level-based exempt system planned but it may take some time to finish

**Comment by DevLeoko** [comment]
This feature has been implemented in our newest release: https://www.spigotmc.org/resources/advancedban.8695/update?update=321631
