### ISSUE TITLE
Server doesn't start while I have this plugin

### ISSUE THREAD

**Issue by Sollembum78** [DevLeoko/AdvancedBan#73]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.0.6.
 
_What kind of server do you have (`Bungeecord/single server`)?_
 I am having this problem on both spigot and bungeecord. I install it on bungeecord and remove from all spigots - bungee doesn't start. I remove it from bungee and put on some spigots - spigots don't start.
 
_What server version (/version) are you using?_
The very latest bungeecord and spigot for today.

_Please provide the EXACT steps required to reproduce the problem..._
Happens at random. Sometimes server will not start, hanging at moment of loading the plugin. It's connected to mysql, but mysql server is perfectly accessible by all the other plugins.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
No errors, crashes or anything, at all. Pause forever on loading, that's it.

_Add any aditional information below._
First the problem. Ingame, when I try to ban or mute someone it gives message that some error occured (no details here) and no effect. I restart server to resolve this and it hangs in moment when this plugin is loading. No errors, no crashes or "stopped responding" or anything. It just pauses forever, I can wait like 5 minutes and it will stay on same spot, with no huge load on cpu or anything.

I've been using this plugin for like 5-6 months on spigot, and it worked perfectly fine, then I got this problem. Later, in day or so it fixed itself, I moved it to bungeecord, coz that was necessary for current setup, and in few days got this problem again.

Config of plugin is mostly default, with messages translated into my language. I'm using it for offline mode server with no uuid fetching, and all data is stored in mysql. Mysql server is same host as my bungee and spigots, so everything is localhost. Mysql server is not overloaded, I use it only for few more plugins like economy and registration. At times that this problem occurs all other plugins keep working fine, both already loaded and ones that load if I restart some spigots. Mysql database is pretty much default setup with utf8 encoding to ensure my language ban reasons are displayed properly.

No changes in overall setup. Same host as it was few months ago, no recent updates on system, mysql server or java or anything else. It works more than month with absolutely no changes to system or hardware. Only changes are updates of spigot and bungeecord to latest versions, from official sources. Can this be reason?

**Comment by DevLeoko** [comment]
Sorry for the delay, but I've been busy :P

As there is no error or crash message it makes it really hard for me to see where the problem is.
Normally there is a timeout after which the server crashes when there is a plugin blocking the main thread (as it seems to be in your case) so try to wait a bit longer (like 15min) then there should come up a long crash message.

**Comment by Sollembum78** [comment]
Now it's working again, happens at random, but next time I will post all reports here, if I can get them. Thanks for comment :)

**Comment by DevLeoko** [comment]
Okey then just reopen the issue if there are any problems ;)

**Comment by Sollembum78** [comment]
Now I get this:
https://pastebin.com/KRT0Wepb

...no connection to the MySQL-Server please restart...

Are there common reasons why this happens? My bungeecord is running for like 3-4 days, with around 100 online players all the time, all other plugins work with no problems (including PlayerPoints, SaneEconomy, PermissionsEx, mcMMO, MysqlPlayerDataBridge). AdvancedBan lost connection during the day at random point, no lags or anything like that. Mysql shouldn't be overloaded. BungeeCord has 4Gb of RAM, just in case.

**Comment by DevLeoko** [comment]
I've checked the MySQL-Manager again and may have found the issue, I'll try to make a fix for that next weekend

**Comment by DevLeoko** [comment]
Forgot about that issue ^^ it got solved a long time ago in v2.1.0+
