### ISSUE TITLE
Problems while using special characters with MySQL

### ISSUE THREAD

**Issue by personinblack** [DevLeoko/AdvancedBan#74]
**_What version of AdvancedBan (`/AdvancedBan`) are you using?_**
 Version • 2.0.6
 
**_What kind of server do you have (`Bungeecord/single server`)?_**
 single server
 
**_What server version (/version) are you using?_**
PaperSpigot 1.8.8 "4c7641d"

**_Please provide the EXACT steps required to reproduce the problem..._**
1. Set "UseMySQL" to true in order to use MySQL.
2. Ban anyone with these characters in reason: " ı - ğ - ş "
3. Voila! The characters are replaced with " ? ".

**Any error/log post it through [pastebin.com](http://pastebin.com) and link it here.**
No error.

**_Add any aditional information below._**
The MySQL setup supports these characters. I'm pretty sure about that.

**Comment by DevLeoko** [comment]
Well MySQL does not seem to support them when they are not displayed properly

**Comment by Personinblack** [comment]
So... Is  there anything I can try to fix this? Is it because of my MySQL setup or AdvancedBan?
Sorry for the late reply.

**Comment by DevLeoko** [comment]
Why don't you use FlatFile instead of MySQL?

**Comment by Personinblack** [comment]
Ahh, screw me I forgot this issue... I'm using MySQL because I have a web page for listing bans. Sorry for my very very late reply.

**Comment by DevLeoko** [comment]
Do you still have the same issue?

**Comment by Personinblack** [comment]
Yep...

**Comment by DevLeoko** [comment]
does your MySQL-Server, your Database and the Table support UTF8?

**Comment by Personinblack** [comment]
Yes they support UTF8 except the table. While AuthMe's table is "utf8_general_ci", AdvancedBan's tables are "latin1_swedish_ci". Could changing them manually cause something bad?

**Comment by Personinblack** [comment]
![145](https://cloud.githubusercontent.com/assets/24732321/26780717/ab96c414-49f3-11e7-945e-f0edb2664c0e.png)
Changed tables' and every row's collation manually and restart the server but its still the same:
![146](https://cloud.githubusercontent.com/assets/24732321/26780965/d04c51c4-49f4-11e7-85fc-083a5af779dc.png)

**Comment by DevLeoko** [comment]
Okey then I'll have to change the SQL-Statements, will be fixed in the next update

**Comment by Personinblack** [comment]
Thanks!

**Comment by DevLeoko** [comment]
Please don't close the issue as the bug is not solved yet ;)

**Comment by calvin487487** [comment]
Same problems in Chinese...

**Comment by BrainStone** [comment]
@DevLeoko when creating the table be sure to set the character encoding to UTF-8 and work with UTF-8 strings everywhere

**Comment by Kundello** [comment]
Same problems in Russian...

**Comment by Alex4386** [comment]
Same Issue in Korean.
Seems to be unicode is not correctly handled in the command-parsing-side.
@DevLeoko

**Comment by DevLeoko** [comment]
Does the latest build fix your issue? http://v.skamps.eu/jenkins/job/AdvancedBanV2/37/ @Alex4386

**Comment by Alex4386** [comment]
@DevLeoko Problem solved.

**Comment by DevLeoko** [comment]
Thanks for the feedback
