### ISSUE TITLE
cannot use Message layout as a reason

### ISSUE THREAD

**Issue by NurPech** [DevLeoko/AdvancedBan#75]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
  2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.11.2

_Please provide the EXACT steps required to reproduce the problem..._
1. Executing a command with a message layout as reason eg. /tempban player #TimeLayout @MessageLayout
2. This will result in: player got banned by operator
For the reason @MessageLayout
This player got banned for 29min and 59sec
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
The message layout will not be parsed. The ban reason will be @ExampleLayout

_Add any aditional information below._

**Comment by DevLeoko** [comment]
That's weird could you please post your server address and tell me when you will be online so that I can check this on your server? Or just add me on Skype: Leoko33

**Comment by NurPech** [comment]
I've send you a skype invitation. I won't publish my ID here, because it's my company account. I think my name could help you with identify me: René Gessinger
