### ISSUE TITLE
Eclipse Code Error

### ISSUE THREAD

**Issue by ItzSomebody** [DevLeoko/AdvancedBan#76]
_Please provide the EXACT steps required to reproduce the problem..._
1. Import the source for the project through Eclipse
2. Navigate to me.leoko.advancedban.manager.MessageManager.java
3. Lines 24 & 32.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
Invalid Character Constant

_Add any aditional information below._

Eclipse is giving a headache about: str = replace(str, parameters).replace('&', 'Â§');

Specifically it doesn't like 'Â§'. Is there a way around this?

**Comment by DevLeoko** [comment]
Ya you can change the encoding to UTF-8
just google how to do this for eclipse

**Comment by ItzSomebody** [comment]
Boi, am I stupid xD
