### ISSUE TITLE
Request | Compatibility with Redis

### ISSUE THREAD

**Issue by TheJanRG** [DevLeoko/AdvancedBan#77]
This is a feature request.

Well, AdvancedBan is actually one of the best ban plugins. There's just one thing, I would need for compatibility with the server, I'm currently working on. The feature would be the compatibility with multiple proxies via Redis/RedisBungee. As a colleague said, it isn't very much work, to add this feature, but it would be awesome, and on the server network where we would use it, this is very important to have such a feature as soon as possible. [The network has always about 250 - 300 players].

Thank you for reading :)

**Comment by DevLeoko** [comment]
Thanks for the suggestion but as there are not so many people using RedisBungee it might take some time until this feature will be implemented.
But if you have any Devs on your team they can implement this my themselves as the plugin is open source :)

**Comment by Foorack** [comment]
@DevLeoko Following the merge of this https://github.com/DevLeoko/AdvancedBan/pull/132 pull request, can this issue be closed?

**Comment by DevLeoko** [comment]
Ya thanks
