### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by RedstoneCoder** [DevLeoko/AdvancedBan#78]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Singler Server
 
_What server version (/version) are you using?_
1.11.2

_Add any aditional information below._
I am trying to access the ban system using the "ab.*" permission as an owner but I am unable to as it says I have no permission.  Help?!?!

**Comment by DevLeoko** [comment]
make sure that your permissions system supports *-Perms

**Comment by ItzSomebody** [comment]
Don't use Group Manager

**Comment by DevLeoko** [comment]
@RedstoneCoder if you don't reply to this issue within 48 hours it will be closed

**Comment by DevLeoko** [comment]
Closed due to no response from the user!
