### ISSUE TITLE
[Suggestion] Disable some AdvancedBan commands

### ISSUE THREAD

**Issue by OrlandoLaCrue** [DevLeoko/AdvancedBan#79]
I would like some commands for AdvancedBan to be disable via config.yml

-Thanks!

**Comment by A248** [comment]
Commands aren't dynamically registered on Spigot. Once defined in AdvancedBan's plugin.yml, a command is necessarily registered.

If you want to disable a command, you have a few options:

1. Remove the command's permission from your administrators. If they run the command, they'll receive a no-permission message (configured in the messages.yml). This is definitely the simplest solution.
2. Override the command in commands.yml. This will completely prevent the command from being registered by any plugin. Examples and information on how to do this are [here](https://bukkit.gamepedia.com/Commands.yml#Alias_Examples)
