### ISSUE TITLE
[Feature Request] Events

### ISSUE THREAD

**Issue by Simonsator** [DevLeoko/AdvancedBan#84]
Hi,
Could you add Events inside the API, so other plugins can delete their data if someone was banned forever.

**Comment by DevLeoko** [comment]
Ya sounds good, will be implemented ^^

**Comment by ItzSomebody** [comment]
So basically 
boolean isBanned = Database.get().isPlayerBanned(uuid, ip);

**Comment by DevLeoko** [comment]
Added in 2.1.0 ;)
