### ISSUE TITLE
Hey, i cant register my account on Banpanel.net.

### ISSUE THREAD

**Issue by TunikaGruss** [DevLeoko/AdvancedBan#87]
Hey,
i cant register me because he cant connect to the Database. I tipped all Information right and it wont work!

**Comment by Beelzebu** [comment]
Did you checked if the sql port is open to external connections?

**Comment by TunikaGruss** [comment]
Where i can do it?

**Comment by ItzSomebody** [comment]
Are you using IPTables?

**Comment by TunikaGruss** [comment]
Its on My Debian V-Server with Mysql and phpmyadmin

2017-06-02 6:19 GMT+02:00 ItzSomebody <notifications@github.com>:

**Comment by Beelzebu** [comment]
If you are using some firewall you need to allow connections to the MySQL port that by default is 3306, but may be your problem is that the MySQL server is binded to 127.0.0.1 to allow only internal connections, to bind it to the public IP address find the my.cnf file /etc/mysql/ and change the following line
`bind-address = 127.0.0.1`
to
`#bind-address = 127.0.0.1`

**Comment by DevLeoko** [comment]
@TunikaGruss if you don't reply to this issue within 48 hours it will be closed

**Comment by TunikaGruss** [comment]
How can i restart MYsql?

**Comment by DevLeoko** [comment]
Google is your best friend ;) http://lmgtfy.com/?q=restart+mysql
First link: https://coolestguidesontheplanet.com/start-stop-mysql-from-the-command-line-terminal-osx-linux/

**Comment by TunikaGruss** [comment]
The MySQL-Data are not valid!
Failed: Host 'at-viex-inx-r16.ha184092.xenox.systems' is not allowed to
connect to this MySQL server

2017-06-09 18:48 GMT+02:00 DevLeoko <notifications@github.com>:

**Comment by TunikaGruss** [comment]
In The Mysql permissions there is no at-viex...

2017-06-09 20:43 GMT+02:00 TunikaGruss <tunikagruss@gmail.com>:

**Comment by DevLeoko** [comment]
Did you try what @Beelzebu told you to do above?

**Comment by TunikaGruss** [comment]
Its on my V-Server i dont know where to disable the Port in the Host Firewall!

**Comment by DevLeoko** [comment]
find the my.cnf file /etc/mysql/ and change the following line
bind-address = 127.0.0.1
to
#bind-address = 127.0.0.1

**Comment by TunikaGruss** [comment]
I did this.

The MySQL-Data are not valid!
Failed: Host 'at-viex-inx-r16.ha184092.xenox.systems' is not allowed to
connect to this MySQL server

2017-06-10 14:12 GMT+02:00 DevLeoko <notifications@github.com>:

**Comment by DevLeoko** [comment]
Here is a detailed instruction how to make MySQL available for remote connections:
https://www.cyberciti.biz/tips/how-do-i-enable-remote-access-to-mysql-database-server.html

**Comment by ItzSomebody** [comment]
Is the port open?

**Comment by DrFallen** [comment]
Hi I'm trying to register but it comes up  AdvancedBan tables not found is there something I need to download first? If so I can't find it in the post.

**Comment by DevLeoko** [comment]
should not take longer than a few minutes. Otherwise, you may have misspelled your email address

**Comment by DevLeoko** [comment]
@TunikaGruss if you don't reply to this issue within 48 hours it will be closed
