### ISSUE TITLE
Bungeecord Event Error

### ISSUE THREAD

**Issue by LordByronRS** [DevLeoko/AdvancedBan#89]
I use the newest Bungeecord Version and everytime someone write something in the Chat, i get this error message in the Bungeecord Console: [WARNUNG] Event ChatEvent(super=TargetedEvent(sender=Legonoah08, receiver=net.md_5.bungee.ServerConnection@16d4fb0), cancelled=false, message=h) took 310.073.690ns to process!

**Comment by DevLeoko** [comment]
Ya this is because there are some performance issues with the mute system there will be a fix for that

**Comment by DevLeoko** [comment]
Fixed 2.1.0 ;)
