### ISSUE TITLE
 Failed fetching UUID of USER

### ISSUE THREAD

**Issue by haugsvar** [DevLeoko/AdvancedBan#92]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
 13:15:08 [INFO] CONSOLE executed command: /AdvancedBan
13:15:08 [INFO] -===== AdvancedBan v2 =====- 
13:15:08 [INFO]   Dev • Leoko
13:15:08 [INFO]   Status • Stabel
13:15:08 [INFO]   Version • 2.0.6
13:15:08 [INFO]   License • Public
13:15:08 [INFO]   MySQL • false
13:15:08 [INFO]   Prefix • AdvancedBan »
13:15:08 [INFO] -=========================- 

_What kind of server do you have (`Bungeecord/single server`)?_
 
 12:01:23 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:eab710b:1242

 
_What server version (/version) are you using?_

12:01:23 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:eab710b:1242

_Please provide the EXACT steps required to reproduce the problem..._
1. Try to login
2. Advancded ban fails to get a statisfactory replay from mojang api's for uuid
3. Get's kicked out

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

https://pastebin.com/4s4fXLsb

_Add any aditional information below._

**Comment by DevLeoko** [comment]
Ya you are getting the 429 Too Many Requests Error which means that your IP-Adress is requesting the Mojang-Server too often, maybe there are also some other plugins requesting UUIDs from their RestAPI.

The easiest solution would be to switch the UUID-Fetcher to internal or disable in completely

**Comment by FrostTaco** [comment]
This was happening to me until I enabled Intern, try that.

**Comment by DevLeoko** [comment]
Fixed in 2.1.0 ;)
