### ISSUE TITLE
HELP!!

### ISSUE THREAD

**Issue by Techno3600** [DevLeoko/AdvancedBan#93]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Latest, look at the pastebin
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Look at the pastebin
 
_What server version (/version) are you using?_
Look at the pastebin

_Please provide the EXACT steps required to reproduce the problem..._
1. Try joining
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/WMTq0Rp7

_Add any aditional information below._

**Comment by ItzSomebody** [comment]
Same as https://github.com/DevLeoko/AdvancedBan/issues/92

Try setting the UUID-Fetcher to internal

**Comment by Techno3600** [comment]
I did, still nothing changes

**Comment by DevLeoko** [comment]
well at least there should now be a different error message

**Comment by DevLeoko** [comment]
@Techno3600 if you don't reply to this issue within 48 hours it will be closed
