### ISSUE TITLE
Cannot use bans/kicks/anything

### ISSUE THREAD

**Issue by FrostTaco** [DevLeoko/AdvancedBan#96]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
https://gyazo.com/96654345d8fadb288d96213fae5ee8ce
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
https://gyazo.com/abe127b62c40c1cd5ec57e5c03f6523f

_Please provide the EXACT steps required to reproduce the problem..._
1. Log on to the server.
2. Attempt banning someone.
3. Watch the ban fail.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/8Q84NSLv

_Add any aditional information below._
version wouldn't work on the bungeecord server.
UUID Fetcher Settings: https://gyazo.com/a0843ce4387a668e531f841237d7240a

**Comment by DevLeoko** [comment]
please post your UUID-Fetcher settings

**Comment by FrostTaco** [comment]
Just put the UUID Fetcher Settings in main post.

**Comment by DevLeoko** [comment]
Is your bungeecord for cracked users?
Pls paste a screen of /systemprefs

**Comment by FrostTaco** [comment]
My bungee is online mode. https://gyazo.com/512b358427eb1b552abd328c61f06c59

**Comment by DevLeoko** [comment]
Ya seems like the intern UUID fetcher is not working with your bungeecord version or with bungeecord in general. There are not so many people using Intern-UUIDFetcher in combination with Bungee so I've not heard about this bug yet. This will be solved when I start working again on this Plugin. If you want to try solving this issue you can switch your uuid fetcher to normal again, so not internal or can change the bungee-version.

**Comment by FrostTaco** [comment]
If you look at https://github.com/DevLeoko/AdvancedBan/issues/92 you can see I cant put it back to normal.

**Comment by jQuery0** [comment]
I have the same problem. After updating my Bungee, the external UUID-fetcher doesn't work. When logging in, it says "Failed to fetch your UUID". 

After that, I switched to internal UUID-fetcher which doesn't work. I can't perform any commands and it throws me this error in console: https://hastebin.com/kazacotiwa.lua

I would really appreciate if you fix this issue, sad to see one of the best punishment plugin inactive :(

**Comment by FrostTaco** [comment]
^^^ :'c

**Comment by DevLeoko** [comment]
check if fixed in 2.1.0

**Comment by FrostTaco** [comment]
Fixed :D Although I think its fixed in 2.1.1
