### ISSUE TITLE
UUID Fetcher - username toLowerCase problem

### ISSUE THREAD

**Issue by xPlux** [DevLeoko/AdvancedBan#97]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
git-Spigot-cd6ba67-a7d074c (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
I'm using my own BackUp-API for UUID Fetcher, but my API won't work correctly with ignoring case sensitivity. I would be grateful if you add an option to disable it.

**Comment by DevLeoko** [comment]
well, why don't you build in your API that it does ignore cases? AdvancedBan does not allow to disable  lowercase saving as sometimes the administrator types in the name randomly without knowing the case

**Comment by xPlux** [comment]
I want to disable lowercase saving only when I'm [asking my API](https://github.com/DevLeoko/AdvancedBan/blob/c4f6a347ea64860c11c7fcd2a9a814533244adcb/src/me/leoko/advancedban/manager/UUIDManager.java#L24). In my case it is hard to improve my API to work without case sensitivity. But I try to fix it or just fork your plugin.

**Comment by DevLeoko** [comment]
Well it will not solve the problem if you remove the toLowerCase in the UUID Fetcher as the punishments are already stored in lowercase.
But as you said you can just fork the plugin and try it out or try changing your API ;)
