### ISSUE TITLE
Please help me with API

### ISSUE THREAD

**Issue by fede1132** [DevLeoko/AdvancedBan#98]
Hi, i have problem with your api: 

new Punishment(event.getPlayer(), event.getPlayer().getUniqueId(), "Using cheats", "AntiCheat", PunishmentType.BAN, TimeManager.getTime(), -1, null, -1).create();

Error: The constructor Punishment(Player, UUID, String, String, PunishmentType, long, int, null, int) is undefined

**Comment by DevLeoko** [comment]
The first parameter is not a Player but the Player's name.

**Comment by fede1132** [comment]
new Punishment(event.getPlayer().getName(), event.getPlayer().getUniqueId(), "Using cheats", "AntiCheat", PunishmentType.BAN, TimeManager.getTime(), -1, null, -1).create();

Punishment cannot be resolved to a type 

https://gyazo.com/97358df1570213dece659c1fda85cf8a

**Comment by DevLeoko** [comment]
Dude you just have to match this constructor... 
`Punishment(String name, String uuid, String reason, String operator, PunishmentType type, long start, long end, String calculation, int id)`

**Comment by DevLeoko** [comment]
@fede1132 if you don't reply to this issue within 48 hours it will be closed
