### ISSUE TITLE
Unnotified stats collection

### ISSUE THREAD

**Issue by Ghostium** [DevLeoko/AdvancedBan#99]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.0.6 
 
_What kind of server do you have (`Bungeecord/single server`)?_
Bungeecord
 
_What server version (/version) are you using?_
git:BungeeCord-Bootstrap:1.12-SNAPSHOT:6958943:1244

Hey, I just noticed that you collect telemetry information at [Universal.java](https://github.com/DevLeoko/AdvancedBan/blob/master/src/me/leoko/advancedban/Universal.java#L79). I neither can find a hint about that in your plugin description nor I can find a option in the configuration to opt-out. If I'm not blind, I'm suggest to fix this, as it could cause you trouble under german data protection law. Under that you need to inform the user at some point about the data you collect and provide a mechnism (configuration option) to disable above mentioned stats collection.

It would be nice if you could add an opt-out option for both the stats and the update checker.

**Comment by DevLeoko** [comment]
Thanks for the advice I've just added this to the plugin page :)

> Data collection
Beside McStats there is also my private data collection RestAPI which does only track your player count of online players each 15min.
Also, there is an update checker which connects to my web server to check what the current Version of this resource is.
Please note:
>- By downloading and installing the plugin you agree to this kind of data collection
>- By checking the current version or reporting the player count your IP address is automatically logged by the web server
>- None of this can be disabled
>- I've no interest in doing anything bad with your data it just helps me to see how many people actually use my plugin and it helps you to always keep up to date ;D

Also, I'm going to add the disable option to my todo list but this has no priority sorry
